doc-src/scripting/inlinescripts.html
I updated the certutils.SSLCert reference from "libmproxy.certutils.SSLCert" to "netlib.certutils.SSLCert".
=> Updated inlinescripts.html - changed "libmproxy.certutils.SSLCert" to "netlib.certutils.SSLCert"

libmproxy/console/__init__.py
=> Error to stdout when loading bad replays from the command line

libmproxy/console/common.py, libmproxy/console/flowlist.py, libmproxy/console/flowview.py, libmproxy/flow.py, libmproxy/protocol/http.py
Hi Max, 
Adding str() fixed the issue thanks.
Here is the PR for issue #426 with that addition and the method renamed 
The created request is almost empty, only method and url are set by default, but everything else can be added using the flow editor. 
just let me know if you think more data needs to be precreated.
Regards.
Marcelo
=> Feature 426

libmproxy/console/flowdetailview.py, libmproxy/utils.py, test/test_utils.py
=> improvement to PR #496

libmproxy/console/flowdetailview.py, libmproxy/utils.py, test/test_utils.py
Hi Max,
I've added detailed timing information to FlowDetailView, as you requested in #487 
They are in the same order that where in the screenshot and then are sorted by timestamp like is done in https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/web/static/app.js#L1084 
there is no delta for now, but can [easily] be added later.
Regards.
Marcelo
=> Feature 487 ii

web/package.json
Decide to modify or just wait `react-router` to update.
=> update package.json during transition period, see #518

libmproxy/console/flowdetailview.py, libmproxy/console/help.py, test/test_console_help.py
Hi,
Setting loop.widget was missing in return from help, also in flowdetailview.py which produced a similar issue.
with this changes i can't reproduce #522 any longer
Regards.
Marcelo
=> fix for #522

libmproxy/console/__init__.py
Not much to add: path was already a list
=> fixed exception in mitmproxy -c fix #535

libmproxy/flow.py
Hi,
I'm sending a PR for fixing #530 
Regards.
Marcelo
=> fix #530 set client_playback to None when client_playback is done

libmproxy/web/__init__.py
mitmweb is not starting the onboarding app even if commanded to. This patch fixes the issue.
=> mitmweb: start onboarding app if instructed to

libmproxy/console/contentview.py, libmproxy/flow.py, libmproxy/protocol/http.py, libmproxy/utils.py, test/test_protocol_http.py, test/test_utils.py
=> [#514] Add support for ignoring payload params in multipart/form-data

libmproxy/web/static/app.js, libmproxy/web/static/vendor.js, web/package.json, web/src/js/components/common.js
react-router 0.13.2, which includes https://github.com/rackt/react-router/pull/957, is shipped.
Should I use "mitmweb" rather than "web" for the prefix of commit logs?
cc: @mhils
=> mitmweb: upgrade to react-router 0.13.2

libmproxy/web/static/app.js, libmproxy/web/static/vendor.js, web/src/js/actions.js
Well, recent changes seemed to cause the issue. A small fix
Regards,
Wensheng Tang
=> web: fix delete flows

libmproxy/console/common.py
When save a content as a file instead of saving to clipboard, it asks if overwrite or not.
=> Check overwrite, when save to file instaed of clipboard

libmproxy/console/common.py
```
File "/Users/tunz/Documents/ing/mitm/mitmproxy/libmproxy/console/__init__.py", line 456, in run
self.loop.run()
File "/Library/Python/2.7/site-packages/urwid/main_loop.py", line 278, in run
self._run()
File "/Library/Python/2.7/site-packages/urwid/main_loop.py", line 375, in _run
self.event_loop.run()
File "/Library/Python/2.7/site-packages/urwid/main_loop.py", line 678, in run
self._loop()
File "/Library/Python/2.7/site-packages/urwid/main_loop.py", line 715, in _loop
self._watch_files[fd]()
File "/Library/Python/2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
event_loop, callback, self.get_available_raw_input())
File "/Library/Python/2.7/site-packages/urwid/raw_display.py", line 492, in parse_input
callback(processed, …
```
=> Fix crash when save to clipboard before finishing loading

libmproxy/console/flowlist.py, libmproxy/console/grideditor.py, libmproxy/console/help.py, libmproxy/console/searchable.py
=> Match g/G shortcuts to less

examples/ignore_websocket.py, libmproxy/console/contentview.py, libmproxy/protocol/http_wrappers.py, libmproxy/utils.py, test/test_protocol_http.py, test/test_utils.py
=> move code to netlib

examples/read_dumpfile
=> Fixing issue #710. Prety printing in read_dumpfile

libmproxy/protocol/http.py, libmproxy/protocol/http_wrappers.py, libmproxy/protocol2/http.py, test/test_protocol_http.py
requires https://github.com/mitmproxy/netlib/pull/87
=> Proxy refactor cb

libmproxy/console/__init__.py, libmproxy/console/flowview.py, libmproxy/console/options.py, libmproxy/contentviews.py, libmproxy/dump.py, libmproxy/protocol/http.py, libmproxy/protocol/rawtcp.py, libmproxy/utils.py, setup.py, test/test_contentview.py, test/test_dump.py
This PR does a bunch of related things
- Colorize mitmdump output :sparkles: 
- Properly handle unicode in content views 
- Use content views for mitmdump output
- Simplify contentview api
=> Improve Content Views

examples/har_extractor.py, libmproxy/cmdline.py, libmproxy/console/common.py, libmproxy/console/flowview.py, libmproxy/dump.py, libmproxy/exceptions.py, libmproxy/flow.py, libmproxy/models/http.py, libmproxy/protocol/http.py, libmproxy/protocol/http_replay.py, libmproxy/protocol/tls.py, libmproxy/proxy/root_context.py, libmproxy/proxy/server.py, libmproxy/web/app.py, test/test_dump.py, test/test_filt.py, test/test_flow.py, test/test_fuzzing.py, test/test_protocol_http.py, test/test_proxy.py, test/test_server.py, test/tutils.py, web/src/js/components/flowview/messages.js
refs https://github.com/mitmproxy/netlib/pull/92, https://github.com/mitmproxy/pathod/pull/34
=> Adjust to netlib changes

docs/Makefile, docs/conf.py, docs/dev/models.rst, examples/dns_spoofing.py, examples/redirect_requests.py, libmproxy/console/common.py, libmproxy/console/flowview.py, libmproxy/dump.py, libmproxy/flow.py, libmproxy/models/http.py, libmproxy/protocol/http.py, libmproxy/protocol/tls.py, libmproxy/proxy/root_context.py, libmproxy/web/app.py, test/test_dump.py, test/test_flow.py, test/test_protocol_http.py, test/test_server.py
This is the mitmproxy part of mitmproxy/netlib#100, including full documentation for the Request and Response classes.
=> Refactor HTTP Models

CONTRIBUTING.md
Wrong link (REAMD.mkd -> README.rst)
=> Correct a wrong link in CONTRIBUTING.md

docs/certinstall.rst
=> doc typo fix

docs/install.rst
Otherwise install fails with error "--enable-jpeg requested but jpeg not found"
=> Update ubuntu installation to includ libjpeg

libmproxy/console/common.py
Hi @mhils 
This PR has only the changes to fix the exception thrown when trying to copy to clipboard option: headers+content (h key)
Cheers
Marcelo
=> fix copy to clipboard command when copying content

docs/certinstall.rst
If there is any other information that you feel should be included, please let me know.
=> Added information on cert pinning (Fixes #689)

examples/custom_contentviews.py, libmproxy/contentviews.py, libmproxy/flow.py, libmproxy/script.py, test/test_contentview.py, test/test_custom_contentview.py, test/test_script.py
Based on feedback from PR #832, simple custom content view support in scripts for mitmproxy/mitmdump.
=> Contentview scripts

libmproxy/console/__init__.py, libmproxy/flow.py, libmproxy/script.py
Simply add hotkey 's' on the flowview window, I'm not sure whether 's' key is the best choice for this function, but it works fine.
=> Add hotkey to reload all inline scripts #713

docs/features/responsestreaming.rst, docs/features/upstreamcerts.rst, docs/tutorials/gamecenter.rst
This PR was brought to you by [mwic](http://jwilk.net/software/mwic).
=> docs: fix typos

docs/certinstall.rst, libmproxy/cmdline.py, libmproxy/models/connections.py, libmproxy/proxy/config.py, test/test_proxy.py, test/test_server.py, test/tservers.py
This PR references the discussion made in Issue https://github.com/mitmproxy/mitmproxy/issues/867.
=> [docs/libmproxy/test] Support single client-side cert file

examples/sslstrip.py
Added sslstrip.py to the inline script examples. The script mimics the functionality of Moxie Marlinspike's popular standalone tool.
=> added sslstrip to inline script examples

libmproxy/cmdline.py, libmproxy/console/__init__.py, libmproxy/main.py
This pull request adds to mitmproxy (cli) an argument to enable the "follow flow list" as requested in #889.
=> Added CLI argument to enable "follow flow list" mode

docs/features/passthrough.rst, libmproxy/protocol/__init__.py, libmproxy/protocol/tls.py, libmproxy/proxy/root_context.py
=> Add ignore based on TLS ClientHello SNI

libmproxy/console/__init__.py
Adds feature requested in issue #714
=> Added feature to intercept flows from within inline scripts

libmproxy/cmdline.py, libmproxy/main.py, libmproxy/web/__init__.py, libmproxy/web/app.py
Added Basic Auth support for MITMWeb interface as requested in #802. It supports both single user format ("username:password") or .htpasswd file.
=> Added Basic Auth support for MITMWeb interface

libmproxy/console/__init__.py, libmproxy/models/http.py, libmproxy/protocol/http.py, libmproxy/protocol/http1.py, libmproxy/protocol/http2.py, libmproxy/protocol/tls.py, libmproxy/stateobject.py, libmproxy/web/app.py, test/test_console_help.py, test/test_filt.py, test/test_flow.py, test/test_protocol_http1.py, test/test_protocol_http2.py
Using autopep8 and autoflake tools.
Only minor changes.
=> Improve Coding Style

mitmproxy/mitmproxy/console/flowview.py
'P' can also be used on the request screen!
=> Fix misleading documentation for clipboard command

netlib/netlib/http/request.py, test/mitmproxy/test_flow.py, test/netlib/http/test_request.py
From: https://github.com/mitmproxy/netlib/pull/121
Also incorporates the [comment](https://github.com/mitmproxy/mitmproxy/issues/651#issuecomment-184007109) by @mhils
=> Handle port numbers in host header

examples/har_extractor.py
=> Fix minor issues with har_extractor

.appveyor.yml, .travis.yml, dev.bat
This should help us keep the install routine clean and tested on all platforms.
=> use dev-scripts on CI

mitmproxy/web/static/app.js, web/src/js/store/view.js
Use `_.sortedIndexBy` instead of `_.sortedIndex`, see https://lodash.com/docs#sortedIndex
=> [web] fix StoreView.index

mitmproxy/web/static/app.js, mitmproxy/web/static/vendor.js, web/src/js/components/flowtable.js, web/src/js/store/view.js
`FlowTable.scrollIntoView` doesn't work correctly when there are multiple flows with same value for sorting function.
Reproduce by:
- select a flow whose method is `GET`
- sort flows by method field
=> [web] fix FlowTable.scrollIntoView

mitmproxy/cmdline.py, mitmproxy/models/http.py, mitmproxy/protocol/http.py, mitmproxy/proxy/config.py, test/mitmproxy/test_cmdline.py, test/mitmproxy/test_proxy.py
=> Add upstream proxy authentication

mitmproxy/flow_export.py, test/mitmproxy/test_flow_export.py
=> Indent JSON body while exporting it as code

mitmproxy/web/static/app.js, web/src/js/components/common.js, web/src/js/components/footer.js, web/src/js/components/header.js, web/src/js/components/proxyapp.js
Eliminate `common.SettingsState` mixin with props.
=> [web] eliminate SettingsState

mitmproxy/web/static/app.css, web/src/css/footer.less
It looks pretty weird since #1009
=> [web] Fix label margin in footer

mitmproxy/web/static/app.js, web/src/js/components/eventlog.js
Props are frozen since React 0.14.
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#breaking-changes
=> [web] dont mutate props

mitmproxy/console/grideditor.py
=> Fix missing cookie import

mitmproxy/web/static/app.js, web/src/js/components/helpers/VirtualScroll.js
There will be an empty row at the end of the flow table when an odd row was preserved.
=> [web] fix virtual scroll range

netlib/socks.py, test/netlib/test_socks.py
Add `UsernamePasswordAuth` and `UsernamePasswordAuthResponse` to `netlib.socks`
=> Add 'UsernamePasswordAuth' 'UsernamePasswordAuthResponse' to SOCKS

setup.py
All tests passed here, and it works fine.
=> Allow lxml 3.6

mitmproxy/console/__init__.py, mitmproxy/flow.py, mitmproxy/script/reloader.py, mitmproxy/script/script.py, test/mitmproxy/script/test_concurrent.py, test/mitmproxy/script/test_reloader.py, test/mitmproxy/script/test_script.py, test/mitmproxy/scripts/concurrent_decorator.py, test/mitmproxy/test_examples.py, test/mitmproxy/test_script.py, test/mitmproxy/tutils.py
This PR slightly improves the semantics of `mitmproxy.script.Script` (Scripts must now be loaded explicitly or using a `with` statement) and cleans up the tests.
=> Better scripts

mitmproxy/flow_export.py
=> Generate better function names for root url.

mitmproxy/protocol/http2.py
=> cleanup h2 and test

mitmproxy/version.py, pathod/version.py
=> Fix `version.NAME`

mitmproxy/dump.py, netlib/utils.py, test/netlib/test_utils.py
=> Sanitize Print

mitmproxy/protocol/http2.py
=> Fixed HTTP2 headers being folded. (#1143)

mitmproxy/proxy/server.py
=> Change ProxyServerError to ServerException in the docstring

mitmproxy/protocol/http2.py
* immediately send push to client
* fix typo
* implement transparent Priority updates
* kill streams if connection gets terminated
=> Improve http2

mitmproxy/dump.py, mitmproxy/flow.py, mitmproxy/models/__init__.py, mitmproxy/models/flow.py, mitmproxy/models/http.py, mitmproxy/models/tcp.py, mitmproxy/protocol/rawtcp.py, mitmproxy/proxy/root_context.py, test/mitmproxy/scripts/tcp_stream_modify.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_server.py, test/mitmproxy/tservers.py, test/mitmproxy/tutils.py
This PR introduces support for saving TCP flows in dumpfiles. It's mitmdump only for now.
=> mitmdump: Add Basic Support for TCP Flows

.gitignore, dev.sh
This allows us to run e.g. tests in a different python version:
$ venv3/bin/py.test test/netlib/test_tcp.py
=> add a py3 venv in dev environment

.travis.yml, pathod/app.py, pathod/language/__init__.py, pathod/language/base.py, pathod/log.py, pathod/pathoc.py, pathod/pathod.py, pathod/utils.py, test/pathod/test_utils.py
Tests for the file `test/pathod/test_utils.py` pass with both Py2 & 3 interpreters.
=> Python 3 - pathod.utils

.travis.yml, pathod/language/generators.py, test/pathod/test_language_generators.py
Received a huge amount of help from the awesome folks at #python IRC :)
=> Python 3 - pathod.language.generators

README.rst
Feel free to not merge. I thought there should at least be a link to the installation instructions to stop issues like #1196.
fixes #1196
=> Add installation section to README

dev.sh
Let's try to work out what happened to the cryptography wheels.
=> Better debugging output.

mitmproxy/web/__init__.py, mitmproxy/web/app.py, mitmproxy/web/static/app.js, mitmproxy/web/static/vendor.js, web/src/js/actions.js, web/src/js/components/header.js, web/src/js/store/store.js, web/src/js/utils.js
download working, upload only for small files, do you have any hints ?
=> File menu save open

pathod/language/writer.py, test/pathod/test_language_writer.py
One of the test [`test_write_values_after`] still fails, but I don't think it has anything to do with this module.
=> Python 3 - pathod.language.writer

setup.py
All tests passed and it works correctly here.
=> Allow cryptography 1.4

mitmproxy/contentviews.py, test/mitmproxy/test_contentview.py
=> Change Contentviews: Escape in Raw Mode, Show UTF8 in JSON

examples/nonblocking.py, examples/redirect_requests.py, examples/tls_passthrough.py, mitmproxy/controller.py, mitmproxy/flow/master.py, mitmproxy/models/flow.py, mitmproxy/script/concurrent.py, test/mitmproxy/mastertest.py, test/mitmproxy/script/test_concurrent.py, test/mitmproxy/test_controller.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_server.py
Re-submitting to see  if we can jolt appveyor out of catatonia.
=> Controller refactoring

mitmproxy/web/static/app.js, mitmproxy/web/static/vendor.js, web/src/js/components/flowtable-columns.js, web/src/js/components/flowtable.js, web/src/js/components/mainview.js, web/src/js/ducks/flows.js, web/src/js/ducks/utils/view.js
moved sort state to redux state, and start with sorting the flow
=> Add sorting with redux

docs/scripting/inlinescripts.rst, examples/custom_contentviews.py, examples/filt.py, examples/flowwriter.py, examples/har_extractor.py, examples/iframe_injector.py, examples/modify_response_body.py, examples/proxapp.py, examples/sslstrip.py, examples/stub.py, examples/tcp_message.py, examples/tls_passthrough.py, mitmproxy/script/script.py, test/mitmproxy/data/scripts/a.py, test/mitmproxy/data/scripts/concurrent_decorator_err.py, test/mitmproxy/data/scripts/starterr.py
=> Inline Scripts: use sys.argv instead of args argument.

test/mitmproxy/completion/bbb/Readme.md, test/mitmproxy/console/test_pathedit.py
I've not used mock/patch before so I'm not sure if this is the correct
way to test the things.
=> mitmproxy.console tests - PathEdit

docs/install.rst
Windows install failed due to out of date pip. Show how to upgrade to latest pip.
=> Show how to upgrade pip.

mitmproxy/protocol/http2.py, test/mitmproxy/test_protocol_http2.py, test/netlib/tservers.py
=> http2: tests++

examples/har_extractor.py, test/mitmproxy/test_examples.py, tox.ini
=> Exclude harparser script on Python 3

mitmproxy/protocol/http2.py, test/mitmproxy/test_protocol_http2.py, tox.ini
=> HTTP/2: Python 3-compatibility

mitmproxy/protocol/http2.py
=> http2: fix self-depended streams

mitmproxy/contentviews.py, mitmproxy/dump.py, mitmproxy/models/http.py, netlib/strutils.py, test/mitmproxy/test_dump.py, test/netlib/test_strutils.py, tox.ini
=> Python 3 - test_dump

mitmproxy/flow/modules.py, netlib/http/cookies.py, test/mitmproxy/test_flow.py, test/netlib/http/test_cookies.py
=> Delete stickycookies when told by the server

release/rtool.py
=> rtool hotfix

.travis.yml
@mhils is this everything need to fix #1332?
=> move OSX Travis job to py3 for snapshots

mitmproxy/builtins/__init__.py, mitmproxy/builtins/stream.py, mitmproxy/dump.py, mitmproxy/flow/master.py, test/mitmproxy/builtins/test_stream.py, test/mitmproxy/mastertest.py, test/mitmproxy/test_dump.py, test/mitmproxy/test_flow.py
This commit also clarifies a confusion about the "outfile" attribute and its
use in testing in the mitmdump master.
=> Streaming to file -> addon

mitmproxy/builtins/script.py, mitmproxy/cmdline.py, mitmproxy/console/flowlist.py, mitmproxy/console/flowview.py, mitmproxy/console/master.py, mitmproxy/console/palettes.py, mitmproxy/console/signals.py, mitmproxy/controller.py, mitmproxy/dump.py, mitmproxy/flow/master.py, mitmproxy/flow/options.py, mitmproxy/main.py, mitmproxy/utils.py, mitmproxy/web/master.py, test/mitmproxy/mastertest.py, test/mitmproxy/test_dump.py, test/mitmproxy/test_examples.py, test/mitmproxy/tservers.py
- mitmdump returns error exit status when an error has been logged
- mitmproxy flashes a user notification when an error has been logged
- add_event -> add_log throughout, with other associated name changes
=> Some work on errors and logs

mitmproxy/builtins/__init__.py, mitmproxy/builtins/replace.py, mitmproxy/console/master.py, mitmproxy/console/options.py, mitmproxy/console/statusbar.py, mitmproxy/dump.py, mitmproxy/flow/master.py, netlib/http/headers.py, test/mitmproxy/builtins/test_replace.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_server.py, test/mitmproxy/tservers.py
Also fixes a bug in header replacements in netlib that resulted in a mutable
multidict.
=> replacehooks -> addon

mitmproxy/builtins/__init__.py, mitmproxy/builtins/filestreamer.py, mitmproxy/flow/master.py, test/mitmproxy/builtins/test_filestreamer.py
- stream -> filestreamer throughout
- move active_flows set into FileStreamer addon
=> Some work on stream-to-file

mitmproxy/console/common.py, mitmproxy/console/flowlist.py, mitmproxy/console/flowview.py, mitmproxy/console/grideditor.py, mitmproxy/console/master.py, mitmproxy/console/options.py, mitmproxy/console/statusbar.py, mitmproxy/flow/master.py, mitmproxy/options.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_options.py
- file -> open in console
- add a .toggler() helper to options
- use setters, togglers in console
- move more things from master to options
=> Console-related cleanups 

.appveyor.yml
=> add Windows py3 builds

mitmproxy/console/common.py, mitmproxy/console/flowlist.py, mitmproxy/console/flowview.py, mitmproxy/flow/export.py, test/mitmproxy/test_flow_export.py
Fixes #976
Things still left to do:
=> Flow Export Improvements

mitmproxy/protocol/http2.py
fixes #1395
Not sure if this will do the trick...
=> http2: fix kill

mitmproxy/console/searchable.py
=> Fix console search on Python 3

mitmproxy/console/master.py
=> Fix clearing of flows

web/src/css/flowdetail.less, web/src/js/components/FlowView/Headers.jsx
Fix https://github.com/mitmproxy/mitmweb/issues/37
=> [web] fix flow editing style

mitmproxy/console/help.py, mitmproxy/console/window.py
The command line options are still the same though.
=> Consolidate replay under R

mitmproxy/dump.py
=> mitmdump: send script .done when terminating after flow read

mitmproxy/console/master.py, mitmproxy/console/signals.py
=> console: add replace_view_state, fix statusbar issues

mitmproxy/proxy/config.py
=> Add missing ssl_insecure option

mitmproxy/console/window.py
=> Better status message on mouse drag

mitmproxy/web/app.py, mitmproxy/web/static/app.js, mitmproxy/web/static/vendor.js, web/src/css/dropdown.less, web/src/js/components/ContentView/CodeEditor.jsx, web/src/js/components/ContentView/ContentViews.jsx, web/src/js/components/ContentView/UploadContentButton.jsx, web/src/js/components/ContentView/ViewSelector.jsx, web/src/js/components/Footer.jsx, web/src/js/components/Header/FileMenu.jsx, web/src/js/components/Header/FlowMenu.jsx, web/src/js/components/Header/OptionMenu.jsx, web/src/js/components/common/Dropdown.jsx, web/src/js/components/common/FileChooser.jsx, web/src/js/components/common/ToggleInputButton.jsx, web/src/js/ducks/flows.js, web/src/js/ducks/ui/flow.js, web/src/js/utils.js
=> Web refactor

docs/dev/models.rst, examples/redirect_requests.py, mitmproxy/console/flowview.py, netlib/http/response.py, test/netlib/http/test_response.py
This PR adds Response.make() so that addons have a reasonable API to create replies.
=> Introduce Response.make for simple response creation

netlib/strutils.py, test/netlib/test_strutils.py
Fixed https://github.com/mitmproxy/mitmproxy/issues/1501
=> fixed #1501 : Divide by zero error came when string was empty, also a test

.travis.yml, setup.py
=> cryptography 1.5

netlib/encoding.py, setup.py, test/netlib/test_encoding.py
=> bump brotli dependency

mitmproxy/addons.py, mitmproxy/builtins/serverplayback.py, mitmproxy/console/master.py, mitmproxy/console/statusbar.py, mitmproxy/console/window.py, test/mitmproxy/test_addons.py
Fix interaction and immediate crash.
=> Fix server replay in mitmproxy console

mitmproxy/builtins/script.py, mitmproxy/console/master.py, mitmproxy/dump.py, mitmproxy/flow/master.py, test/mitmproxy/builtins/test_script.py
=> Add "run_once" support to the script addon, use it in mitmproxy

mitmproxy/console/flowlist.py, mitmproxy/console/help.py, mitmproxy/console/statusbar.py
- Fix "S" shortcut in list view
- Consolidate replay from file in global R shortcut
- Fix help
=> console: fix/improve server replay

mitmproxy/builtins/__init__.py, mitmproxy/builtins/clientplayback.py, mitmproxy/builtins/dumper.py, mitmproxy/console/flowlist.py, mitmproxy/console/flowview.py, mitmproxy/console/master.py, mitmproxy/console/statusbar.py, mitmproxy/dump.py, mitmproxy/exceptions.py, mitmproxy/flow/__init__.py, mitmproxy/flow/master.py, mitmproxy/flow/modules.py, test/mitmproxy/builtins/test_clientplayback.py, test/mitmproxy/mastertest.py, test/mitmproxy/test_dump.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_server.py
- Client replay to addon
- Use a way simpler synchronisation mechanism
- Misc cleanups
=> revamp client replay

netlib/tcp.py
=> allow socket creation monkeypatchs

mitmproxy/builtins/termlog.py, mitmproxy/controller.py, mitmproxy/dump.py, mitmproxy/flow/master.py, mitmproxy/proxy/__init__.py, mitmproxy/proxy/root_context.py, mitmproxy/proxy/server.py, test/mitmproxy/builtins/test_termlog.py, test/mitmproxy/data/addonscripts/recorder.py, test/mitmproxy/data/scripts/all.py, test/mitmproxy/mastertest.py, test/mitmproxy/tservers.py
- Make log event handler work
- Move terminal event log into an addon
- Clean various log related errors and duplications
=> Consolidate logging

docs/certinstall.rst
Made changes in the documentation on how to use a custom certificate with mitmproxy
=> Issue 1461

mitmproxy/console/flowlist.py, mitmproxy/console/flowview.py, mitmproxy/flow/master.py, mitmproxy/flow/state.py, mitmproxy/web/app.py, test/mitmproxy/data/addonscripts/duplicate_flow.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_flow_state.py
This is a pure operation on state, and doesn't belong on master.
Part of prep to move state to an addon.
=> master.duplicate_flow -> state.duplicate_flow

mitmproxy/addons.py, mitmproxy/console/flowlist.py, mitmproxy/console/flowview.py, mitmproxy/console/master.py, mitmproxy/controller.py, mitmproxy/dump.py, mitmproxy/flow/__init__.py, mitmproxy/flow/master.py, mitmproxy/flow/state.py, mitmproxy/models/flow.py, mitmproxy/web/app.py, mitmproxy/web/master.py, test/mitmproxy/builtins/test_anticache.py, test/mitmproxy/builtins/test_anticomp.py, test/mitmproxy/builtins/test_dumper.py, test/mitmproxy/builtins/test_filestreamer.py, test/mitmproxy/builtins/test_replace.py, test/mitmproxy/builtins/test_script.py, test/mitmproxy/builtins/test_serverplayback.py, test/mitmproxy/builtins/test_setheaders.py, test/mitmproxy/builtins/test_stickyauth.py, test/mitmproxy/builtins/test_stickycookie.py, test/mitmproxy/builtins/test_streambodies.py, test/mitmproxy/mastertest.py, test/mitmproxy/script/test_concurrent.py, test/mitmproxy/test_examples.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_flow_state.py, test/mitmproxy/test_server.py, test/mitmproxy/tservers.py
Convert state to an addon - clocks in at -50 LOC.
=> Convert flow.state to an addon

mitmproxy/console/master.py, mitmproxy/controller.py, mitmproxy/dump.py, mitmproxy/flow/master.py, mitmproxy/main.py, mitmproxy/proxy/server.py, mitmproxy/web/master.py, test/mitmproxy/builtins/test_anticache.py, test/mitmproxy/builtins/test_anticomp.py, test/mitmproxy/builtins/test_dumper.py, test/mitmproxy/builtins/test_filestreamer.py, test/mitmproxy/builtins/test_replace.py, test/mitmproxy/builtins/test_script.py, test/mitmproxy/builtins/test_serverplayback.py, test/mitmproxy/builtins/test_setheaders.py, test/mitmproxy/builtins/test_stickyauth.py, test/mitmproxy/builtins/test_stickycookie.py, test/mitmproxy/builtins/test_streambodies.py, test/mitmproxy/console/test_master.py, test/mitmproxy/script/test_concurrent.py, test/mitmproxy/test_addons.py, test/mitmproxy/test_controller.py, test/mitmproxy/test_dump.py, test/mitmproxy/test_examples.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_flow_state.py, test/mitmproxy/test_web_app.py, test/mitmproxy/test_web_master.py
It's simple enough to re-add if needed, and until then is just cruft.
=> Let's dispense with this fiction that we support multiple servers

examples/har_dump.py, pathod/language/generators.py, test/mitmproxy/test_examples.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_utils_strutils.py
This PR is based on @slobo's #1650 and fixes various encoding inconsistencies around the HAR dumper.
=> Encoding Fixes

setup.py, tox.ini
An extremely modest beginning, but we'll roll this out over the whole codebase
in time.
Also move flake8 and mypy dependencies into setup[dev].
=> Add mypy to lint

mitmproxy/connections.py, mitmproxy/io_compat.py, mitmproxy/tools/console/flowdetailview.py, test/mitmproxy/tutils.py
Resolved #582 
Display the select cipher of TLS on the tui
=> Resolved #582: display ClientConnection select cipher of TLS

mitmproxy/addons/view.py, setup.py, test/mitmproxy/addons/test_view.py
A replacement for addons.State that has a clear interface and internal design.
=> addons.View

mitmproxy/addons/dumper.py, mitmproxy/contentviews.py, mitmproxy/options.py, mitmproxy/tools/console/flowview.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/options.py, mitmproxy/tools/console/statusbar.py, test/mitmproxy/test_contentview.py
This is the first step in a longer process of revamping content views. For the
moment, the option is not exposed on the command line.
=> Add options.default_contentview

mitmproxy/addons/view.py, mitmproxy/tools/cmdline.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/help.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/window.py, mitmproxy/tools/main.py, test/mitmproxy/addons/test_view.py
"o" shortcut and --order cmdline option to change flow order.
Options is now bound to "O".
=> console: o for flow order

mitmproxy/tools/console/common.py, mitmproxy/tools/console/statusbar.py
- Arrow to show flow order
- Hook statusbar up to focus change to fix some update issues
=> console: status bar improvements

docs/tutorials/transparent-dhcp.rst
Update with service restart commands for Ubuntu 16.04+.
Add sudo prefix to iptables commands.
=> Update for Ubuntu 16.04

mitmproxy/addons/dumper.py, mitmproxy/test/tflow.py, test/mitmproxy/addons/dumperview.py, test/mitmproxy/addons/test_dumper.py
- 100% test coverage
- Cleanups
- Add test/mitmproxy/addons/dumperview.py, a small utility for viewing dumper
output variations
=> addons: dumper spit and polish

mitmproxy/addons/setheaders.py, mitmproxy/addons/view.py, test/mitmproxy/addons/test_anticache.py, test/mitmproxy/addons/test_anticomp.py, test/mitmproxy/addons/test_replace.py, test/mitmproxy/addons/test_setheaders.py, test/mitmproxy/addons/test_stickycookie.py, test/mitmproxy/addons/test_termlog.py, test/mitmproxy/addons/test_view.py
This takes coverage for all of /addons to 100%
=> addons.view: test suite to 100%

pathod/language/writer.py
Resolves #1541 
The error no longer comes up
Ran py.test and all tests succeeded as well.
=> Allow pathoc to pause forever at end of message

mitmproxy/proxy/protocol/http2.py
This PR removes the monkey-patching of h2 connection objects dynamically added to `client_conn` and `server_conn` in the HTTP/2 protocol.
=> http2: move h2 connection object

test/netlib/test_tcp.py
Try updating ciphers to see if this fixes Travis builds.
=> test/netlib/test_tcp: Update ciphers

mitmproxy/proxy/protocol/tls.py
fixes #1737
If the client has already negotiated an ALP, then force the server to use the same. 
Otherwise we get a protocol mismatch between client <-> server.
But in order for HTTP/2 to work properly we have to relay some messages directly between client and server.
This can only happen if the host gets changed after the initial connection was established. 
E.g.:
* Client tries to open an HTTPS url,
* the client offers http/1.1 and h2,
* the initial host is only capable of http/1.1,
* then the first server connection negotiates http/1.1,
* but after the server_conn change, the new host offers h2
* which results in garbage because the layers don' match.
@muralisr can you please test if this patch fixes your problem?
=> restrict ALPN offers if host changes

mitmproxy/net/tcp.py, test/mitmproxy/net/test_tcp.py
=> Descriptive error message for SSL context initialization failure

mitmproxy/flowfilter.py, mitmproxy/proxy/protocol/websocket.py, test/mitmproxy/protocol/test_websocket.py
This PR adds compatibility to pass most of the Autobahn WebSocket tests.
=> Pass Autobahn WebSocket Test Suite

.travis.yml, mitmproxy/net/tcp.py, test/conftest.py, test/mitmproxy/net/test_tcp.py, test/mitmproxy/protocol/test_http2.py, test/mitmproxy/test_dump.py, test/pathod/test_pathoc.py, test/pathod/test_pathod.py, test/pathod/test_protocols_http2.py, tox.ini
=> simplify ALPN and OpenSSL on macOS

release/rtool.py
=> release: fix dropping _main suffix

mitmproxy/contrib/tls/__init__.py, mitmproxy/contrib/tls_parser.py, mitmproxy/proxy/protocol/tls.py, test/mitmproxy/contrib/test_tls_parser.py, test/mitmproxy/protocol/test_tls.py
=> tls_parser: allow optional extensions

mitmproxy/tools/console/master.py
=> console: use an addon to capture logs

mitmproxy/addons/script.py, mitmproxy/optmanager.py, mitmproxy/tools/console/grideditor/editors.py, mitmproxy/tools/main.py, test/mitmproxy/addons/test_script.py, test/mitmproxy/test_optmanager.py, test/mitmproxy/test_proxy.py
=> options: add a merge method to assimilate options

mitmproxy/proxy/protocol/http.py
=> Catch occasional protocol errors in regular connect

mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/statusbar.py, test/mitmproxy/addons/test_view.py
=> console: mark view indiciator, fix empty flow list behaviour

docs/scripting/overview.rst, mitmproxy/events.py
=> Addon test docs, remove stray deprecated events

README.rst
I'm getting started on this project again and could not install with the instructions in the "Hacking" section. This PR updates the instructions which worked for me on Ubuntu 16.04.
=> Update instructions in README

.gitignore, docs/install.rst, issue_template.md, mitmproxy/test/tutils.py, mitmproxy/tools/cmdline.py, mitmproxy/tools/main.py, mitmproxy/utils/__init__.py, mitmproxy/utils/bits.py, mitmproxy/utils/debug.py, test/mitmproxy/addons/test_script.py, test/mitmproxy/utils/test_debug.py, tox.ini
=> provide git information with --version

mitmproxy/tools/web/app.py, web/src/js/components/FlowView.jsx, web/src/js/filt/filt.js, web/src/js/filt/filt.peg
Adds `~marked` filter as in #1915
=> web: Add ~marked filter

web/src/js/filt/filt.js, web/src/js/filt/filt.peg
=> web: Add ~http and ~tcp filters

setup.py, test/mitmproxy/addons/test_clientplayback.py, test/mitmproxy/addons/test_dumper.py, test/mitmproxy/addons/test_evenstore.py, test/mitmproxy/console/test_pathedit.py, test/mitmproxy/contentviews/test_api.py, test/mitmproxy/mock_urwid.py, test/mitmproxy/net/http/http1/test_read.py, test/mitmproxy/net/http/test_cookies.py, test/mitmproxy/net/http/test_encoding.py, test/mitmproxy/net/test_tcp.py, test/mitmproxy/test_controller.py, test/mitmproxy/test_flowfilter.py, test/mitmproxy/test_proxy.py, test/mitmproxy/test_server.py, test/mitmproxy/test_web_app.py, test/mitmproxy/utils/test_typecheck.py, test/mitmproxy/utils/test_version_check.py, test/pathod/test_pathoc.py, test/pathod/test_pathoc_cmdline.py, test/pathod/test_pathod_cmdline.py, test/pathod/test_protocols_http2.py
This is already included in Python 3.3+ as unittest.mock
=> nuke mock dependency

web/src/js/filt/filt.js, web/src/js/filt/filt.peg
I have mentioned the problem with `~s` and `~src` in Slack.
=> web: Add ~src and ~dst filters

web/src/js/filt/filt.js, web/src/js/filt/filt.peg
Done as per Slack.
:stuck_out_tongue:
=> web: Add body filters

mitmproxy/addons/termlog.py, test/mitmproxy/addons/test_termlog.py
Modified the termlog file as suggested in the comments on issue [#1939](https://github.com/mitmproxy/mitmproxy/issues/1939)
=> Fix errors on stdout

mitmproxy/addons/onboarding.py, mitmproxy/addons/view.py, mitmproxy/options.py, mitmproxy/optmanager.py, mitmproxy/tools/cmdline.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/options.py, mitmproxy/tools/console/palettepicker.py, mitmproxy/tools/console/statusbar.py, mitmproxy/tools/main.py, mitmproxy/tools/web/master.py, test/mitmproxy/addons/test_view.py
- Onboarding app options to onboarding*
- Console-specific options to console_*
- Web-specific options to web_*
=> Consolidate option names

mitmproxy/tools/console/flowlist.py
Fixed a focus_follow that was missed when options were cleaned up.
=> Fixed following on flowlist

mitmproxy/addons/view.py, mitmproxy/tools/console/flowlist.py, test/mitmproxy/addons/test_view.py
'Z' now keeps the marked flows. Unmarked flows are cleared.
=> Closes #1960 'Z' removes unmarked flows

mitmproxy/addons/view.py
Changes view._store from dict to OrderedDict
=> Closes #1977

test/mitmproxy/test_server.py
#1983 wasn't reliably enough...
=> fix flaky test

examples/complex/har_dump.py, mitmproxy/net/http/encoding.py, test/mitmproxy/net/http/test_encoding.py
Handled the case of empty string
=> Fixes #1978

mitmproxy/proxy/protocol/http.py, test/mitmproxy/test_server.py
This is a fix for the issue described in https://discourse.mitmproxy.org/t/change-upstream-proxy-for-https-flow/347.
=> Fix change_upstream_proxy_server

mitmproxy/addons/script.py, test/mitmproxy/addons/test_script.py
https://github.com/mitmproxy/mitmproxy/pull/1911 needed love.
Should I change the docs as well?
First line in [this](https://github.com/mitmproxy/mitmproxy/blob/master/docs/scripting/overview.rst#developing-scripts) should be more clear, right?
=> Closes #1828 script reloads on py file changes

docs/index.rst, docs/transparent/openbsd.rst, docs/transparent/osx.rst, mitmproxy/platform/__init__.py, mitmproxy/platform/openbsd.py
Add transparent proxy support for OpenBSD with pf divert-to.
=> Add transparent proxy support for OpenBSD

web/src/js/components/Footer.jsx
Sorry it's my first PR here. Didn't know the rules. I hope it's mergeable this time.
=> added version info to web footer --clean

pathod/pathoc.py
Using a function intended only for tests in active live code is ugly.
However, this whole portion of pathoc could benefit from some further improvements.
=> remove treq from pathoc

mitmproxy/addons/proxyauth.py, mitmproxy/http.py, test/mitmproxy/addons/test_proxyauth.py
This PR fixes #1722 and #1734, and hopefully #2019 as well. 
@laurmurclar, can you check if that works for you?
=> Improve ProxyAuth

examples/simple/custom_contentview.py, mitmproxy/contentviews/__init__.py, mitmproxy/contentviews/protobuf.py, setup.cfg, setup.py, test/mitmproxy/contentviews/test_protobuf.py
This PR does not really solve #2021, but at least fixes it to a state that it's working again, and has proper tests as well.
=> protobuf: coverage++

mitmproxy/net/check.py, test/mitmproxy/net/test_check.py
Fixes #1938 
There's another problem though which causes ProtocolException. I'll fix that and force push in this PR only :slightly_smiling_face:
=> Absolute IPv6 addresses supported

mitmproxy/tools/console/flowlist.py
Fixes #2102 change `o.focus_follow` to `o.console_focus_follow`
=> Fixes #2102

web/src/js/filt/filt.js, web/src/js/filt/filt.peg
=> web: Add websocket filter

examples/complex/har_dump.py
this fixes the issue described in https://github.com/mitmproxy/mitmproxy/issues/2119#issuecomment-285067292
=> fix tcp.Address leftovers

docs/install.rst
My main VM happily runs on Tumbleweed for a while now, so I can maintain this.
=> Add install docs for openSUSE

mitmproxy/flow.py, mitmproxy/proxy/protocol/websocket.py, mitmproxy/stateobject.py, mitmproxy/test/tflow.py, mitmproxy/websocket.py, test/mitmproxy/test_stateobject.py, test/mitmproxy/test_websocket.py
=> make websocket flows serializable

mitmproxy/test/tutils.py, test/mitmproxy/addons/test_clientplayback.py, test/mitmproxy/addons/test_replace.py, test/mitmproxy/addons/test_script.py, test/mitmproxy/addons/test_serverplayback.py, test/mitmproxy/addons/test_streamfile.py, test/mitmproxy/net/test_tcp.py, test/mitmproxy/test_certs.py, test/mitmproxy/test_examples.py, test/mitmproxy/test_optmanager.py, test/mitmproxy/tools/test_dump.py, test/pathod/language/test_base.py, test/pathod/language/test_generators.py
=> nuke tutils.tmpdir, use pytest tmpdir

setup.py
=> bump cryptography

web/src/js/__tests__/ducks/ui/flowSpec.js
Now `ducks/ui/flow.js` has 100% coverage tests.
=> [web] Reach 100% coverage for ducks/ui/flow.js

mitmproxy/options.py, mitmproxy/optmanager.py, mitmproxy/proxy/protocol/tls.py, mitmproxy/tools/console/grideditor/base.py, mitmproxy/tools/console/grideditor/editors.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/options.py, mitmproxy/tools/console/overlay.py, mitmproxy/tools/console/signals.py, mitmproxy/tools/console/statusbar.py, mitmproxy/utils/typecheck.py, test/mitmproxy/test_optmanager.py
Heavily WIP, here for comments and CI.
=> Console options editor

mitmproxy/addons/dumper.py, mitmproxy/addons/streamfile.py, mitmproxy/addons/view.py, mitmproxy/options.py, mitmproxy/optmanager.py, mitmproxy/tools/cmdline.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/flowview.py, mitmproxy/tools/console/grideditor/editors.py, mitmproxy/tools/console/options.py, mitmproxy/tools/console/statusbar.py, mitmproxy/tools/main.py, mitmproxy/utils/sliding_window.py, test/mitmproxy/addons/test_dumper.py, test/mitmproxy/addons/test_streamfile.py, test/mitmproxy/addons/test_view.py, test/mitmproxy/test_optmanager.py, test/mitmproxy/tools/test_dump.py
- Resolve filter/filtstr options ambiguity
- Fix some console options bugs
- Properly show choices for content views and console order specs
=> Tighten some options-related functionality

mitmproxy/optmanager.py, mitmproxy/tools/console/options.py, test/mitmproxy/test_optmanager.py
Also make options parsing more robust against corrupt data.
=> console options: load and save options to and from file

mitmproxy/addons/termstatus.py, mitmproxy/proxy/server.py, mitmproxy/tools/console/flowdetailview.py, mitmproxy/utils/human.py, test/mitmproxy/utils/test_human.py
Since other PR was closed by the author
Should I make changes in flowdetailview as well?
=> Fixes IP address formatting #2109

.gitignore, mitmproxy/contentviews/image/image_parser.py, mitmproxy/contrib/kaitaistruct/exif.py, mitmproxy/contrib/kaitaistruct/exif_be.py, mitmproxy/contrib/kaitaistruct/exif_le.py, mitmproxy/contrib/kaitaistruct/gif.py, mitmproxy/contrib/kaitaistruct/jpeg.py, mitmproxy/contrib/kaitaistruct/make.sh, mitmproxy/contrib/kaitaistruct/png.py, setup.py
=> update kaitai and recompile formats

mitmproxy/addons/dumper.py, mitmproxy/tools/console/flowdetailview.py
Belongs to https://github.com/mitmproxy/mitmproxy/pull/2234 but I saw this just now.
Fixes the crash when can't resolve address
=> Fixed formatting in mitmdump

mitmproxy/addonmanager.py, mitmproxy/addons/core.py, mitmproxy/command.py, mitmproxy/optmanager.py, mitmproxy/tools/cmdline.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/keymap.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/window.py, test/mitmproxy/test_addonmanager.py, test/mitmproxy/test_command.py, test/mitmproxy/test_optmanager.py
Use this for our built-ins and the console commands.
=> Add a command.command decorator

mitmproxy/addons/core.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/master.py, test/mitmproxy/addons/test_core.py
Plus matching binding in flowlist.
=> command: flow.revert

mitmproxy/addons/script.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/master.py, test/mitmproxy/addons/test_script.py
Plus the flowlist binding adjustments.
=> command: script.run

examples/simple/add_header.py, examples/simple/add_header_class.py, examples/simple/custom_contentview.py, examples/simple/filter_flows.py, examples/simple/io_read_dumpfile.py, examples/simple/io_write_dumpfile.py, examples/simple/modify_body_inject_iframe.py, examples/simple/modify_form.py, examples/simple/modify_querystring.py, examples/simple/redirect_requests.py, examples/simple/send_reply_from_proxy.py, examples/simple/upsidedownternet.py, examples/simple/wsgi_flask_app.py
Extended mypy checking to `example/simple`.
I am new to mypy , thats why worked on small part once get reviewed and get most of it , I will be updating whole` example/ `.
REF : #2194
=> Extend mypy example/simple (#2194)

mitmproxy/addons/view.py, mitmproxy/master.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/master.py, test/mitmproxy/addons/test_view.py, test/mitmproxy/console/test_flowlist.py, test/mitmproxy/test_flow.py
And use these commands to remove the last hard-coded keybindings from flow
list. This means the flow list is now 100% command-driven, which is very
exciting.
=> commands: view.order.options, view.marked.toggle, view.create

mitmproxy/tools/web/static/app.css, mitmproxy/tools/web/static/app.js, mitmproxy/tools/web/static/vendor.js, web/src/css/header.less, web/src/js/__tests__/ducks/connectionSpec.js, web/src/js/backends/websocket.js, web/src/js/components/Header.jsx, web/src/js/components/Header/ConnectionIndicator.jsx, web/src/js/components/common/DocsLink.jsx, web/src/js/ducks/connection.js, web/src/js/ducks/index.js, web/src/js/ducks/ui/flow.js, web/src/js/ducks/ui/header.js, web/yarn.lock
This PR adds a connection indicator to mitmweb in the top right corner:
The next logical step is to automatically reconnect etc, but this is a vast improvement over the current state already.
TODO:
=> [web] add connection indicator [WIP]

mitmproxy/addonmanager.py, mitmproxy/addons/core.py, mitmproxy/addons/view.py, mitmproxy/tools/console/commands.py, mitmproxy/tools/console/flowdetailview.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/flowview.py, mitmproxy/tools/console/grideditor/base.py, mitmproxy/tools/console/grideditor/editors.py, mitmproxy/tools/console/help.py, mitmproxy/tools/console/keymap.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/options.py, mitmproxy/tools/console/overlay.py, mitmproxy/tools/console/searchable.py, mitmproxy/tools/console/signals.py, mitmproxy/tools/console/statusbar.py, mitmproxy/tools/console/tabs.py, mitmproxy/tools/console/window.py, mitmproxy/tools/main.py, test/mitmproxy/addons/test_core.py, test/mitmproxy/addons/test_view.py, test/mitmproxy/tools/console/test_keymap.py
Events, new window management structure, many more keybindings.
=> Console revamp

mitmproxy/addons/core.py, mitmproxy/tools/console/flowview.py, mitmproxy/tools/console/master.py, test/mitmproxy/addons/test_core.py
Use this to bind "z" in flowview.
=> commands: flow.encode, flow.decode, flow.encode.toggle

examples/simple/custom_contentview.py, examples/simple/io_read_dumpfile.py, examples/simple/io_write_dumpfile.py, pathod/language/actions.py, pathod/language/base.py, pathod/language/http.py, pathod/language/http2.py, pathod/language/message.py, pathod/language/websockets.py, pathod/pathod.py, pathod/test.py, pathod/utils.py, tox.ini
This PR Extend Mypy checking to `/pathod` folder , fixed some bugs from previous` example/simple `and add these mypy checking to `tox`.
REF #2194 , #2221
=> Mypy Checking to pathod

mitmproxy/addons/core.py, mitmproxy/addons/view.py, mitmproxy/tools/console/commands.py, mitmproxy/tools/console/common.py, mitmproxy/tools/console/flowdetailview.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/flowview.py, mitmproxy/tools/console/grideditor/base.py, mitmproxy/tools/console/help.py, mitmproxy/tools/console/keymap.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/options.py, mitmproxy/tools/console/overlay.py, mitmproxy/tools/console/searchable.py, mitmproxy/tools/console/select.py, mitmproxy/tools/console/statusbar.py, mitmproxy/tools/console/tabs.py, mitmproxy/tools/console/window.py, test/mitmproxy/addons/test_core.py, test/mitmproxy/addons/test_script.py, test/mitmproxy/addons/test_view.py, test/mitmproxy/tools/console/test_help.py
- Action bar now correctly gets the palette background
- Viewing connection details for a killed flow no longer crashes
- Editing options with selections no longer crashes
=> console: various bugfixes

mitmproxy/io/compat.py, mitmproxy/net/http/url.py, setup.cfg, test/mitmproxy/data/dumpfile-018, test/mitmproxy/net/http/test_cookies.py, test/mitmproxy/net/http/test_message.py
Test coverage improved for following files:
* https://codecov.io/gh/mitmproxy/mitmproxy/src/master/mitmproxy/net/http/cookies.py
* https://codecov.io/gh/mitmproxy/mitmproxy/src/master/mitmproxy/net/http/message.py
* https://codecov.io/gh/mitmproxy/mitmproxy/src/master/mitmproxy/net/http/url.py
* https://codecov.io/gh/mitmproxy/mitmproxy/src/master/mitmproxy/io/compat.py
=> Improve Test coverage

setup.cfg, test/mitmproxy/contentviews/test_api.py, test/mitmproxy/contentviews/test_xml_html.py, test/mitmproxy/contentviews/test_xml_html_data/test-formatted.html, test/mitmproxy/contentviews/test_xml_html_data/test.html, test/mitmproxy/test_controller.py
Bumped coverage to 100% in following files:
* https://codecov.io/gh/mitmproxy/mitmproxy/src/master/mitmproxy/contentviews/__init__.py
* https://codecov.io/gh/mitmproxy/mitmproxy/src/master/mitmproxy/contentviews/xml_html.py
* https://codecov.io/gh/mitmproxy/mitmproxy/src/master/mitmproxy/controller.py
=> Increased test coverage

.travis.yml, mitmproxy/net/tcp.py, setup.cfg, test/full_coverage_plugin.py, test/mitmproxy/net/test_tcp.py, tox.ini
This PR increases net.tcp.py coverage to 100% making coverage of mitmproxy/net/ to 100%
=> Increase net.tcp.py coverage

mitmproxy/options.py
Added the level definition that can be used
fixes #2139
=> improve flow_detail help text

web/src/js/__tests__/components/FlowTable/FlowRowSpec.js, web/src/js/__tests__/components/FlowTable/FlowTableHeadSpec.js, web/src/js/__tests__/components/FlowTable/__snapshots__/FlowRowSpec.js.snap, web/src/js/__tests__/components/FlowTable/__snapshots__/FlowTableHeadSpec.js.snap, web/src/js/components/FlowTable/FlowTableHead.jsx
=> [web] Add tests for js/components/FlowTable

mitmproxy/master.py, setup.cfg, test/mitmproxy/test_flow.py, test/mitmproxy/test_http.py
Increases coverage for:
* https://codecov.io/gh/mitmproxy/mitmproxy/src/master/mitmproxy/flow.py
* https://codecov.io/gh/mitmproxy/mitmproxy/src/master/mitmproxy/master.py
=> Test coverage increase

mitmproxy/tools/console/eventlog.py, mitmproxy/tools/console/flowlist.py
Fixes issue of crash on clearing event log and using mouse to view flow details.
fixes #2377
fixes #2323
=> Fixes #2377 #2323

mitmproxy/contrib/kaitaistruct/png.py
ref: https://github.com/kaitai-io/kaitai_struct_formats/pull/43/files
=> Update png.py. Stop reading after IEND

mitmproxy/options.py, mitmproxy/tools/cmdline.py, mitmproxy/tools/console/commands.py, mitmproxy/tools/console/eventlog.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/flowview.py, mitmproxy/tools/console/grideditor/editors.py, mitmproxy/tools/console/help.py, mitmproxy/tools/console/options.py, mitmproxy/tools/console/window.py
Controlled with the new console_layout_headers option
=> console: layout pane headers

mitmproxy/tools/console/commands.py, mitmproxy/tools/console/eventlog.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/flowview.py, mitmproxy/tools/console/grideditor/base.py, mitmproxy/tools/console/grideditor/col_bytes.py, mitmproxy/tools/console/grideditor/editors.py, mitmproxy/tools/console/help.py, mitmproxy/tools/console/layoutwidget.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/options.py, mitmproxy/tools/console/overlay.py, mitmproxy/tools/console/window.py
Regularise grideditors, pull core functionality out into commands and keybindings.
=> console: grideditor improvements

mitmproxy/tools/console/defaultkeys.py, mitmproxy/tools/console/help.py, mitmproxy/tools/console/keymap.py, mitmproxy/tools/console/master.py
Add a help field to key bindings, use that in contextual help display.
=> console: Key binding help

mitmproxy/certs.py
=> Remove private key from PKCS12 file

mitmproxy/websocket.py
Fixes ip address formatting in websocket messages
=> Fix ip formatting in websocket messages

mitmproxy/addons/onboardingapp/templates/index.html
THE implies there is only one. THE Eiffel tower.
YOUR implies everyone has a different one. YOUR teeth.
=> Slight wording change

mitmproxy/addons/dumper.py
=> Few ip formatting fixes

mitmproxy/test/tflow.py, test/mitmproxy/addons/test_cut.py, test/mitmproxy/test_connections.py, test/mitmproxy/test_flowfilter.py, test/mitmproxy/tservers.py, web/src/js/__tests__/components/FlowView/__snapshots__/DetailsSpec.js.snap, web/src/js/__tests__/ducks/_tflow.js
Changed address value in `tclient_conn` to a valid IP address
ref: https://github.com/mitmproxy/mitmproxy/pull/2436#issuecomment-317660902
=> Fixed addon error in test suite

mitmproxy/addons/termlog.py, mitmproxy/options.py, mitmproxy/tools/console/eventlog.py, mitmproxy/tools/console/master.py, mitmproxy/tools/main.py, test/mitmproxy/addons/test_dumper.py, test/mitmproxy/addons/test_termlog.py, test/mitmproxy/tools/console/test_master.py, test/mitmproxy/tools/test_dump.py
=> Fix #2448: Improve flow_detail and verbosity options

mitmproxy/addons/intercept.py, mitmproxy/options.py, mitmproxy/tools/console/consoleaddons.py, mitmproxy/tools/console/defaultkeys.py, mitmproxy/tools/console/statusbar.py, mitmproxy/tools/web/app.py, test/mitmproxy/addons/test_intercept.py
Added feature to allow toggling of traffic interception while persisting the intercept filters.
=> Add intercept toggle feature.

mitmproxy/log.py, mitmproxy/proxy/protocol2/http.py, mitmproxy/proxy/protocol2/test/test_websocket.py, mitmproxy/proxy/protocol2/websocket.py, requirements.txt
=> [sans-io] WebSocket layer

test/mitmproxy/addons/test_proxyauth.py
=> improve proxyauth tests

mitmproxy/certs.py, setup.py
=> bump pyasn

mitmproxy/tools/main.py, mitmproxy/utils/arg_check.py, test/mitmproxy/utils/test_arg_check.py
More checks can be added to this.
Almost all the options which will be removed can be set using `--set option_name=value` Maybe add a check for that?
ref: #2498
=> Improve options UX

mitmproxy/io/compat.py
=> Fixes #2495

examples/simple/custom_contentview.py
* Changing `load` to `start`.
* Removing the old copy of the contentView (since `done` is only called on shutdown).
=> Fixing incorrect custom_contentview.py example.

docs/certinstall.rst
Certificate pinning (HTTP Public Key Pinning) is better described on Wikipedia
=> docs-certinstall: Certificate pinning update link

examples/complex/xss_scanner.py, test/examples/test_xss_scanner.py
As @EdOverflow suggested, added scanning for CSS injection and iframe injection via unclaimed URLs.
=> Added scanning for CSS injection and iframe injection to XSS scanner

mitmproxy/tools/console/common.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/window.py
| before | after |
|-----|------|
| ![image](https://user-images.githubusercontent.com/1019198/31912588-a6e18d22-b844-11e7-9b95-f2dc282af196.png) | ![image](https://user-images.githubusercontent.com/1019198/31912571-9b25d362-b844-11e7-8041-10db188e5de5.png) |
=> Fix urwid display on WSL

mitmproxy/addons/save.py, mitmproxy/contrib/wsproto/__init__.py, mitmproxy/contrib/wsproto/extensions.py, mitmproxy/contrib/wsproto/frame_protocol.py, mitmproxy/flowfilter.py, mitmproxy/master.py, mitmproxy/proxy/protocol/http.py, mitmproxy/proxy/protocol/websocket.py, mitmproxy/test/tflow.py, mitmproxy/websocket.py, setup.cfg, test/mitmproxy/addons/test_save.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_flowfilter.py
websocket supports domain and url filters now
fixes #2640
=> improve websocket dumps

mitmproxy/tools/console/consoleaddons.py
@cortesi: Not sure if I am doing this as intended - see https://github.com/mitmproxy/mitmproxy/compare/master...mhils:issue-2694?expand=1#diff-14fc04d5ac58857f7ce7f02e8ff05b50R375.
Is there a particular reason why this command is `console.edit.focus` and not `console.edit @focus`?
=> Re-add body editing

mitmproxy/command.py, mitmproxy/tools/console/consoleaddons.py, mitmproxy/tools/console/defaultkeys.py, mitmproxy/types.py, mitmproxy/utils/typecheck.py, test/mitmproxy/test_command.py, test/mitmproxy/test_types.py, test/mitmproxy/utils/test_typecheck.py
=> types: add validation, use it in commands

mitmproxy/command.py, mitmproxy/tools/console/commander/commander.py, mitmproxy/types.py, test/mitmproxy/test_command.py, test/mitmproxy/test_types.py, test/mitmproxy/tools/console/test_commander.py
Step 1 of the fancification of commander.
=>  commander: highlight commands

mitmproxy/command.py, mitmproxy/tools/console/commander/commander.py, mitmproxy/tools/console/palettes.py, mitmproxy/types.py, test/mitmproxy/test_command.py, test/mitmproxy/test_types.py
- Add palette entries specific to commander
- Highlight errors
- Introduce an Unknown type to keep track of extra unknown arguments to
commands
=> commander: palette entries, highlight errors

mitmproxy/addons/cut.py, mitmproxy/tools/console/commandexecutor.py, mitmproxy/tools/console/commands.py, mitmproxy/tools/console/consoleaddons.py, mitmproxy/tools/console/keymap.py, mitmproxy/tools/console/options.py, mitmproxy/tools/console/overlay.py, test/mitmproxy/addons/test_cut.py
=> various command-related fixes

docs/scripting/api.rst, docs/scripting/events.rst, mitmproxy/proxy/protocol/websocket.py, mitmproxy/websocket.py, test/mitmproxy/test_websocket.py
=> websocket: docs++ and kill messages

mitmproxy/addonmanager.py, mitmproxy/controller.py, mitmproxy/flow.py, test/mitmproxy/proxy/protocol/test_websocket.py
=> fix flow.kill

mitmproxy/tools/console/window.py
- Clicking on tab head focuses a tab now. #2676 fixed.
- We can't click on different stuff in not focused tab by pressing left button of mouse now. #2738 fixed.
=> Bugs with console fixed.

mitmproxy/contrib/kaitaistruct/gif.py
=> Update GIF parser

mitmproxy/connections.py, mitmproxy/io/compat.py, mitmproxy/test/tflow.py, mitmproxy/tools/web/app.py, mitmproxy/version.py, test/mitmproxy/net/test_tls.py, test/mitmproxy/proxy/test_server.py
=> Store ClientHello extensions with client connection

mitmproxy/contentviews/base.py, test/mitmproxy/contentviews/test_base.py, test/mitmproxy/contentviews/test_urlencoded.py
=> Fixing the crashing issue

examples/complex/change_upstream_proxy.py, examples/complex/har_dump.py, examples/complex/sslstrip.py, examples/complex/xss_scanner.py, test/examples/test_xss_scanner.py, tox.ini
=> Extend mypy checking, fix #2194

web/src/js/components/FlowTable/FlowColumns.jsx
see https://discourse.mitmproxy.org/t/mitmweb-details-tab-timing/848/3
=> [web] fix timing display for keepalive connections

mitmproxy/net/http/cookies.py, test/mitmproxy/net/http/test_cookies.py, test/mitmproxy/net/http/test_response.py
Fixes #2827 ,
The earlier solution I implemented was bad. I think this will do a decent job.  
Thankyou so much @kajojify for helping out on the flow of the code :)
=>  Handling empty key with value for cookies, fix #2827 

mitmproxy/addons/core.py, mitmproxy/tools/console/consoleaddons.py
When pressing `V`, flow wasn't reverted to the previous state after editing some part of it and after encoding/decoding of a flow body.
It is fixed.
=> Fix reverting of a flow

mitmproxy/addons/serverplayback.py, mitmproxy/options.py, mitmproxy/tools/cmdline.py, mitmproxy/tools/console/statusbar.py, test/mitmproxy/addons/test_serverplayback.py, test/mitmproxy/tools/console/test_master.py, test/mitmproxy/tools/console/test_statusbar.py
All other server playback options have this form.
=> option refresh_server_playback -> server_replay_refresh

CHANGELOG
=> Update changelog for 3.0

mitmproxy/tools/console/master.py
We were stepping on this Urwid bug:
https://github.com/urwid/urwid/issues/285
The guys from pazz/alot found a fix, which I cribbed:
https://github.com/pazz/alot/pull/1204
Fix #2901
=> Fix loss of keyboard control after spawn

mitmproxy/version.py
=> Bump version

docs/src/content/overview-tools.md
Replaced "You should thin* of the mitmproxy" to "You should think* of the mitmproxy"
=> Spelling corrected for think*

docs/src/content/concepts-modes.md
This fixes #2913 :)
The pictures also needs to be changed, is there any source of these images through which it can directly change? Otherwise I will go ahead and photoshop them.
=> Updating docs

mitmproxy/addons/dumper.py, mitmproxy/addons/intercept.py, mitmproxy/addons/proxyauth.py, mitmproxy/options.py, mitmproxy/tools/console/consoleaddons.py, mitmproxy/tools/console/defaultkeys.py, mitmproxy/tools/console/statusbar.py, test/mitmproxy/addons/test_allowremote.py, test/mitmproxy/addons/test_dumper.py, test/mitmproxy/addons/test_intercept.py, test/mitmproxy/addons/test_proxyauth.py, test/mitmproxy/tools/console/test_master.py, test/mitmproxy/tools/console/test_statusbar.py, test/mitmproxy/tools/test_dump.py
These all need a bit more than just shifting the addon, due to various factors.
=> Start moving more complicated options over to /addons

setup.py
=> Remove h11 from dependencies and move requests to dev dependencies

mitmproxy/addons/dumper.py, mitmproxy/addons/view.py, mitmproxy/options.py, test/mitmproxy/addons/test_dumper.py, test/mitmproxy/tools/test_dump.py
These don't even do the same thing.
=> Split dumper_filter off from view_filter

mitmproxy/proxy/config.py
=> Fix display inconsistency for certstore path

docs/src/themes/mitmproxydocs/static/css/style.css
ref https://github.com/mitmproxy/mitmproxy/issues/2895#issuecomment-370141758
=> render sidebar without height limit

mitmproxy/net/http/request.py, test/mitmproxy/net/http/test_request.py
=> Fix crashing when editing form with random data, fix #2794

README.rst
Hi,
The installation instructions linked back to old docs website.
I have updated the same
=> updating README according to recent doc updates

mitmproxy/command.py, test/mitmproxy/test_command.py
Hi,
I still couldn't figure out why @mhils method was not working but I will not give up on that and come to a conclusion some day.
This provides the test for #2850.
closes #2850
=> Test for #2850

mitmproxy/tools/console/statusbar.py
=> Removing the erroneously highlighted keybinding

mitmproxy/tools/console/statusbar.py
Remove erroneously highlighted keybinding for replacements
- Fixes  2953
=> Remove Highlight from status bar

setup.py, test/mitmproxy/addons/test_onboarding.py
https://github.com/tornadoweb/tornado/issues/2183#issuecomment-371001254
=> fix Tornado 5.0 event loop

.travis.yml, docs/src/content/overview-installation.md, mitmproxy/net/tcp.py, mitmproxy/tools/main.py, mitmproxy/utils/typecheck.py, release/README.md, setup.py, test/filename_matching.py, test/individual_coverage.py, test/mitmproxy/utils/test_typecheck.py, tox.ini
=> Python 3.5 is dead -- long live Python 3.6!

mitmproxy/addons/export.py, test/mitmproxy/addons/test_export.py
I thought having an option to export a request as [httpie](https://github.com/jakubroztocil/httpie/) command could be useful for many users that prefer httpie to curl.
I think i added all the needed tests but let me know if i have missed anything.
=> added option to export request as httpie command

examples/simple/README.md
Thanks @q2dg for reporting this!
ref 3b134df77f6d9e2166d722a675dfffb803ece197
=> fix example filename

mitmproxy/net/tcp.py, mitmproxy/tools/web/app.py, mitmproxy/tools/web/master.py
- Move to the new run loop wrapper
- This revealed an issue that exposed an issue that revealed an issue: we still try to handle EINTR, but Python now does that for you
- Just disable mitmweb config saving for now.
=> A grab-bag of mitmweb-related fixes

mitmproxy/tools/web/app.py
=> Fix asyncio.call_soon -> asyncio.ensure_future

mitmproxy/addons/cut.py, mitmproxy/addons/view.py, mitmproxy/types.py, test/mitmproxy/test_types.py
While I am sorting out in #3074 I decide to try to warm up :grinning: 
The list of all commands, which work with path https://github.com/mitmproxy/mitmproxy/issues/3002#issuecomment-374228453
=> Fix #3002. Auto-expanding for tilda.

examples/addons/events.py, mitmproxy/eventsequence.py, mitmproxy/master.py, mitmproxy/script/concurrent.py, mitmproxy/tools/console/master.py, test/mitmproxy/addons/test_script.py, test/mitmproxy/test_addonmanager.py, test/mitmproxy/tservers.py
Mitmproxy: the tickless wonder.
=> Remove the tick event

examples/complex/tcp_message.py
fixes #3113
@mhils: does this look right?
=> fix tcp example

examples/complex/websocket_inject_message.py, mitmproxy/proxy/protocol/websocket.py, mitmproxy/websocket.py, test/mitmproxy/proxy/protocol/test_websocket.py, test/mitmproxy/test_websocket.py
=> websocket: inject messages via flow

mitmproxy/optmanager.py, mitmproxy/tools/main.py, test/mitmproxy/test_optmanager.py
=> Use deferral mechanism for cfg file options

mitmproxy/master.py, mitmproxy/tools/main.py, test/mitmproxy/proxy/test_server.py
This fixes #3133. The current shutdown code is quite ugly really, we need to clean up here once the proxy server is asyncio-based as well.
=> Fix shutdown on Windows

mitmproxy/platform/windows.py
This fixes #3080. 
@spozdnyakov @Jazzelhawk: You both seem to be on Windows as well - could you please verify that this fixes all your issues? 😃
=> Add support for IPv6 transparent mode on Windows

docker/DockerfileARMv7, release/cibuild.py
Adding in a build step to create and deliver an image specifically for the Raspberry Pi 3.
=> Adding Docker build for Raspberry Pi 3 (ARMv7 Processor Family)

.travis.yml, mitmproxy/tools/_main.py, mitmproxy/tools/main.py, tox.ini
This should be included and released in a 4.0.2-bugfix release.
=> fix syntax-error on older python interpreters

mitmproxy/proxy2/layers/websocket.py, requirements.txt, test/mitmproxy/proxy2/layers/test_websocket.py, test/mitmproxy/proxy2/tutils.py
import the existing WS implementation and adapt it for sans-io + basic testing.
=> [sans-io] refactor websockets

CHANGELOG, release/README.md
We no longer care about annotated tags.
=> CHANGELOG, release/README updates

mitmproxy/tools/console/options.py
=> Pass option, not option name to parse_setval

examples/complex/xss_scanner.py, test/examples/test_xss_scanner.py
Two commits:
1. Fix the test failure (small)
2. Cleanup and refacto a little bit the test (bigger)
=> Fix XSS scanner failure in test_xss_scanner.py

examples/complex/dns_spoofing.py
I tested this locally to verify this change is correct.
=> Corrected keep_host_header usage option

mitmproxy/addons/dumper.py, test/mitmproxy/addons/test_dumper.py
=> Display errors on sys.stderr

mitmproxy/addons/clientplayback.py
This is my first PR here,excited :)
fixes #3307
=> client-replay-fix

mitmproxy/net/http/message.py, test/mitmproxy/net/http/test_message.py
=> Charset in meta tags

examples/addons/commands-paths.py, mitmproxy/addons/session.py, mitmproxy/contrib/wbxml/ASCommandResponse.py, test/bench/benchmark.py, test/mitmproxy/addons/test_session.py
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>
=> Fix ResourceWarning: unclosed file, prevent resource leaks

mitmproxy/proxy/protocol/websocket.py, setup.py
A proper update for wsproto 0.13
=> Fix: update to wsproto 0.13 for real this time

docs/src/content/addons-scripting.md
=> Fix markdown typo on addons-scripting.md

mitmproxy/contrib/kaitaistruct/exif_be.py, mitmproxy/contrib/kaitaistruct/exif_le.py
Fixed the exif .ksy files in the kaitai repo with https://github.com/kaitai-io/kaitai_struct_formats/pull/124 . Compiled the .ksy to python files and updated them in the contrib folder. Should fix #3360 and avoids error in mitmproxy 5.0.0 -> no fallback to raw content in view mode.
=> Updated exif kaitai files  

mitmproxy/net/websockets/masker.py
=> websockets: replace masker with more optimized one

mitmproxy/addonmanager.py
=> fix addon deconstruction

docs/src/content/howto-transparent.md
I struggled with getting this working and found a few posts around the internet from people with the same issue. The macOS section talks about this so I've just "ported" that to the linux world.
Thanks for the fantastic tool BTW :tada:
=> Transparent proxy on Linux for local originating traffic

mitmproxy/options.py, mitmproxy/proxy/config.py, mitmproxy/proxy/root_context.py, mitmproxy/tools/cmdline.py, mitmproxy/tools/console/statusbar.py, test/mitmproxy/proxy/test_config.py, test/mitmproxy/proxy/test_server.py
This PR adds the `--allow_hosts` option, opposite to the `--ignore-hosts` option.
=> Add --allow_hosts option

mitmproxy/addons/view.py
=> Fixes crash upon view.focus.[next|prev] - #3694

mitmproxy/tools/_main.py
cf. title
as suggested in #3639
=> adding config.yml as an allowed config filename

mitmproxy/tools/console/consoleaddons.py, mitmproxy/tools/console/master.py
fix for #3165 
Should this be added in docs?
=> external-viewer-fix

mitmproxy/proxy/protocol/http.py
1. run mitmproxy: `mitmproxy --listen-port 8080` 
then run one of commands of following:
`echo "CONNECT bad request HTTP/1.1\r\n"|nc localhost 8080`
`echo "random\n"|nc localhost 8080`
2. or run mitmproxy: `mitmproxy --mode transparent --listen-port 8080` 
then run command:
`echo 'GET http://localhost:60000/test HTTP/1.1\r\nHost: localhost:60000\r\n\r\n'|nc localhost 8080`
3. got duplicate error response: 
```
HTTP/1.1 400 Bad Request
Server: mitmproxy 5.0.0.dev
Connection: close
Content-Length: 302
Content-Type: text/html
<html>
<head>
<title>400 Bad Request</title>
</head>
<body>
<h1>400 Bad Request</h1>
<p>HttpSyntaxException(&quot;Bad HTTP request line: b&#x27;CONNECT bad request HTTP/1.1&#x27;&quot;,)</p>
</body>
</html>HTTP/1.1 502 Bad Gateway
Server: mitmproxy 5.0.0.dev
Connection: …
```
=> fix duplicate error response

mitmproxy/net/tcp.py
Previously, the proxy would attempt to bind to an IPv6 + IPv4 enabled socket.
On failure, it would try to bind to an IPv4 only socket. If that failed, the
proxy would fail to start. This update makes it so that the proxy also tries
to bind to an IPv6-only socket, which is necessary in environments where IPv4
is disabled.
In short, the proxy will try binding in the following order, only moving
to the next step when binding fails:
IPv6 + IPv4 -> IPv4 only -> IPv6 only -> proxy fails to start.
Closes #3695
=> Add support for IPv6-only environments

mitmproxy/tools/console/common.py
Fixes #3704
Added a column for mark and replay on the new table ui
=> Added Replay to new table UI

mitmproxy/proxy/protocol/tls.py
=> close the client connection if TLS ClientHello parsing fails

mitmproxy/contentviews/__init__.py
This should greatly increase the flexibility of custom ContentViews
=> Add message to ContentView metadata

mitmproxy/addons/dumper.py, mitmproxy/contentviews/__init__.py, mitmproxy/tools/console/flowview.py, mitmproxy/tools/web/app.py, mitmproxy/tools/web/static_viewer.py, test/mitmproxy/addons/test_dumper.py, test/mitmproxy/contentviews/test_api.py
The long-awaited sequel to #3738, adds the flow to the ContentView's metadata.
=> Add flow to ContentView metadata

setup.py
=> bump urwid

mitmproxy/tools/console/common.py
=> fix: ValueError: math domain error" in table mode #3778

examples/simple/wsgi_flask_app.py
Correcting example as per discussion in issue #3786
=> Update WSGI example

mitmproxy/optmanager.py
I believe this would fix the issue #3797
=> Fix for issue 3797

mitmproxy/command.py
=> Improve command detection heuristics

release/hooks/hook-pkg_resources.py
See https://github.com/pypa/setuptools/issues/1963 for details.
=> Fix binary builds

mitmproxy/net/server_spec.py, mitmproxy/proxy/protocol/http.py
Nothing exciting here, just syncing changes to the main tree made during sans-io refactorings.
=> Minor code style improvements, sync sans-io changes

mitmproxy/addons/browser.py, mitmproxy/tools/web/master.py, mitmproxy/tools/web/webaddons.py
=> finish FIXME: move open_browser() to addon/browser

docs/src/content/tools-mitmdump.md
Script path in document `tools-mitmdump` seems wrong.
=> fix document error

mitmproxy/net/http/headers.py, test/mitmproxy/net/http/test_headers.py
=> Fix for issue 3833

mitmproxy/addons/script.py, test/mitmproxy/addons/test_script.py, test/mitmproxy/data/addonscripts/configure.py
=> Fix:Addon OptionsError is neither logged, nor does it stop mitmproxy

.github/workflows/main.yml, pathod/language/actions.py, release/cibuild.py, setup.py
=> Update mypy and pin version

web/README.md
Bug: https://github.com/mitmproxy/mitmproxy/issues/3888
=> Clarify developer documentation for mitmweb

mitmproxy/tools/cmdline.py, mitmproxy/tools/web/master.py, mitmproxy/tools/web/webaddons.py, release/docker/README.md
Bug: https://github.com/mitmproxy/mitmproxy/issues/3891
=> Rename web-iface to web-host

docs/src/content/tools-mitmdump.md
=> docs update

mitmproxy/tools/_main.py
=> Add Filter message to mitmdump

mitmproxy/contentviews/json.py, mitmproxy/tools/console/palettes.py, test/mitmproxy/contentviews/test_json.py
=> colorize json

mitmproxy/command_lexer.py, test/mitmproxy/test_command_lexer.py
=> console error

docs/src/config.toml
As per the comments on 
https://github.com/mitmproxy/mitmproxy/issues/3946
=> enable flag pygmentsCodefences = true

web/README.md
Bug: https://github.com/mitmproxy/mitmproxy/issues/3925
=> Document mitmweb architecture

mitmproxy/version.py
=> Verify that we're in the correct repository when extracting dev version information

mitmproxy/version.py
=> Replace git cat-file -t with -e and explain the magic ID

mitmproxy/certs.py
=> Certs: mark SAN as critical if no CN is set

docs/src/content/overview-features.md, mitmproxy/addons/__init__.py, mitmproxy/addons/modifybody.py, mitmproxy/addons/modifyheaders.py, mitmproxy/addons/replace.py, mitmproxy/http.py, mitmproxy/net/http/headers.py, mitmproxy/net/http/message.py, mitmproxy/net/http/request.py, mitmproxy/tools/_main.py, mitmproxy/tools/cmdline.py, mitmproxy/tools/console/statusbar.py, mitmproxy/utils/arg_check.py, test/mitmproxy/addons/test_modifybody.py, test/mitmproxy/addons/test_modifyheaders.py, test/mitmproxy/addons/test_replace.py, test/mitmproxy/net/http/test_headers.py, test/mitmproxy/net/http/test_message.py, test/mitmproxy/net/http/test_request.py, test/mitmproxy/test_http.py, test/mitmproxy/tools/console/test_statusbar.py, test/mitmproxy/utils/test_arg_check.py
The new addon only replaces data in the body using `--modify-body`.
refs #3948
=> Replace replacements addon with new modify body addon

mitmproxy/addons/mapremote.py, mitmproxy/addons/modifybody.py, mitmproxy/addons/modifyheaders.py, test/mitmproxy/addons/test_mapremote.py, test/mitmproxy/addons/test_modifybody.py, test/mitmproxy/addons/test_modifyheaders.py
This PR fixes the Windows tests and introduces some minor code-reuse in the modify* and map* addons.
@mplattner: There shouldn't be much controvery here, feel free to take a look and merge if you are happy! 😃
=> Minor addon improvements, fix tests

examples/addons/http-trailers.py, mitmproxy/http.py, mitmproxy/io/compat.py, mitmproxy/net/http/http1/read.py, mitmproxy/net/http/message.py, mitmproxy/net/http/request.py, mitmproxy/net/http/response.py, mitmproxy/proxy/protocol/http.py, mitmproxy/proxy/protocol/http1.py, mitmproxy/proxy/protocol/http2.py, mitmproxy/tools/web/app.py, mitmproxy/version.py, pathod/protocols/http2.py, test/mitmproxy/net/http/test_request.py, test/mitmproxy/net/http/test_response.py, test/mitmproxy/proxy/protocol/test_http2.py
Do not raise exception when TrailersReceived
=> support HTTP2 trailers

CHANGELOG, mitmproxy/tools/web/app.py
I changed the problematic RegEx Pattern that i critized earlier in #4072
=> Secure fix for the DNS Rebind Protection issue from #4072

mitmproxy/tools/console/tabs.py
=> fix console tab error

CHANGELOG, mitmproxy/contentviews/__init__.py, mitmproxy/contentviews/msgpack.py, setup.py, test/mitmproxy/contentviews/test_msgpack.py
This is a msgpack content viewer.
Is this of interest? If so, what kind of tests should I add if at all?
Thanks.
=> Add a msgpack content viewer.

.github/workflows/main.yml, codecov.yml
This is an attempt to 1) fix codecov's premature reporting (probably not going to happen and 2) split coverage for web and python.
=> Use Codecov projects

CHANGELOG, mitmproxy/websocket.py
Fixes https://github.com/mitmproxy/mitmproxy/issues/4131
I have no idea about Python typing, I copied this from StackOverflow like a professional.
=> Updated typing for WebsocketMessage.content

mitmproxy/addons/clientplayback.py, mitmproxy/flow.py, mitmproxy/proxy/protocol/http2.py, mitmproxy/proxy/server.py, web/src/js/__tests__/components/FlowTable/FlowColumnsSpec.js, web/src/js/components/FlowTable/FlowColumns.jsx
This is mostly a preparation for sans-io, where we detect kills using the presence of the error.
=> Standardize killed error message

mitmproxy/addons/intercept.py, test/mitmproxy/addons/test_intercept.py
=> Intercept: don't fail on requests taken by other addons

CHANGELOG, mitmproxy/addons/export.py, test/mitmproxy/addons/test_export.py
=> Update raw export to not remove headers

CHANGELOG, mitmproxy/tools/main.py, setup.py, tox.ini
=> semver bump

mitmproxy/addons/dumper.py, test/individual_coverage.py, test/mitmproxy/addons/test_dumper.py
=> various trailer-related fixes

CHANGELOG.rst, mitmproxy/addons/asgiapp.py, test/mitmproxy/addons/test_asgiapp.py
Fixes the bug described in #4270
=> asgiapp.py: fix query parameters

mitmproxy/net/websocket_utils.py, mitmproxy/proxy/protocol/websocket.py, test/mitmproxy/net/test_websocket_utils.py, test/mitmproxy/proxy/protocol/test_websocket.py
This PR decouples the websocket stack from the pathod library.
This PR introduces additional debug logging for websocket frames and events.
=> websocket: decouple from pathod

CHANGELOG.rst, pathod/__init__.py, pathod/pathoc_cmdline.py, pathod/pathod_cmdline.py
=> mark pathod/pathoc as deprecated

CHANGELOG.rst, examples/contrib/webscanner_helper/mapping.py, examples/contrib/webscanner_helper/proxyauth_selenium.py, examples/contrib/webscanner_helper/test_mapping.py, examples/contrib/webscanner_helper/test_proxyauth_selenium.py, examples/contrib/webscanner_helper/test_urldict.py, examples/contrib/webscanner_helper/test_urlindex.py, examples/contrib/webscanner_helper/test_urlinjection.py, examples/contrib/webscanner_helper/test_watchdog.py, examples/contrib/webscanner_helper/urldict.py
Updated imports and style of the web-scanner-helper addons.
Is an update of the CHANGELOG necessary for changes on the contrib addons?
=> [contrib addons] updated imports and style.

mitmproxy/utils/asyncio_utils.py, mitmproxy/utils/debug.py, mitmproxy/utils/human.py, test/mitmproxy/utils/test_asyncio_utils.py, test/mitmproxy/utils/test_debug.py
=> Add Async Debugging Utilities

setup.py
It's already in install_requires.
=> Remove duplicated flask from dev dependencies

examples/addons/shutdown.py
=> add example to shutdown the proxy master

CHANGELOG.rst, web/src/js/__tests__/components/FlowView/DetailsSpec.js, web/src/js/__tests__/components/FlowView/__snapshots__/DetailsSpec.js.snap, web/src/js/components/FlowView/Details.jsx
Added a check for server address in details.js #4205 . Opening a new pull request with changes suggested from previous PR .
=> Web UI shows blank for details tab when server address is blank 

setup.py
see https://packaging.python.org/guides/making-a-pypi-friendly-readme/
=> fix long description content type

mitmproxy/master.py, mitmproxy/tools/console/consoleaddons.py, mitmproxy/tools/console/flowdetailview.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/window.py, test/mitmproxy/tools/console/test_integration.py
This PR fixes #4382, and (more importantly) adds a harness to drive integration tests for the UI. We can expand on tests here in the future, but we already catch problems like #4382 now!
/cc @Prinzhorn 😉
=> Fix #4382, add console integration tests

CHANGELOG.md, docs/src/content/overview-installation.md, mitmproxy/contrib/README, mitmproxy/contrib/urwid/raw_display.py, mitmproxy/contrib/urwid/win32.py, mitmproxy/tools/console/common.py, mitmproxy/tools/console/window.py, mitmproxy/tools/main.py, release/cibuild.py, release/installbuilder/mitmproxy.xml, release/installbuilder/run.ps1, test/mitmproxy/tools/console/test_integration.py, test/release/test_cibuild.py
This PR vendors [my urwid patch](https://github.com/urwid/urwid/pull/448) adding Windows support to urwid.raw_display. This means we can now run mitmproxy's command line interface natively on Windows! 🎉 
There still are some rough edges when it comes to mouse events for example, but all essential stuff just works fine. 🥳
=> mitmproxy.exe 🎉🥳

mitmproxy/hooks.py, mitmproxy/proxy/context.py, mitmproxy/proxy/events.py, test/mitmproxy/proxy/test_events.py, test/mitmproxy/test_hooks.py
raising causes issues when using pdoc's live reloading, this should fix it.
=> duplicate hooks: warn instead of raise

docs/build.sh, docs/ci.sh, docs/upload-stable.sh
This fixes #4405. @Kriechi, please double check that we don't rm -rf too much. 😄
=> Clean docs folder before building, fixes #4405

docs/src/content/concepts-certificates.md
the help output claims that --certs is correct
=> fix --certs argument

mitmproxy/proxy/context.py, mitmproxy/proxy/events.py, test/mitmproxy/proxy/test_events.py, test/mitmproxy/proxy/test_layer.py
I'm writing api docs with [pdoc](https://pdoc.dev/) at the moment. There will be a bunch of preparatory PRs adding docstrings in the mitmproxy codebase.
=> api docs++

CHANGELOG.md, mitmproxy/tools/console/defaultkeys.py
Press `?` again to exit from help view.
=> Use `?` to exit from help if already there

.github/workflows/main.yml, release/cibuild.py, release/docker/DockerHub-README.md, release/docker/Dockerfile, release/docker/README.md, release/docker/docker-entrypoint.sh
@PeterDaveHello: Alternative to #4495 - what do you think? 😃
=> Docker ctx

mitmproxy/addons/clientplayback.py, mitmproxy/proxy/layers/http/__init__.py, mitmproxy/proxy/layers/http/_events.py, mitmproxy/proxy/layers/http/_hooks.py, mitmproxy/proxy/layers/http/_http2.py, test/mitmproxy/proxy/conftest.py, test/mitmproxy/proxy/layers/http/test_http.py, test/mitmproxy/proxy/layers/http/test_http2.py, test/mitmproxy/proxy/layers/http/test_http_fuzz.py, test/mitmproxy/proxy/tutils.py
=> support http/2 response trailers

web/package.json
=> Set jest time zone, otherwise the test will fail in other time zones

CHANGELOG.md, docs/src/content/overview-features.md, mitmproxy/addons/block.py, mitmproxy/addons/blocklist.py, mitmproxy/flowfilter.py
This PR removes some outdated parts in the documentation and fixes some minor nits.
=> minor cleanups

README.md, docs/bucketassets/robots.txt, docs/ci.sh, docs/scripts/api-render.py, docs/scripts/examples.py, docs/src/content/addons-overview.md, docs/src/content/concepts-howmitmproxyworks.md, docs/src/content/overview-installation.md, docs/src/layouts/partials/edit-on-github.html, release/README.md, release/cibuild.py, release/docker/DockerHub-README.md, setup.py, test/release/test_cibuild.py
Changing branch names doesn't fix any problems, but it serves as a reminder about implicit biases we have that contribute to the lack of diversity in tech. You may say that "master" is harmless, yet this change brings repeated awareness to an important topic. Sorry if we temporarily break your workflow. :)
=> master branch -> main branch

CHANGELOG.md, release/docker/Dockerfile
Add `examples/` into Docker image.
https://github.com/mitmproxy/mitmproxy/issues/1477#issuecomment-545007956
=> Add examples to Docker image

mitmproxy/certs.py
=> keyinfo typing

docs/src/content/howto-install-system-trusted-ca-android.md
The current tutorial for "Install System CA Certificate on Android Emulator" in the docs, which i created a while ago is now outdated and does not work starting from Android 10 as @suntong pointed out here https://github.com/mitmproxy/mitmproxy/commit/a4ff65e321223e29afe782aa2aa70d863ff5c11b#commitcomment-49282339
I updated the tutorial and tested it on different Android versions.
=> docs: update tutorial for Android CA

mitmproxy/net/tls.py
This isn't particularly beautiful, but it's the best approach we have.
=> TLS: support certificates with IP SubjectAlternativeName

CHANGELOG.md, mitmproxy/flowfilter.py, test/mitmproxy/test_flowfilter.py
Flows may be filtered based on metadata and replay status.
=> Metadata and replay filter syntax

CHANGELOG.md, mitmproxy/addons/__init__.py, mitmproxy/addons/comment.py, mitmproxy/flow.py, mitmproxy/flowfilter.py, mitmproxy/io/compat.py, mitmproxy/tools/console/defaultkeys.py, mitmproxy/tools/console/flowdetailview.py, mitmproxy/version.py, test/mitmproxy/addons/test_comment.py, test/mitmproxy/test_flow.py, test/mitmproxy/test_flowfilter.py
A very simple addition of a useful feature from other proxy tools.
=> Add `flow.comment` command and keybinding to add a comment to a flow.

CHANGELOG.md, mitmproxy/http.py, test/mitmproxy/test_http.py
Simple `.json()` method modeled after what Requests does.
=> Add `json()` method for HTTP Request and Response classes.

docs/scripts/api-events.py, examples/contrib/jsondump.py, mitmproxy/addons/dumper.py, mitmproxy/addons/save.py, mitmproxy/eventsequence.py, mitmproxy/proxy/layers/websocket.py, mitmproxy/test/tflow.py, test/mitmproxy/addons/test_dumper.py, test/mitmproxy/addons/test_save.py, test/mitmproxy/proxy/layers/test_websocket.py, test/mitmproxy/test_eventsequence.py, test/mitmproxy/test_flowfilter.py
I think we need a filter for close_code now.
Original discussion in #4674
=> remove websocket_error event, fixes #4674

mitmproxy/proxy/layers/http/__init__.py, test/mitmproxy/proxy/layers/http/test_http.py, test/mitmproxy/proxy/layers/http/test_http2.py
@ericbeland and @kiturutin uncovered some interesting race conditions where we would receive a HTTP/2 server's settings frame before having processed the first request. This PR should fix the two underlying issues. 😃
=> Transparent mode: re-use client SNI when connecting upstream

examples/addons/websocket-inject-message.py, examples/addons/websocket-simple.py, mitmproxy/proxy/layers/websocket.py, mitmproxy/websocket.py, test/mitmproxy/proxy/layers/test_websocket.py, test/mitmproxy/test_websocket.py
tests are dlc and available soon
=> fix forward empty ws messages

mitmproxy/addons/dumper.py, mitmproxy/proxy/events.py, mitmproxy/proxy/layers/tls.py, mitmproxy/proxy/server.py, test/mitmproxy/addons/test_dumper.py, test/mitmproxy/proxy/layers/test_tls.py, test/mitmproxy/proxy/test_layer.py
=> Release Polish

.github/workflows/main.yml, release/README.md, release/cibuild.py, release/deploy.py
This PR fixes the issues described in #4685.
=> Post-Release Cleanups

mitmproxy/proxy/layers/websocket.py, test/mitmproxy/proxy/layers/test_websocket.py
Thanks again @Pilphe for the detailed description in #4701! 🍰
=> Don't emit WS CONT. frames when the peer does not send any, fix #4701

examples/addons/http-stream-modify.py, mitmproxy/http.py, mitmproxy/proxy/layers/http/__init__.py, test/mitmproxy/proxy/layers/http/test_http.py
@cbenien: Here's an experimental patch that makes it possible to return multiple chunks from `.stream`, and also some final ones on messag end. Let me know what you think! 😃
=> Improve HTTP Stream Modification

mitmproxy/addons/export.py, test/mitmproxy/addons/test_export.py, test/mitmproxy/test_optmanager.py
=> Minor flow export-related fixups

mitmproxy/io/io.py, mitmproxy/io/tnetstring.py, test/mitmproxy/io/test_io.py
=> [WIP] add unittest for mitmproxy.io

CHANGELOG.md, docs/src/content/concepts-certificates.md, docs/src/content/howto-ignoredomains.md, docs/src/content/overview-features.md, mitmproxy/addons/tlsconfig.py, mitmproxy/addons/upstream_auth.py, mitmproxy/proxy/server.py, mitmproxy/test/tflow.py, test/mitmproxy/addons/test_upstream_auth.py
This PR fixes a bunch of smaller issues (see individual commits) in preparation for 7.0.1. :)
=> Minor fixes, Docs++

mitmproxy/utils/human.py, test/mitmproxy/utils/test_human.py
Resolves #4696 
If there is any issue, please feel free to tell me and I will fix it.
=> Improve rendering of size column

CHANGELOG.md, mitmproxy/net/encoding.py, test/mitmproxy/net/test_encoding.py
In theory, fixes #4735. Disclaimer: I'm not very familiar with the codebase
=> case insensitive encoding

mitmproxy/net/tls.py
Added extra type hints while experimenting with the code base.
=> Add more type hints

mitmproxy/addons/onboardingapp/templates/index.html
Add MacOS script instructions in the docs to mitm.it
Related PR: #4599
=> Add script instructions for MacOS to mitm.it

CHANGELOG.md, mitmproxy/proxy/context.py, mitmproxy/proxy/layers/tls.py, test/mitmproxy/proxy/layers/test_tls.py, test/mitmproxy/proxy/tutils.py
=> Improve TLS version mismatch error, fix #4758

mitmproxy/optmanager.py
=> Fix typo in optmanager.py

setup.py
Temporary workaround for coverage issue that broke our `individual_coverage` tests.
=> fix import errors caused by coverage.py

CHANGELOG.md, mitmproxy/net/tls.py, setup.py, tox.ini
=> Remove pyopenssl cruft

setup.py
=> Add runtime dependency on setuptools

CHANGELOG.md, mitmproxy/addons/script.py, test/mitmproxy/addons/test_script.py, test/mitmproxy/data/addonscripts/error.py
=> Make sure that `running()` is only invoked once on startup.

CHANGELOG.md, mitmproxy/proxy/server.py
This PR takes the patch from #5034 into main. Thanks again, @EndUser509! 😃:cake:
=> Catch cancellation errors when draining writers, fix #5034

CHANGELOG.md, mitmproxy/addons/core.py, mitmproxy/optmanager.py, mitmproxy/tools/console/options.py, test/mitmproxy/test_optmanager.py, test/mitmproxy/tools/console/test_commander.py
=> Refactor how we process `--set` options

CHANGELOG.md, mitmproxy/addons/proxyserver.py, mitmproxy/proxy/layers/http/_http2.py, test/mitmproxy/proxy/layers/http/test_http2.py, web/src/js/ducks/_options_gen.ts
=> Lowercase HTTP/2 headers by default, fix #4746

mitmproxy/addons/dumper.py, mitmproxy/addons/termlog.py, mitmproxy/contrib/click/__init__.py, mitmproxy/platform/windows.py, setup.cfg, setup.py, test/mitmproxy/addons/test_dumper.py, test/mitmproxy/addons/test_termlog.py
click introduces subdependencies like colorama, this approach is much simpler.
=> Vendor `click.style` instead of depending on click

CHANGELOG.md, mitmproxy/addons/browser.py, test/mitmproxy/addons/test_browser.py
Add flatpak chrome apps support to the browser addon
=> Add flatpak support to the browser addon

CHANGELOG.md, examples/contrib/domain_fronting.py
Adds an addon which implements domain fronting.
=> Add domain fronting example

mitmproxy/addons/save.py, mitmproxy/master.py, mitmproxy/proxy/layers/http/__init__.py, mitmproxy/proxy/server.py, mitmproxy/utils/asyncio_utils.py, mitmproxy/utils/debug.py, test/mitmproxy/proxy/layers/http/test_http.py, test/mitmproxy/proxy/tutils.py, test/mitmproxy/utils/test_asyncio_utils.py, test/mitmproxy/utils/test_debug.py
Correct base branch this time. :)
=> Fix Memory Leaks

mitmproxy/proxy/layers/tls.py, setup.py, test/mitmproxy/proxy/layers/test_tls.py, test/mitmproxy/proxy/tutils.py
Not much to see here - OpenSSL did some slight changes to their error messages (on which we match), other than that we're good. :)
=> Fix compatibility with OpenSSL 3

examples/addons/http-trailers.py
Fix typo in http-trailers.py
- [N/A] I have updated tests where applicable.
- [N/A] I have added an entry to the CHANGELOG.
=> Fix typo in http-trailers.py

docs/scripts/api-render.py, docs/src/content/api/mitmproxy.proxy.mode_specs.md, mitmproxy/flow.py, mitmproxy/proxy/mode_specs.py, test/mitmproxy/proxy/test_mode_specs.py
=> Add `mode_specs` docs, remove `@classmethod @property` usage

mitmproxy/tools/web/app.py
Add compression to dump files, refs #5531
=> mitmweb: compress dump files

mitmproxy/proxy/commands.py, mitmproxy/proxy/events.py, mitmproxy/proxy/layers/modes.py, mitmproxy/proxy/mode_servers.py, mitmproxy/proxy/server.py, test/mitmproxy/proxy/layers/test_modes.py, test/mitmproxy/proxy/test_commands.py
Two small changes in preparation for https://github.com/mitmproxy/windows-transparent-mode 😃
=> Simplify transparent mode, fix listening on port 0

mitmproxy/proxy/mode_servers.py
This is the most dumb approach I've come up with, let's go with that.
=> Improve handling of `port=0`

docs/src/content/concepts-modes.md, mitmproxy/proxy/mode_specs.py, test/mitmproxy/proxy/test_mode_specs.py
Fixes https://github.com/mitmproxy/mitmproxy/pull/5556#discussion_r957481469.
=> Make default_port protocol specific.

CHANGELOG.md, mitmproxy/contentviews/__init__.py, mitmproxy/contentviews/http3.py, mitmproxy/tools/console/window.py, setup.cfg, test/mitmproxy/contentviews/test_http3.py, test/mitmproxy/net/test_tls.py
/cc @meitinger - this should be relatively useful for HTTP/3 debugging:
with
```
mitmweb --mode reverse:quic://quic.westus.cloudapp.azure.com:443@127.0.0.1:8080 --set tcp_hosts=.*
```
and 
```
curl --http3 https://127.0.0.1:8080 -k -vv
```
on 01dba16eb1faef1d1dc502d694ebe8edb3daaf32.
=> Add HTTP/3 contentview

mitmproxy/net/udp.py, mitmproxy/proxy/server.py, test/mitmproxy/net/test_udp.py
Catching up on older issues - here's a simpler fix for #5363. :) @EndUser509, does that look somewhat correct to you?
=> Don't write to closing streams, fix #5363

mitmproxy/tools/console/consoleaddons.py, mitmproxy/tools/console/defaultkeys.py, mitmproxy/tools/console/flowlist.py, mitmproxy/tools/console/master.py, mitmproxy/tools/console/options.py, mitmproxy/tools/console/signals.py, mitmproxy/tools/console/statusbar.py, test/mitmproxy/tools/console/test_statusbar.py
This PR does some minor console-related cleanups.
=> Fix console nits

CHANGELOG.md, docs/src/content/howto-transparent.md
Had trouble running transparent mode for Windows when going through the tutorials as it was missing. Made a PR that fixes #5402. Let me know if the verbiage should be changed or if there are any missing steps.
Thank you.
=> Added Docs for Transparent Mode on Windows

web/src/js/components/FlowView/Messages.tsx
Coincidentally managed to reproduce this one during testing. :)
=> [web] don't crash when server has disappeared, fix #5677

mitmproxy/tools/web/app.py
Turns out tornado does return a future which we just need to wrap. 🙃
=> Fix WebSocketClosedError

CHANGELOG.md, setup.py
Do not merge yet, we want to test the binaries manually first.
=> Downgrade pyinstaller, fix #5699

CHANGELOG.md, mitmproxy/addons/asgiapp.py, mitmproxy/addons/onboarding.py, release/build-and-deploy-docker.py, release/build.py, release/selftest.py
This should prevent some of the issues discovered in the 9.0.0 Docker images in the future 😃
=> Add self-test addon for release scripts

mitmproxy/addons/script.py, test/mitmproxy/addons/test_script.py, test/mitmproxy/data/addonscripts/import_error.py
This is an easy improvement we can make to help on things like https://twitter.com/digininja/status/1593244696045711360.
=> Improve error message for missing packages in frozen binaries

docs/src/content/howto-wireshark-tls.md
fix Wireshark TLS (Pre)-Master-Secret link
=> fix Wireshark TLS (Pre)-Master-Secret link

mitmproxy/tools/dump.py
added loop parameter to DumpMaster so that loop can be passed to parent class Master which allows to directly inherit DumpMaster.
=> Add loop as a parameter in DumpMaster

mitmproxy/contrib/README, mitmproxy/contrib/README.md, mitmproxy/contrib/click/LICENSE.BSD-3, mitmproxy/contrib/kaitaistruct/LICENSE, mitmproxy/contrib/kaitaistruct/README.md, mitmproxy/contrib/kaitaistruct/dtls_client_hello.ksy
=> Clarify license for vendored code

web/src/js/ducks/ui/keyboard.tsx
Added the `delete` key as a shortcut to delete flows in mitmweb. Fixes #5881
=> Add delete shortcut to delete flows in mitmweb

mitmproxy/proxy/mode_servers.py, mitmproxy/proxy/mode_specs.py, test/mitmproxy/addons/test_proxyserver.py, test/mitmproxy/proxy/layers/http/test_http2.py, test/mitmproxy/proxy/layers/http/test_http_fuzz.py, test/mitmproxy/proxy/test_mode_servers.py, test/mitmproxy/proxy/test_mode_specs.py, test/mitmproxy/tools/web/test_app.py
this is merely a proof-of-concept now, but works under the most ideal circumstances.
=> Add experimental Windows OS proxy mode

CHANGELOG.md, mitmproxy/http.py, test/mitmproxy/addons/test_mapremote.py, test/mitmproxy/test_http.py
=> fix `Host` and `:authority` header not being updated on changes to host or port

examples/addons/websocket-inject-message.py, mitmproxy/addons/clientplayback.py, mitmproxy/addons/keepserving.py, mitmproxy/addons/proxyserver.py, mitmproxy/addons/readfile.py, mitmproxy/addons/termlog.py, mitmproxy/proxy/mode_servers.py, mitmproxy/proxy/server.py, mitmproxy/tools/web/app.py, test/bench/benchmark.py, test/conftest.py, test/mitmproxy/test_master.py
=> Fix usage of `asyncio.create_task`

web/src/js/filt/filt.js
Replace: https://github.com/mitmproxy/mitmweb/issues/10
with: https://github.com/mitmproxy/mitmproxy/issues/3609
Related pull request: https://github.com/mitmproxy/mitmproxy/pull/5951. I covered few more occurrences in mine.
=> Update links to mitmweb issue

examples/contrib/dns_spoofing.py
=> update api for sni call

CHANGELOG.md, mitmproxy/tools/console/defaultkeys.py
=> Allow focus-follow shortcut to work in flow view context.

docs/src/content/howto-transparent.md
File `pf.conf` needs to end with a blank newline for the configuration to be valid. Update the doc according to issue #4748
=> Update file howto-transparent.md as suggested in issue #4748

examples/addons/duplicate-modify-replay.py
close #4272 with a small docs fix
=> solve #4272 docs bug

CHANGELOG.md, mitmproxy/proxy/layers/http/__init__.py, test/mitmproxy/proxy/layers/http/test_http.py
=> Re-use SNI in reverse proxy mode if the original connection was torn down

mitmproxy/proxy/layers/quic.py, test/mitmproxy/proxy/layers/test_quic.py
=> Do not crash on invalid quic headers

mitmproxy/proxy/mode_servers.py, mitmproxy/tools/web/master.py, test/mitmproxy/tools/web/test_master.py
=> recommend port+2 instead of port+1 to avoid clashes with mitmweb

docs/src/content/_index.md
=> Fix grammar in _index.md

mitmproxy/connection.py
refs https://github.com/mitmproxy/mitmproxy/discussions/6351
=> Improve docstring for `Server.address`

CHANGELOG.md, mitmproxy/contentviews/__init__.py, mitmproxy/contentviews/dns.py, mitmproxy/contentviews/hex.py, mitmproxy/contentviews/http3.py, test/mitmproxy/contentviews/test_auto.py, test/mitmproxy/contentviews/test_dns.py, test/mitmproxy/contentviews/test_hex.py
We probably need to figure out something better here sometime soon, but this here is simple and a clear improvement.
=> Add DoH contentview

examples/addons/nonblocking.py
This previously caused an error on import (https://twitter.com/digininja/status/1711355339637973146), which we want to avoid.
=> fix nonblocking.py example

.github/workflows/main.yml, CHANGELOG.md, mitmproxy/addons/clientplayback.py, mitmproxy/optmanager.py, mitmproxy/proxy/mode_servers.py, mitmproxy/proxy/server.py, pyproject.toml, test/mitmproxy/addons/test_asgiapp.py, test/mitmproxy/addons/test_clientplayback.py, test/mitmproxy/addons/test_proxyserver.py, test/mitmproxy/addons/test_script.py, test/mitmproxy/proxy/test_mode_servers.py, test/mitmproxy/tools/web/test_master.py
We also tighten what sort of warnings we accept in tests to make sure these shenanigans don't happen again.
=> Fix a bug where connections would not be fully closed

mitmproxy/certs.py
/cc @driuba - does that look good?
=> simplify cert loading with new cryptography APIs

web/src/js/components/FlowView/HttpMessages.tsx, web/src/js/components/contentviews/HttpMessage.tsx
i have added image preview support in  /web/src/components/contentviews/HttpMessage/tsx
=> added svg image preview support

release/build.py
refs https://github.com/mitmproxy/www/issues/57. 
Will wait until next release to merge in sync with changes in mitmproxy/www.
=> Unify download filenames

CHANGELOG.md, mitmproxy/addons/next_layer.py, test/mitmproxy/addons/test_next_layer.py
This PR fixes https://github.com/mitmproxy/mitmproxy/issues/6554.
=> fix ignore hosts to not drop connections, improve http header handling

CHANGELOG.md, mitmproxy/proxy/mode_servers.py
=> Wireguard mode: bind to 0.0.0.0

test/mitmproxy/addons/test_next_layer.py
Minor correction that does not change test case result however passes params in the intended order.
=> Micro-fix to arrange items in the right order.

.github/workflows/main.yml, CHANGELOG.md
=> Build macOS arm64 binaries

mitmproxy/contentviews/__init__.py, mitmproxy/contentviews/graphql.py, test/mitmproxy/contentviews/test_graphql.py, test/mitmproxy/contentviews/test_json.py
=> Fix `Couldn't parse: falling back to Raw` for empty JSON array

mitmproxy/proxy/layers/tls.py, pyproject.toml, test/mitmproxy/proxy/layers/test_tls.py
Fix the test cases for OpenSSL v3
Ref:
https://github.com/openssl/openssl/commit/81b741f68984b2620166d0d6271fbd946bab9e7f
https://github.com/openssl/openssl/commit/4030869d24309bfb5292e7bec41cd2b3012ba99d
=> Fix error message in OpenSSL >=3.2.0

.gitignore, CHANGELOG.md, mitmproxy/addons/errorcheck.py, mitmproxy/master.py, test/mitmproxy/addons/test_errorcheck.py
=> fix display of error messages on early shutdown

examples/addons/tcp-simple.py, examples/contrib/httpdump.py, test/bench/benchmark.py
=> Fix some typos

CHANGELOG.md, mitmproxy/tools/web/master.py
Just added ReadFileStdin class to mitmweb
- afaik there are already tests for ReadFileStdin
=> 6704-readfile

CHANGELOG.md, mitmproxy/tools/console/master.py, test/mitmproxy/tools/console/test_master.py
Changed editor spawner so it checks if a file is mostly binary (using strutils), and opens the appropriate editor.
=> Add hex editor for non text files

CHANGELOG.md, mitmproxy/certs.py
=> fix cryptography DeprecationWarning

CHANGELOG.md, mitmproxy/addons/tlsconfig.py, test/mitmproxy/addons/test_tlsconfig.py
=> Fix certs for unicode domains

CHANGELOG.md, mitmproxy/addons/readfile.py, test/mitmproxy/addons/test_readfile.py
=> Fix program exit when `n` is passed

CHANGELOG.md, release/specs/standalone.spec
=> Update PyInstaller spec to set the u (unbuffered) flag

CHANGELOG.md, mitmproxy/addons/proxyauth.py, test/mitmproxy/addons/test_proxyauth.py
=> Skip proxyauth on client replay, fix #6836

pyproject.toml
=> Use upstream urwid again

CHANGELOG.md, docs/scripts/api-events.py, mitmproxy/proxy/layers/http/__init__.py, mitmproxy/proxy/layers/http/_hooks.py, test/mitmproxy/proxy/layers/http/test_http.py
Cleaned up version of #6906
Fixes https://github.com/mitmproxy/mitmproxy/issues/6632
=> Add `HttpConnectedHook` and `HttpConnectErrorHook`

mitmproxy/proxy/layers/quic.py
As suggested by @jlaine via email. :)
=> QUIC: Fix Supported Versions

web/src/css/header.less, web/src/js/__tests__/components/FlowViewSpec.tsx, web/src/js/__tests__/components/Header/CaptureMenuSpec.tsx, web/src/js/__tests__/components/Header/MainMenuSpec.tsx, web/src/js/__tests__/components/Header/__snapshots__/CaptureMenuSpec.tsx.snap, web/src/js/__tests__/components/HeaderSpec.tsx, web/src/js/__tests__/components/__snapshots__/HeaderSpec.tsx.snap, web/src/js/__tests__/ducks/tutils.ts, web/src/js/components/FlowView.tsx, web/src/js/components/Header.tsx, web/src/js/components/Header/FlowListMenu.tsx, web/src/js/components/MainView.tsx, web/src/js/components/ProxyApp.tsx, web/src/js/ducks/ui/index.ts, web/src/js/ducks/ui/tabs.ts
Once we have a flow, we should display that instead of configuration! In particular, `mitmweb -r file` should spawn with the flow list.
=> Web: Switch to flow list upon arrival of the first flow.

test/mitmproxy/addons/test_tlsconfig.py
This is accommodating for upstream changes. :)
=> loosen cryptography warning

CHANGELOG.md, mitmproxy/tools/console/options.py
=> Allow `typing.Sequence[str]` to be an editable option

CHANGELOG.md, mitmproxy/addons/clientplayback.py, mitmproxy/addons/proxyserver.py, mitmproxy/proxy/server.py, test/conftest.py, test/mitmproxy/proxy/test_server.py
This fixes a really gnarly bug that turned up in https://github.com/mitmproxy/mitmproxy/issues/7027.
=> Guard server_event against reentrancy, fix #7027

CHANGELOG.md, web/src/css/flowtable.less, web/src/js/__tests__/components/FlowTable/__snapshots__/FlowColumnsSpec.tsx.snap, web/src/js/components/FlowTable/FlowColumns.tsx, web/src/js/flow/utils.ts
=> web: add index column

CHANGELOG.md, mitmproxy/addons/next_layer.py, test/mitmproxy/addons/test_next_layer.py
Fix for https://github.com/mitmproxy/mitmproxy/issues/7023#issuecomment-2249453950
=> Nextlayer: detect SSH as non-HTTP

CHANGELOG.md, mitmproxy/addons/next_layer.py, mitmproxy/proxy/layers/quic.py, test/mitmproxy/proxy/layers/test_modes.py, test/mitmproxy/proxy/layers/test_quic.py
Handles fragmented QUIC client hello
refs #7025
=> Handle fragmented QUIC client hello

test/mitmproxy/proxy/test_mode_servers.py
I was seeing ghosts due to `tox -e py` still having an old mitmproxy_rs version. I parametrized the test to get better debugging info, which I guess is the only positive result from what otherwise was a waste of time. 😅
=> parametrize dual stack test to ease debugging

web/src/css/mode.less, web/src/js/components/Modes/CaptureSetup.tsx, web/src/js/components/Modes/Reverse.tsx, web/src/js/components/Modes/ReverseToggleRow.tsx
Some super minor improvements. 😃
=> Capture tab nits

web/src/js/components/Modes/Socks.tsx, web/src/js/components/Modes/Transparent.tsx
In this PR, I've added the popover functionality to the socks and the transparent modes. Nothing too special :)
=> add popover to socks and transparent

CHANGELOG.md, mitmproxy/tools/main.py
=> Use loop.add_signal_handler on supported platforms

CHANGELOG.md, mitmproxy/addons/tlsconfig.py, mitmproxy/net/tls.py, test/mitmproxy/addons/test_tlsconfig.py, test/mitmproxy/net/test_tls.py
=> Warn if TLS version is unsupported by OpenSSL

web/src/js/__tests__/components/Modes/__snapshots__/RegularSpec.tsx.snap, web/src/js/components/Modes/Dns.tsx, web/src/js/components/Modes/Local.tsx, web/src/js/components/Modes/ModeToggle.tsx, web/src/js/components/Modes/Regular.tsx, web/src/js/components/Modes/Reverse.tsx, web/src/js/components/Modes/Socks.tsx, web/src/js/components/Modes/Transparent.tsx, web/src/js/components/Modes/Upstream.tsx, web/src/js/components/Modes/Wireguard.tsx
In this PR, I'm adding the ability to activate or deactivate a mode by clicking on its label
Ref: minor stuff of #7063
=> Click on mode's label to activate it

mitmproxy/addons/dns_resolver.py, mitmproxy/proxy/mode_servers.py, mitmproxy/proxy/mode_specs.py, mitmproxy/proxy/server.py, mitmproxy/tools/web/app.py, pyproject.toml, test/mitmproxy/addons/test_dns_resolver.py, test/mitmproxy/addons/test_proxyserver.py, test/mitmproxy/proxy/test_mode_servers.py, test/mitmproxy/tools/web/test_app.py
/cc @lups2000: this includes the fix that we raise for unknown paths on Windows.
=> Upgrade to mitmproxy_rs 0.8

.github/workflows/main.yml, pyproject.toml
0.9 has a different approach to fix the Windows stack overflow, let's see how it goes.
=> bump mitmproxy_rs

release/docker/Dockerfile
A one-liner, resolving https://github.com/mitmproxy/mitmproxy/issues/7156
=> added chown for .mitmproxy volume

mitmproxy/tools/web/app.py
=> mitmweb: cache executable icons

CHANGELOG.md, mitmproxy/addons/dumper.py, mitmproxy/connection.py, mitmproxy/io/compat.py, mitmproxy/proxy/layers/quic/_stream_layers.py, mitmproxy/proxy/layers/tls.py, mitmproxy/tools/console/common.py, mitmproxy/version.py, test/mitmproxy/addons/test_dumper.py, test/mitmproxy/data/dumpfile-19.mitm, test/mitmproxy/io/test_compat.py, web/src/js/flow/utils.ts
This aligns us with what OpenSSL is returning.
=> tls_version: QUIC -> QUICv1

CHANGELOG.md, mitmproxy/addons/next_layer.py, mitmproxy/options.py, mitmproxy/proxy/layers/quic/_raw_layers.py, test/mitmproxy/addons/test_next_layer.py, test/mitmproxy/proxy/layers/quic/test__raw_layers.py, web/src/js/ducks/_options_gen.ts
GSoC Success 🥳
depends on #7201
=> Enable HTTP/3 in transparent mode by default

CHANGELOG.md, release/docker/Dockerfile, release/docker/docker-entrypoint.sh
=> Docker: use latest python and debian

CHANGELOG.md, mitmproxy/tools/console/common.py, test/mitmproxy/tools/console/test_common.py
=> Don't crash UI on negative durations

CHANGELOG.md, mitmproxy/net/http/http1/read.py, mitmproxy/net/http/validate.py, mitmproxy/proxy/layers/http/__init__.py, test/mitmproxy/net/http/http1/test_read.py, test/mitmproxy/net/http/test_validate.py
=> Improve transfer-encoding error messages, be more permissive if validate_inbound_headers is disabled

docs/src/content/concepts-certificates.md
In this PR, I've updated the documentation as proposed here: #6924
=> update docs: certificate installation on iOS simulator 

web/src/js/ducks/commandBar.ts
In this PR, I've updated the command bar duck to RTK.
=> update commandBar duck to RTK

CHANGELOG.md, mitmproxy/tools/web/templates/index.html, web/src/templates/index.html
Turns out this is a super easy fix because tornado has builtin functionality. 🎉 
fixes #7381
=> Implement Cache-Busting for mitmweb

docs/src/content/concepts-certificates.md, mitmproxy/addons/onboardingapp/templates/index.html
Pretty minor change, I don't think updating the changelog is required.
=> Added Certificate Installation steps for Arch Linux

CHANGELOG.md, mitmproxy/net/http/status_codes.py
Update list of supported status codes. Fixes: #7451
=> fix: Add missing HTTP status codes

CHANGELOG.md, mitmproxy/addons/blocklist.py, test/mitmproxy/addons/test_blocklist.py
Fixes: #7451.
If someone wants to reply with their own custom error code, they shall do that. Hence, I've removed the check.
=> Remove check for status codes in the blocklist add-on

CHANGELOG.md
Fix `CHANGELOG.md` formatting glitch
=> chore: Fix CHANGELOG.md formatting glitch

CHANGELOG.md, mitmproxy/tools/console/consoleaddons.py, mitmproxy/tools/console/defaultkeys.py, mitmproxy/tools/console/master.py
Fixes #7413 
Refs #7282
~- Added prompts for destructive shortcuts~
~- Mapped the no-prompts version to `ctrl+[key]`~
~Yet to add tests and update [KeyMapConfig.load_path](https://github.com/mitmproxy/mitmproxy/blob/6e4cb235fdc7d0f55b8edcda37e9f7cb0c8fda22/mitmproxy/tools/console/keymap.py#L209), wanted to get feedback before proceeding further.~
Prompts user before clearing screen
=> Prompt user before clearing screen

mitmproxy/addons/dns_resolver.py, test/mitmproxy/addons/test_dns_resolver.py
This PR is a refactor to prepare https://github.com/mitmproxy/mitmproxy/issues/7266. Filing it first for easier review.
=> dns resolver: make Hickory and `getaddrinfo` resolvers available using the same protocol

.github/workflows/autofix.yml, .github/workflows/main.yml, .github/workflows/release.yml, CHANGELOG.md
fixes https://github.com/mitmproxy/mitmproxy/issues/6756
=> Build arm64 binaries

docs/src/content/web-tutorials/web-01-user-interface.md, docs/src/layouts/partials/sidebar.html, docs/src/layouts/shortcodes/video.html
Add the first mitmweb tutorial from @EstherRoeth.
=> docs: Add mitmweb user interface tutorial

CHANGELOG.md, docs/src/content/web-tutorials/web-01-user-interface.md, docs/src/content/web-tutorials/web-02-intercepting-traffic.md, docs/src/content/web-tutorials/web-03-analysing-flows.md, docs/src/content/web-tutorials/web-04-modifying-requests.md, docs/src/content/web-tutorials/web-05-replaying-flows.md
add mitmweb tutorial videos to docs
=> Add mitmweb tutorial videos to docs 

CHANGELOG.md, mitmproxy/addons/next_layer.py, test/mitmproxy/addons/test_next_layer.py
=> Next Layer: Don't wait for host header based on alpn

CHANGELOG.md, mitmproxy/tools/web/webaddons.py
=> mitmweb: recommend setting `web_password` for systems without browser

docs/src/content/concepts-modes.md, release/docker/docker-entrypoint.sh
We haven't documented TUN mode yet, let's fix that!
=> Add proxy mode docs for tun mode

CHANGELOG.md, mitmproxy/addons/export.py, test/mitmproxy/addons/test_export.py
fix https://github.com/mitmproxy/mitmproxy/issues/7561
=> Ensure export output has no surrogates

CHANGELOG.md, mitmproxy/options.py, web/src/js/__tests__/components/Header/__snapshots__/OptionMenuSpec.tsx.snap, web/src/js/__tests__/components/__snapshots__/HeaderSpec.tsx.snap, web/src/js/components/Header/OptionMenu.tsx
We're already pretty good on this, this here fixes the remaining leftovers.
=> Ensure that all mitmweb options have help text.

.github/workflows/main.yml, test/mitmproxy/proxy/layers/test_tls.py
kudos to @alex for discovering this. 🙏
=> Fix CI: actually test on older Python versions

docs/src/assets/css/components/github-button.scss, docs/src/assets/css/style.scss, docs/src/content/_index.md, docs/src/layouts/_default/baseof.html, docs/src/layouts/partials/add-anchors.html, docs/src/layouts/partials/sidebar.html
Fixing some accessibility issues - this should only affect users with assistive technologies.
=> docs: improve accessibility

CHANGELOG.md, web/src/js/flow/utils.ts
=> Preventing mitmweb crash when viewing flows with undefined headers

examples/contrib/change_upstream_proxy.py
Didn't test it, https://github.com/mitmproxy/mitmproxy/issues/7602 says it works
=> Fix change_upstream_proxy.py example

mitmproxy/http.py, mitmproxy/net/http/url.py, test/mitmproxy/net/http/test_url.py
The parse implementation is still awful, but this is a bit of progress
/cc @JordanPlayz158
=> fixup url.unparse

docs/src/content/concepts/modes.md
=> docs: mention that transparent mode is TCP only for now

web/src/css/mode.less, web/src/js/__tests__/components/Modes/LocalDropdownSpec.tsx, web/src/js/__tests__/components/Modes/__snapshots__/LocalDropdownSpec.tsx.snap, web/src/js/components/Modes/LocalDropdown.tsx
In this PR, I'm trying to enhance the UI/UX of the local mode in mitmweb, based on the discussion in #7546. For the sake of simplicity, I’ve added a new entry to the dropdown (**All applications**),  which represents the default value when toggling the local mode.
DEMO:
https://github.com/user-attachments/assets/f632bee1-8953-423f-b732-175e88370ab9
Let me know your thoughts :)
=> Local mode UX enhancement in mitmweb

docs/src/content/concepts/modes.md
=> docs: mention that macOS local mode covers egress only

mitmproxy/tools/console/consoleaddons.py, mitmproxy/tools/console/defaultkeys.py, mitmproxy/tools/console/window.py, mitmproxy/tools/main.py
This is particularly useful for CLI recordings
=> console ux: make it more clear what the current dialog is about

CHANGELOG.md, web/src/js/__tests__/ducks/flowsSpec.tsx, web/src/js/components/FlowTable/FlowColumns.tsx, web/src/js/components/Header/FlowMenu.tsx, web/src/js/ducks/flows.ts, web/src/js/ducks/ui/keyboard.tsx
In this PR, I have implemented the last missing feature for multiple selected flows: replay. This is a continuation of #7319.
=> Replay multiple selected flows in mitmweb

mitmproxy/addons/tlsconfig.py, mitmproxy/certs.py, mitmproxy/net/tls.py, pyproject.toml, test/mitmproxy/contentviews/test__compat.py, test/mitmproxy/contentviews/test_base.py, test/mitmproxy/net/test_free_port.py, test/mitmproxy/net/test_tls.py, test/mitmproxy/test_certs.py, uv.lock
This PR fixes a bunch of deprecation warnings surfaced in tests.
=> Fix various deprecation warnings

web/src/js/__tests__/components/Header/__snapshots__/OptionMenuSpec.tsx.snap, web/src/js/__tests__/components/__snapshots__/HeaderSpec.tsx.snap, web/src/js/__tests__/ducks/tutils.ts, web/src/js/__tests__/urlStateSpec.tsx, web/src/js/components/Header.tsx, web/src/js/components/Header/OptionMenu.tsx, web/src/js/ducks/ui/tabs.ts, web/src/js/flow/utils.ts, web/src/js/urlState.ts
=> Web: fix nits

CHANGELOG.md, mitmproxy/tools/console/consoleaddons.py
=> Fix a crash when editing raw message bodies in mitmproxy

web/src/js/__tests__/ducks/eventLogSpec.tsx, web/src/js/ducks/eventLog.ts
100x performance improvement, this is insane.
=> web: move eventlog reducer off immer

web/package-lock.json, web/package.json
This went away with one of the recent cleanups. :)
=> web: remove unused prop-types dependency

CHANGELOG.md, web/src/js/__tests__/ducks/flows/indexSpec.tsx, web/src/js/ducks/flows/index.ts
This should fix a regression in 12.1 when loading an existing flows file from disk. :)
=> web: account for race conditions during flow fetching

docs/src/content/addons/event-hooks.md
=> docs: fix relative URLs on event hook page
