mitmproxy/mitmproxy

libmproxy/console/__init__.py

Hi Max, 
I've just backported the fix in mitmproxy's start_server_playback() from PR [#439] to add the missing parameter (replay_ignore_payload_params) which is present in mitmdump but was missing in mitmproxy.
Regards
Marcelo

hotfix to mitmproxy missing start_server_playback() parameter added. 

---

libmproxy/console/flowlist.py

Hi Max,
I found two more places were start_server_playback has missing the last parameter 
I grep the code and these seems like the only places were it was missing
Regards.
Marcelo

missing parameter in start_server_playback call (again)

---

setup.py

We should use setuptool's `entry_points` instead of `scripts` - `scripts` don't work on Windows.

use entry_points for Windows support

---

libmproxy/console/common.py
libmproxy/utils.py
test/test_utils.py

Hi Max, 
i've added to flowview and flowlist time elapsed to handle request. I've used the difference between end of request and end of response but flow has timestamps for begin and end for both request and response so other combinations can be shown either. 
Just let me know if this approach seems ok or you want to calculate it differently. Or perhaps add to view more times (req time: xxx ms., resp time: yyy ms. , whole time: zzz ms.)
I created this PR for issue #487 
Regards
Marcelo

added time elapsed between request sent and response received

---

README.mkd
dev
dev.bat

- add dev.bat for Windows users
- remove superfluous pip install calls.
- remove `~/.pipcache` stuff.  
If that causes issues with PyInstaller, we should use `pip --no-cache-dir` there or `rm -r pip.locations.USER_CACHE_DIR`.
@cortesi: third change works for you?

simplify virtualenv

---

libmproxy/cmdline.py
libmproxy/console/__init__.py
libmproxy/console/flowlist.py
libmproxy/dump.py
libmproxy/flow.py
test/test_flow.py

Similar to the other --replay-ignore-* options, this prevents matching on the destination address while searching for flows to replay.
The use case necessitating this is replaying server responses (in transparent mode) for domains that use multiple IP addresses.

Add --replay-ignore-host option

---

libmproxy/console/__init__.py

Checking bug #522 (which i can reproduce) found that presing "c" (client replay) mitmproxy crashes with this error: 
```
File "/home/gato/trabajos/mitmproxy/libmproxy/console/__init__.py", line 805, in run
self.loop.run()
File "/home/gato/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
self._run()
File "/home/gato/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
self.event_loop.run()
File "/home/gato/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
self._loop()
File "/home/gato/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
self._watch_files[fd]()
File "/home/gato/.local/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
event_loop, …
```

fixes crash pressing 'c':client-replay in mitmproxy

---

libmproxy/console/common.py

Hi @cortesi 
this PR solves #531
When feature #334 was implemented i found a similar error once (a TypeError) but couldn't reproduce it again, so we removed the catch for these type of error. (see https://github.com/mitmproxy/mitmproxy/pull/448#discussion-diff-24215901R226) As pyperclip uses different base tools to do the actual copying depending on OS and installed libraries (gtk, xsel, pbpaste, etc) is hard to know in advance what exceptions can be thrown. I could reproduce the UnicodeDecodeError on a Mac running Yosemite (10.10.3) and this solve it. (well actually just catch the exception and offers to save the content as file instead)
Regards
Marcelo

handles UnicodeDecodeError (#531)

---

libmproxy/flow.py
test/test_flow.py

I've found that some websites use query values that are blank, e.g. foobar.com/index?thing.
The current master branch would hash '/index?thing' and '/index?other' as the same flow for server replay, which is undesirable. This patch causes these blank query values to be preserved and included when hashing.

Keep blank query values for flow hashing

---

examples/ignore_websocket.py

Some servers respond with `"upgrade"`; so just normalize the field value.
(Just I realized that maybe, should also be done for the header name? I dunno..)

Make the Websocket's connection header value case-insensitive

---

libmproxy/platform/__init__.py
libmproxy/platform/pf.py

+ Use sys.platform.startswith("freebsd") instead of matching just freebs...
+ This means support for any freebsd version (note that I only tested 11-CURRENT and 9)

Match all freebsd versions and not just freebsd10

---

libmproxy/protocol/http.py

When building a request from a stream, try to get an accurate
start timestamp from the Reader. This was already in the code
and also used when building response objects, but was omitted
in commit ddf458b330bf9fe200cb1dbc3ddb5ae1a5d2102a
Without his logic and when the client is reusing a connection
to send requests, the timestamp_start of subsequent requests
is early and equal to when the connection started read blocking

Accurately timestamp start of request

---

doc-src/features/passthrough.html

because wouldnt work with default bash settings as its part of history expansion in bash

docs: Single Qoute for ignore pattern with "!"

---

libmproxy/protocol/http.py

rather than hardcoding to 1.1.
This helped me to work around the scenario where I was testing some old code that broke because it was expecting to receive 'HTTP/1.0 200 Connection established'

Make sure proxy returns the httpversion specified in the request

---

.env

* properly quote DIR variable
(it might contain spaces)
* use builtin string magic instead of `dirname`

improve autoenv script

---

libmproxy/console/common.py

fixes #604 if pyperclip is not found offers save to file instead of copying to clipboard

fixes #604 catch method not found for handling pyperclip not found

---

libmproxy/cmdline.py
libmproxy/protocol/http.py
libmproxy/proxy/config.py
libmproxy/proxy/primitives.py
libmproxy/proxy/server.py
test/test_proxy.py
test/test_server.py
test/tservers.py

Added http transparent proxy mode.
Unlike transparent proxy mode, this mode uses the Host header to connect to a server.
```
$ mitmproxy --http-transparent -p 8080
$ nc localhost 8080
GET / HTTP/1.1
Host: www.example.com
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 1270
...
```
Example of use:
Host A (192.168.100.2) ... using mitmproxy
```
$ mitmproxy --http-transparent -p 8080
```
Host B (192.168.200.1) ... routing ip packets, redirecting tcp:http packets to A
```
$ sysctl -w net.ipv4.ip_forward=1
$ iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 80 -j DNAT --to-destination 192.168.100.2:8080
```

HTTP Transparent Proxy

---

libmproxy/proxy/config.py

based on @mhils comment: https://github.com/mitmproxy/pathod/pull/27/files#r32608761
This PR unifies the usage of SSL version and method identifiers from CLI and internal usage.
Requires these other PRs to work: https://github.com/mitmproxy/netlib/pull/75 and https://github.com/mitmproxy/pathod/pull/29

unify SSL version/method handling

---

libmproxy/proxy/config.py
libmproxy/proxy/server.py
test/test_server.py
test/tservers.py

The certforward feature was implemented to support #gotofail, which only works on unpatched iOS devices. Given that many apps don't support iOS 7 anymore, jailbreak+ssl killswitch is usually the better option. By removing certforward, we can make netlib a pure python module again, which significantly simplifies distribution.
depends on https://github.com/mitmproxy/netlib/pull/79
closes #360 
closes #471
closes #629
closes https://github.com/mitmproxy/netlib/issues/33
closes https://github.com/mitmproxy/netlib/issues/63
closes https://github.com/mitmproxy/netlib/issues/68

Remove Certforward Feature

---

libmproxy/filt.py
test/test_filt.py

This filter allow to match on the request source and destination addresses in the form
of `<IP>:<Port>` with `~src` and `~dst`.
Ex:
* Match client IP: `~src 192.168.0.123`
* Match source subnet: `~src 192.168.0.*`
* Match port: `~dst :8080`
Also fixed the parsing grammar to add a `WordEnd` after each filter
name. That way, `~src` doesn't match `~s` instead and keep the behavior
consistent with `~hq` != `~h`.
An alternative, which look betters IMO, but isn't consistent with the others filter name would be using name such as:
* `~src.ip`
* `~src.port`
This look similar to Wireshark notation and could be extended to other filter such as `~request.headers.host google.com` which might look better and be easier to remember than `~hq 'host.*google.com'`.

Add source address filter

---

libmproxy/web/app.py

Otherwise, a non-unicode character in a flow cause mitmweb to crash.
```
File "./mitmweb", line 4, in <module>
mitmweb()
File "/home/isra17/devel/mitmproxy/mitmproxy/libmproxy/main.py", line 120, in mitmweb
m = web.WebMaster(server, web_options)
File "/home/isra17/devel/mitmproxy/mitmproxy/libmproxy/web/__init__.py", line 131, in __init__
self.load_flows_file(options.rfile)
File "/home/isra17/devel/mitmproxy/mitmproxy/libmproxy/flow.py", line 884, in load_flows_file
return self.load_flows(freader)
File "/home/isra17/devel/mitmproxy/mitmproxy/libmproxy/flow.py", line 874, in load_flows
self.load_flow(i)
File "/home/isra17/devel/mitmproxy/mitmproxy/libmproxy/flow.py", line 859, in load_flow
self.handle_request(f)
File …
```

Use `ensure_ascii` in wep.app#broadcast

---

libmproxy/console/grideditor.py
libmproxy/flow.py
libmproxy/protocol/http.py
libmproxy/proxy/config.py
test/test_protocol_http.py
test/test_proxy.py
test/test_server.py

This PR starts of a larger refactoring process to unify everything related to HTTP semantics and split the actual "on-the-wire" protocol from the overall flow behind it.
Mostly moving code around between projects, modules, and classes.
This PR requires mitmproxy/netlib#81 to work properly.
This PR requires mitmproxy/pathod#31 to work properly.

HTTP protocol refactoring

---

libmproxy/flow.py
libmproxy/protocol/http.py
libmproxy/protocol/primitives.py
test/test_server.py

Selectively connect to upstream server based on certforward and
no_upstream_cert options. When no_upstream_cert is used during server
replay, this patch prevents connecting to the upstream server unless
absolutely necessary.

Prevent unnecessary upstream server connects

---

libmproxy/cmdline.py
libmproxy/console/__init__.py
libmproxy/main.py

Adds the --no-mouse command line option to disable the mouse.
Fixes #685

console: add command line flag to disable mouse interaction

---

libmproxy/script.py

Bash (and many other shells) provide a nifty feature in "anonymous pipe" or "anonymous fifo" whereby the output of a subshell may be treated as a simple file by the parent shell: http://unix.stackexchange.com/a/156088
Unfortunately, libmproxy complains because that "file" is not a regular file, as os.path.isfile checks, e.g. giving the error "Not a file: /dev/fd/11". This patch is intended to provide for the following use-case:
```
mitmdump -s <(echo "def response(context, flow):\n  flow.response.headers['newheader'] = [`hostname`]")
```
where `hostname` may be replaced with a more complicated lookup.

Allow reading scripts from an anonymous pipe

---

libmproxy/models/connections.py

Fixes #761 by returning an empty server address if connection hasn't yet been made

server_conn.address might not yet be established

---

libmproxy/console/flowview.py

When accepting intercepted flows with 'a' or 'A' command in flowview, mitmproxy makes new window every time. So, I need to press 'q' button several times to return the flow list.

Prevent flowview from creating duplicated windows

---

libmproxy/console/common.py
libmproxy/console/help.py

I want to use ctrl+f/b to scroll down/up one page, just like `less` and `vi(m)`.
Since b (save request/response body) and f (load full body data) are used as other commands, I only implemented ctrl+f/b, unlike `less`.

Use ctrl+f and ctrl+b to scroll a page

---

libmproxy/platform/osx.py

On my system, I was receiving a `CalledProcessError` when the pfctl subprocess executed, resulting in a vague "Transparent mode failure: CalledProcessError()" message.
This should make it more likely to report the correct error.

Better error handling/reporting for pfctl failures on OS X

---

test/test_contentview.py

I think the test code should *probably* use odict stuff but this fixes the failing test case
```
================================================================================================================== FAILURES ==================================================================================================================
_________________________________________________________________________________________________________ test_view_protobuf_request _________________________________________________________________________________________________________
def test_view_protobuf_request():
v = cv.ViewProtobuf()
p = tutils.test_data.path("data/protobuf01")
content_type, output = v(file(p, "rb").read())
assert content_type == "Protobuf"
>       assert output[0].text == '1: …
```

Fix failing protobuf contentview test

---

libmproxy/contentviews.py

Fix this by myself! :smiley:  
Simply set encoding type to utf8 in ```lxml.etree.tostring``` function.

Fix #835 , can display unicode character correctly

---

libmproxy/dump.py

I tested this and warnings no longer corrupt the file when I run
`mitmdump -q -w /dev/stdout > out` then `mitmdump -n -r out`
cc @mhils

TLS verification warnings write to stderr

---

setup.py

Tested with Pillow 3.1.0, all tests passed and the functionality is working correctly here.

Allow Pillow 3.1

---

docs/scripting/inlinescripts.rst
examples/tcp_message.py
libmproxy/flow.py
libmproxy/protocol/rawtcp.py
test/scripts/tcp_stream_modify.py
test/test_server.py

:dancer:  This early PR is the beginning of advancement on #747
@mhils Specifically, regarding the removal of the `layer` attribute from TcpMessage, I took out the `layer` from class `TcpMessage` and now send the `client_conn` and `server_conn` explicitly to the initializer... Let me know if you had something else in mind, as far as getting the `client_conn` and `server_conn` into the TcpMessage. 
This is not yet included, but I am working on an inline script using the new feature that might be able to serve as an example script. More details to come on this later.
Do new inline script hooks need unit tests??
Do any docs need updating?
The following is a key point of `TcpMessage`:
`sender` and `receiver` are mirrors to `client_conn` or `server_conn`. Together, the four are used to …

Add "tcp_message" Inline Script Hook

---

libmproxy/console/flowdetailview.py

Connections become false values when it's `finished`. Check if it's
`None` when trying to show address info.
Fixes #886.

[console] always show connection info in Details tab

---

libmproxy/contentviews.py

Was getting a crash viewing AMF requests... tracked it down to inflated python date objects that can't deserialize directly to JSON. This worked for me - might be a better way to do this...

fix crash with viewing unpacked date objects

---

libmproxy/main.py
setup.py

This PR simplifies our setup.py to use enviroment markers to specify dependencies. This allows us to build a wheel for mitmproxy, which should improve installation speed. Also, this should make requires.io work with mitmproxy. The downside is that we don't support old setuptools versions anymore, but to my understanding, we will have this "issue" with `h2` as a dependency anyway. Ubuntu 14.04 LTS+ onwards should work.

Modern setuptools

---

docs/install.rst
setup.py

This PR removes the compatible version specifiers again. This allows us to `pip install mitmproxy` on Ubuntu 14.04 out of the box. Also, I added a note for Ubuntu 12.04 that users need to update pip first.
FWIW, Ubuntu 12.04 is currently responsible for 2.5% of our PyPi installs (thx @dstufft!):
`null` means PyPi doesn't have that data available because of the version of the installer they used didn't include it in the information they send.

remove compatible version specifiers

---

libmproxy/flow_format_compat.py
libmproxy/models/connections.py
libmproxy/models/flow.py
libmproxy/models/http.py
libmproxy/stateobject.py
libmproxy/version.py
libmproxy/web/__init__.py
libmproxy/web/app.py
test/test_flow.py
test/tutils.py

This PR introduces some changes to serialization within mitmproxy:
- Check if there are any leftover or missing attributes when restoring state and raise an exception if so. This already caught a few subtle bugs.
- Remove the `short` argument from `.get_state()`, which is replaced by `_strip_content` in mitmweb. This should not have been part of the serialization API in the first place.
- `s/load_state/set_state/`
- Simplify serialization based on the changes in mitmproxy/netlib/pull/120.
I needed to increase the version number so that the convert function corrects serialized data. This is a first attempt and simplifying libmproxy.models.http as much as possible.

Model Cleanup

---

libmproxy/models/http.py

Sending any headers at all in response to a CONNECT request breaks
proxying Android emulators on all non-80 ports.
Issue: #783

Do not send Proxy-Agent in CONNECT responses

---

libmproxy/protocol/http2.py

This may become handy when getting bug reports. Also, it may be useful to peek into internals for some users.

Print HTTP2 frames to debug log

---

netlib/netlib/http/request.py
test/netlib/http/test_request.py

Currently the path_components and query setters of the Request object
use the url setter under the hood. The url setter updates all parts of
the URL including the host. If the host header and the host in the
request URL are different (as is common when making HTTPS requests)
then the host header will be updated to the value in the URL as a
result of modifying the path.
This change fixes this problem by modifying the query and
path_components setters to not use the url setter and instead directly
update the path field.

Preserve host header when modifying request path

---

mitmproxy/mitmproxy/console/flowview.py
mitmproxy/mitmproxy/contentviews.py
test/mitmproxy/test_contentview.py

The query content view uses format_dict to display a table of query
parameters and is made the default content view for requests with
query parameters and no request body.
To facilitate this the query parameter dictionary of HTTPRequests is
added to the metadata content view parameter under the "query" key.
Additionally, the logic for handling "no content" messages is moved
from contentviews.get_content_view to ViewAuto. This is necessary as
it allows the query content view to be displayed when there is no
request body.

Add a content view for query parameters

---

README.rst
issue_template.md

I think the current version is a bit too verbose. Also, stuff like "run `import OpenSSL; print(OpenSSL.__version__)` in Python" etc. may be confusing to users that just take the binary.
@Kriechi, is that ok for you?

Simplify Issue Template

---

web/gulpfile.js

Gulp eats errors from watchify, which makes `scripts-app-dev` never finish when start up gulp with an error script.

[web] gulp: log errors from buildScript/bundle

---

web/package.json
web/src/js/tests/utils.js

Eslint complains about it all the time:
```
Parsing error: 'import' and 'export' may only appear at the top level
```
Anyway, I found our tests are completely broken. I think we should remove it now and add them sometime later :confused:

[web] Fix eslint warnings about tests

---

examples/har_extractor.py
test/mitmproxy/data/har_extractor.har
test/mitmproxy/test_har_extractor.py

Fixes #987.
I've got the `har_extractor` script to run :smile:
I just ran `mitmdump -n -r small_dumpfile -s "examples/har_extractor.py /tmp/out.har"` and kept on fixing errors that came up but I am not too sure about the script right now!
There's room for a lot of improvements (maybe not in this same PR):
~~- [ ] Test with real world stuff~~
@colemickens maybe you could test this out with your set of flows?
~~- [ ] Add some usage documentation~~
I had to look here and there to figure out that har_extractor works with mitmdump & not mitmproxy (is that really true though?)

Improve HAR Extractor Script

---

mitmproxy/web/static/app.js
web/src/js/components/common.js
web/src/js/components/editor.js
web/src/js/components/header.js
web/src/js/components/prompt.js
web/src/js/components/proxyapp.js

This PR eliminates `common.ChildFocus` mixin by extracting `returnFocus` method to `ProxyAppMain` component.

[web] remove common.ChildFocus

---

mitmproxy/web/static/app.js
web/src/js/components/common.js
web/src/js/components/mainview.js

Use `props.routeParams` instead of `this.getParams()`. I prefer to remove react-router and use history directly though. :confused:

[web] eliminate common.Router.getParams

---

release/specs/mitmdump.spec
release/specs/mitmproxy.spec
release/specs/mitmweb.spec
release/specs/pathoc.spec
release/specs/pathod.spec

The executables created earlier used the default PyInstaller icon.
Now, the mitmproxy icon is used.

Add mitmproxy icon for binaries

---

mitmproxy/console/flowdetailview.py
mitmproxy/flow_format_compat.py
mitmproxy/models/connections.py
netlib/tcp.py
test/mitmproxy/tutils.py

It's useful to know the peer address when the domain has several IP addresses and you need to know where the request has gone.

add resolved IP address in "Details" tab

---

mitmproxy/cmdline.py
mitmproxy/protocol/tls.py
mitmproxy/proxy/config.py
netlib/tcp.py
pathod/pathoc.py
test/mitmproxy/test_server.py
test/mitmproxy/tservers.py

If enabled, append all server certificates to the certificate chain
served to the client, as extras. Can be used to test/bypass certain
certificate pinning impementations.

New option: Add server certs to client chain

---

.appveyor.yml
.travis.yml
setup.cfg

I'd like to remove the coverage collection by default. I frequently use `py.test`'s looponfail mode, which has cluttered output and slow performance due to this.

py.test: disable coverage collection by default

---

docs/features/responsestreaming.rst
mitmproxy/console/common.py
mitmproxy/console/flowview.py
mitmproxy/dump.py
mitmproxy/flow.py
mitmproxy/models/http.py
mitmproxy/protocol/http.py
mitmproxy/web/app.py
netlib/http/__init__.py
netlib/http/http1/assemble.py
netlib/http/message.py
test/mitmproxy/test_dump.py
test/mitmproxy/test_flow.py
test/mitmproxy/test_server.py
test/netlib/http/http1/test_assemble.py

fixes #963
As @mhils said, I did this in two step:
The relative comments and document have been updated too, hope I didn't miss anything.

Simplify '.content' by removing CONTENT_MISSING

---

mitmproxy/models/http.py

The make_error_response method does not properly escape characters
that end up in the response body. Since the error code can contain
user supplied values this leads to a potential XSS vulnerability.
Example:
echo '<script>alert(1)</script>' | nc localhost 8888

Fix XSS vulnerability in HTTP errors

---

examples/har_extractor.py
mitmproxy/models/flow.py
netlib/http/response.py
pathod/pathoc.py
test/netlib/http/http2/test_connections.py

This PR replaces all (already deprecated) occurences of `Response.msg` with `Response.reason`.

response.msg -> response.reason

---

mitmproxy/models/http.py
mitmproxy/protocol/http.py
mitmproxy/protocol/http1.py
mitmproxy/protocol/http2.py
mitmproxy/protocol/http_replay.py
netlib/http/http2/connections.py
netlib/http/request.py
test/mitmproxy/test_server.py
test/netlib/http/http2/test_connections.py

This PR replaces all (already deprecated) occurences of `Request.form_(in|out)` with `Request.first_line_format`.

form_(in|out) -> first_line_format

---

mitmproxy/models/http.py
netlib/http/cookies.py
netlib/http/response.py
test/mitmproxy/test_flow.py
test/netlib/http/test_cookies.py
test/netlib/http/test_response.py

This PR moves `HTTPResponse.refresh` into netlib.

move HTTPResponse.refresh into netlib

---

mitmproxy/models/http.py
mitmproxy/utils.py
netlib/http/headers.py
netlib/http/message.py
netlib/http/request.py
netlib/odict.py
netlib/utils.py
test/mitmproxy/test_utils.py
test/netlib/http/test_headers.py
test/netlib/test_utils.py

This PR improves header replacement and moves `.replace()` into netlib.

Better .replace()

---

mitmproxy/console/common.py

On Ubuntu 15.10 and Python 2 with PyGTK, when exporting a large amount of binary data (with the E shortcut), `pyperclip` will fail with a `Gtk.Clipboard.set_text() must be string without null bytes, not str`.
The failure then proceeds to crash mitmproxy, losing your session. This patch allows us to recover from this.

Fix being unable to export binary data in requests

---

mitmproxy/console/__init__.py
mitmproxy/controller.py
mitmproxy/dump.py
mitmproxy/exceptions.py
mitmproxy/flow.py
mitmproxy/models/flow.py
mitmproxy/protocol/__init__.py
mitmproxy/protocol/base.py
mitmproxy/protocol/http.py
mitmproxy/protocol/http_replay.py
mitmproxy/proxy/server.py
mitmproxy/web/__init__.py
test/mitmproxy/test_controller.py
test/mitmproxy/test_flow.py
test/mitmproxy/test_proxy.py
test/mitmproxy/test_server.py

This PR refactors `controller.Master` into `controller.Master` and `controller.ServerMaster` and cleans up a couple of inconsistencies. Also, `Channel` now raises a `Kill` exception when the server shuts down, which fixes #907.
@Kriechi: How understandable is `mitmproxy.controller` now? My primary focus was to make this more readable, did I succeed at least a bit? (You'd need to look at the file probably, the diff is fairly broken)

cleanup mitmproxy.controller, raise Kill in Channel

---

mitmproxy/flow.py
test/mitmproxy/test_flow.py

This patch adds support for using multiple cookies set by the same server, when using stickycookies.
The original code only remembered the last cookie set.
Testcase through: mitmdump -t "."
visit https://httpbin.org/cookies/set?helloWWW=worldZZZ&xxx=yyy
then flush cookies from your browser
and finally visit https://httpbin.org/cookies

support for setting/sending multiple cookies

---

mitmproxy/console/__init__.py
mitmproxy/console/grideditor.py
mitmproxy/dump.py
mitmproxy/exceptions.py
mitmproxy/flow.py
mitmproxy/script/script.py
test/mitmproxy/test_examples.py
test/mitmproxy/test_flow.py
test/mitmproxy/test_server.py

This PR improves mitmproxy's script loading:
- Return an error string in Python is an anti pattern. In particular, we swallowed errors regarding script loading in the mitmproxy UI when loading scripts.
- Add traceback to script exceptions. That greatly helps with debugging.

Improve script loading

---

mitmproxy/console/flowview.py
mitmproxy/flow.py
netlib/http/cookies.py
netlib/http/request.py
netlib/http/response.py
test/mitmproxy/test_flow.py
test/netlib/http/test_cookies.py
test/netlib/http/test_request.py
test/netlib/http/test_response.py

allows `/` to be within a cookie name, e.g. `_csrf/link=foobar`
backport: `:` character to be within a cookie name from python 3.3
removes deprecated cookie getter/setter
fixes #1118 
This introduces a minor API change for sticky cookies.

improve cookie parsing

---

examples/README
examples/fail_with_500.py

I love using mitmproxy to easily reproduce network failures against API's.  I think this example will help raise awareness of how easy it can be to use mitmproxy in this way.

Adding example which turns every reponse into an HTTP 500.

---

mitmproxy/web/__init__.py

Nothing major, just makes it a bit easier for opening it up in the browser.

Send URL to stderr when starting mitmweb

---

netlib/odict.py
test/netlib/test_odict.py

This PR removes the unused `ODict.in_any` and generally cleans up the ODict code.

clean up odict

---

mitmproxy/protocol/base.py
mitmproxy/protocol/http.py
mitmproxy/protocol/tls.py
mitmproxy/proxy/root_context.py

This is an experimental PR that speeds up mitmproxy's TLS handshake. The assumption is as follows: If the client sends a SNI value in the handshake, we can be reasonably sure that this is actually the server the client is requesting. Thus, we can just mirror the SNI value in the cert and don't need to an upstream connection.
I really don't see a case where this could be failing. @cortesi, any concerns with this? If we all agree that this should be implemented, I'll adjust the tests.

Speed up TLS handshake if SNI is present

---

mitmproxy/protocol/http2.py
netlib/http/http2/connections.py
netlib/multidict.py
test/netlib/http/http2/test_connections.py

- The canonical source for :method, :scheme and :path are the .method, .scheme
and .path attributes on the request object.
- These pseudo-headers are stripped after reading the request, and re-inserted
just before sending.
- The :authority header remains, and should be handled analagously to the Host
header in HTTP1 with respect to display and user interaction.

Improve handling of HTTP2 pseudo-headers

---

mitmproxy/console/__init__.py
mitmproxy/console/flowlist.py
mitmproxy/console/statusbar.py

Hi All, I've been using this capability a bit when wrangling a bit of traffic in mitmproxy. It's not implemented as a filter, as the 'marking' of flows is handled in the ConsoleState. The 'M' command will quickly change the view to either marked flows or not. If there was an existing filter in place, this will be temporarily stored, and then replaced.
I'm unsure if this is the 'best' way to do this (don't hack much in Python), but it seems to be working for me fine.

implement a toggle for viewing marked flows only in console

---

netlib/multidict.py
test/netlib/test_multidict.py

Fixes #1214
Some servers don't fully respect RFC 2616 (Headers should be case-insensitive). This makes it so that the capitalization of the header fields stay the same, even if (for example) the `Content-Length` changes.

Now keeps header capitalization

---

netlib/debug.py
test/netlib/test_debug.py

`signal.SIGUSR1` is undefined on Windows. The test probably has terrible side effects, but better than not detecting errors.

Fix Debug Mode on Windows

---

examples/har_extractor.py
test/mitmproxy/data/har_extractor.har

HAR files were failing to load in harviewer (http://www.softwareishard.com/har/viewer/) due to:
- ISO 8601 dates for startedDateTime missing timezone (http://www.softwareishard.com/blog/har-12-spec/#pages)
-- Used UTC but could add detection of default system timezone if desired
- pages object missing pageTimings (http://www.softwareishard.com/blog/har-12-spec/#pageTimings)
-- Used null because all child fields are optional

Make har_extractor.py output HAR 1.2 spec-compliant

---

mitmproxy/models/__init__.py

Spotted by Landscape (thanks @Kriechi for pointing out the site).  Add a
comma to the last item too, to prevent this from happening in the future
and reduce messing up blame later.

mitmproxy/models: missed comma in __all__

---

mitmproxy/protocol/http2.py
netlib/http/http2/__init__.py
netlib/http/http2/utils.py
pathod/protocols/http2.py
test/pathod/test_protocols_http2.py

[One of the pathod tests](https://github.com/dufferzafar/mitmproxy/blob/h2-refactor/test/pathod/test_protocols_http2.py#L370-L398) is failing...

h2: move header parsing to netlib

---

examples/tcp_message.py
mitmproxy/contentviews.py
netlib/strutils.py
netlib/websockets/frame.py
pathod/log.py
test/netlib/test_strutils.py

This PR removes `strutils.clean_bin` and replaces it with the less obscure `escape_control_characters`. `escape_control_characters` does just one thing: It takes all unicode C1 control codes and replaces them with `"."`. We also had a bug in the raw display mode, where we escaped newlines and tabs, which made everything look weird. This has now been fixed by adding a `keep_spacing` parameter to `bytes_to_escaped_str`.

remove clean_bin, clarify unicode handling

---

mitmproxy/contentviews.py
test/mitmproxy/test_contentview.py

In practice, Ember.js applications support JSON API out the box, so it would be awesome if HTTP requests with a `Content-Type: application/vnd.api+json` header (as defined in the spec) are detected and parsed as JSON 😃 
IANA assignment here:
https://www.iana.org/assignments/media-types/application/vnd.api+json
More about JSON API:
https://github.com/json-api/json-api

Detect JSON API media type as a json content view

---

mitmproxy/proxy/root_context.py

An ASCII character can't be both upper case and lower case. Fixing this, otherwise --raw-tcp option will assume innermost layer is always raw TCP.

Fix is_ascii check when determining next layer

---

mitmproxy/platform/osx.py

In Python 3, subprocess.check_output() returns a sequence of bytes. This change ensures that it will be converted to a string, so the substring test for the sudo error message does not raise a TypeError. This fixes the code in Python 3 while remaining compatible with Python 2.

Make sudo pfctl error check Python 3 compatible

---

.travis.yml
mitmproxy/console/common.py
mitmproxy/console/master.py
mitmproxy/console/options.py
mitmproxy/main.py
mitmproxy/options.py
mitmproxy/web/app.py
test/mitmproxy/test_options.py

Minor addons cleanup: handle options errors on the command line, add a bit of convenience to options, and disable Travis while OSX tests are screwed up.

Addons cleanup

---

mitmproxy/console/master.py
mitmproxy/dump.py
mitmproxy/flow/__init__.py
mitmproxy/flow/options.py
mitmproxy/options.py
mitmproxy/web/master.py
test/mitmproxy/builtins/test_anticache.py
test/mitmproxy/builtins/test_anticomp.py
test/mitmproxy/builtins/test_stickyauth.py
test/mitmproxy/builtins/test_stickycookie.py
test/mitmproxy/builtins/test_stream.py
test/mitmproxy/console/test_master.py
test/mitmproxy/test_options.py
test/mitmproxy/test_web_master.py

This PR makes all options explicit arguments to the Options constructors. This should greatly improve type hinting and catching errors in general.

Make options explicit

---

mitmproxy/builtins/stickycookie.py
test/mitmproxy/builtins/test_stickycookie.py

This was originally added in #1324 (fixing issue #1096)
but got lost during "the big refactor" (#1352)

Re-add deletion of stickycookies

---

mitmproxy/console/common.py
mitmproxy/console/flowview.py
mitmproxy/dump.py
mitmproxy/filt.py
mitmproxy/flow/export.py
netlib/http/message.py
netlib/http/request.py
netlib/wsgi.py
test/netlib/http/test_message.py

@cortesi: As we discussed, this makes `.content` raise a ValueError if decoding the Content-Encoding fails instead of returning our best guess. Unfortunately, after implementing this I'm back at my opinion that we probably should not do this. `Request` is supposed to provide an API that favors simplicity, and wrapping every call to `.content` with
```
try:
content = request.content
except ValueError:
content = request.raw_content  # well, let's do a best guess...
```
really does not improve things :confused: . 
I believe we should document our graceful degradation approach, and add a proper UI indicator for mitmproxy if we ever encounter an unknown/invalid content encoding. Alternatively, I suggest we implement `get_content(strict=False)` and make `.content` a shorthand for this. Anyone …

[RFC] Raise ValueError if content-encoding is invalid

---

mitmproxy/filt.py
mitmproxy/models/tcp.py
test/mitmproxy/test_filt.py
test/mitmproxy/test_flow.py
test/mitmproxy/tutils.py

Filters that make sense for TCPFlows:
Filters that will just return `False` for TCPFlows:
Other Tasks:

TCPFlow Filters

---

mitmproxy/builtins/dumper.py
mitmproxy/controller.py
mitmproxy/dump.py
test/mitmproxy/builtins/test_dumper.py
test/mitmproxy/mastertest.py
test/mitmproxy/test_dump.py

This removes all the code that deals with printing flows to screen from dump.py
into a self-contained addon.
- This fixes a bug - by moving dumping into an
addon, we now dump flows AFTER addon transformation, so we can see the changes
made.
- We get dumping "for free" in other places by simply adding the addon. It's
now easy to add dumping to console to mitmweb for debugging and development.
The same goes for external projects that derive from master.
- We also get major benefits in clarity for a frankly hairy part of our
project. Mitmdump is much clearer, and all the hairyness is now isolated for
further refactoring.

Extract console dump functionality into an addon

---

mitmproxy/console/flowview.py
netlib/http/message.py
netlib/multidict.py
test/netlib/http/test_message.py
test/netlib/test_multidict.py

This PR fixes #1185. 
netlib.http.Message and netlib.multidict.MultiDict should not be hashable as they are mutable, so I removed that part.

Fix content view cache invalidation

---

examples/filt.py
examples/flowwriter.py
examples/iframe_injector.py
mitmproxy/builtins/script.py
test/mitmproxy/builtins/test_script.py
test/mitmproxy/data/addonscripts/addon.py
test/mitmproxy/data/addonscripts/recorder.py

- Script .start() can now return a class to handle all hooks from that point in. This is the last step in completely unifying scripts and addons, and gives us a nicer way to handle stateful data. Refactor some examples accordingly.
- Tweak change detection to make things a little better. We're never going to be completely happy with how this works unless we more or less recreate modd in mitmproxy.

Keep maturing scripts and addons

---

mitmproxy/console/flowlist.py
mitmproxy/console/flowview.py
mitmproxy/web/app.py

In a nutshell, whenever a users requests to delete a flow, we need to check if we need to kill it as well. I kept the check out of `self.flow.kill`, so that calling this in the wrong setting does not become a no-op.
@cortesi: Looks good to you?

fix #1396, fix #1205, fix #1374

---

mitmproxy/console/common.py
mitmproxy/console/flowlist.py
mitmproxy/console/master.py
mitmproxy/console/statusbar.py
mitmproxy/filt.py
mitmproxy/flow/io_compat.py
mitmproxy/models/flow.py
mitmproxy/models/http.py
mitmproxy/models/tcp.py
test/mitmproxy/test_flow.py

This tries to replace the marked flow view (activated by `M` key) with a `~marked` filter.
`marked` property in flows:
`marked` filter:
* which will just toggle view filter between `~marked` and what was before
focus flows:
save flows:

Marked property and filter

---

netlib/http/request.py
netlib/http/url.py
netlib/strutils.py
test/netlib/http/test_url.py

This PR fixes the handling of non-utf8 characters in `request.query` and `request.path_components` and adds `url.quote/url.unquote` functions. These features are required for the revised GridEditor to work.

Fix query/path_components encoding

---

mitmproxy/onboarding/app.py
mitmproxy/platform/__init__.py

Fixes two small bugs:
1. Fix platform import on Linux using python3 
```sh
$ mitmproxy -T --host
mitmproxy: Transparent mode not supported on this platform.
```
Using Python3 `sys.platform` returns `linux` instead of `linux2` (Python2). This causes the platform import to fail on python3.
2. Substitute tilde with user's home.
Delivering the cert `~/.mitmproxy/mitmproxy-ca-cert.pem` using `mitm.it` fails because the tilde is not replaced with the user's home directory.

Fix platform import, substitute "~" with user's home

---

netlib/strutils.py
pathod/language/base.py
pathod/pathoc.py
test/netlib/test_strutils.py

This fixes #1448. Without this change applied, we'd see `'` escaped as `\'` in a couple of places (especially the raw view), which might be confusing.

Add escape_single_quotes=False arg to bytes_to_escaped_str

---

mitmproxy/cmdline.py
mitmproxy/console/flowlist.py
mitmproxy/console/flowview.py
mitmproxy/console/master.py
mitmproxy/console/statusbar.py
mitmproxy/flow/state.py
mitmproxy/main.py
test/mitmproxy/console/test_master.py
test/mitmproxy/test_flow.py

Fixes #542.
Two filter view related functionalities:

Rename "Limit" feature to "Filter View"

---

mitmproxy/console/common.py

* Regarding color coding the response codes
The colors were not working in python 3. As 404/100 was coming out to be 4.04 instead of 4.

integer division for python 3 compatibility

---

mitmproxy/addons.py
mitmproxy/builtins/dumper.py
mitmproxy/console/flowview.py
mitmproxy/contentviews.py
mitmproxy/flow/master.py
netlib/http/__init__.py
test/mitmproxy/builtins/test_dumper.py
test/mitmproxy/test_contentview.py

This PR unifies the (1) "oh the contentview failed let's log an exception and just do raw mode" and (2) "let's remove the content decoding" logic we have for mitmproxy, mitmdump and (soon) mitmweb.

Simplify contentview logic

---

mitmproxy/builtins/replace.py
mitmproxy/builtins/setheaders.py
mitmproxy/console/common.py
mitmproxy/console/flowlist.py
mitmproxy/console/flowview.py
mitmproxy/console/master.py
mitmproxy/controller.py
mitmproxy/flow/master.py
mitmproxy/flow/state.py
mitmproxy/models/flow.py
mitmproxy/script/concurrent.py
mitmproxy/web/app.py
mitmproxy/web/master.py
test/mitmproxy/builtins/test_anticache.py
test/mitmproxy/builtins/test_anticomp.py
test/mitmproxy/builtins/test_dumper.py
test/mitmproxy/builtins/test_filestreamer.py
test/mitmproxy/builtins/test_replace.py
test/mitmproxy/builtins/test_script.py
test/mitmproxy/builtins/test_setheaders.py
test/mitmproxy/builtins/test_stickyauth.py
test/mitmproxy/builtins/test_stickycookie.py
test/mitmproxy/mastertest.py
test/mitmproxy/script/test_concurrent.py
test/mitmproxy/test_controller.py
test/mitmproxy/test_examples.py
test/mitmproxy/test_flow.py

This PR tries to make the semantics of controller.Reply more explicit by representing a Reply's state as a single attribute and making all unexpected state transitions raise.
Fixes #1468.

Improve controller.Reply semantics

---

mitmproxy/protocol/http.py
mitmproxy/proxy/config.py
netlib/http/authentication.py
test/mitmproxy/test_server.py

This PR makes it possible to have basic auth in reverse proxy mode:
```
mitmdump -R http://example.com --singleuser foo:bar
```

Add basic auth support for reverse proxy mode

---

mitmproxy/console/common.py
mitmproxy/console/flowlist.py
mitmproxy/console/flowview.py

An attempt to fix #1485
Currently, URLs are shortened in the `flowlist`, but are displayed as-is in the `flowview`. 
I'd actually prefer to shorten them in both the views, but then we need to come up with a way to view the full URL.
It could be via an option in the UI like we have `Show Host` or a hotkey that toggles the behaviour in both the views.

Truncate URLs in console

---

examples/flowbasic
mitmproxy/protocol/http.py

- Don't log a traceback for either HTTP or HTTPS DNS resolution or TCP
connection errors. These are "ordinary" errors, not mitmproxy issues.
- Ensure that the error handler is correctly called for SSL-related protocol
errors.

Improve the way we handle upstream errors

---

docs/howmitmproxy.rst
docs/introduction.rst

fixes #859
use TLS instead of SSL when revering to HTTPS encryption

update docs: how mitmproxy works

---

netlib/encoding.py
test/netlib/test_encoding.py

```
In [7]: encoding.decode('', 'none')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-a83dfad39aec> in <module>()
----> 1 encoding.decode('', 'none')
/home/ames/dev/mitmproxy/netlib/encoding.pyc in decode(encoded, encoding, errors)
54             type(e).__name__,
55             repr(encoded)[:10],
---> 56             repr(encoding),
57         ))
58 
ValueError: LookupError when decoding '' with 'none'
```
Return the same value.
I encountered a website that sent a content-encoding header of 'none', which `netlib.encoding` doesn't seem to be able to handle. I realize that it's an out of spec header value, but I believe it should be handled gracefully.
---
Mitmproxy …

Fix decoding when content-encoding: none

---

mitmproxy/addons.py
mitmproxy/builtins/serverplayback.py
mitmproxy/console/master.py
mitmproxy/console/statusbar.py
mitmproxy/console/window.py
mitmproxy/protocol/http_replay.py
test/mitmproxy/protocol/test_http1.py
test/mitmproxy/test_addons.py
test/mitmproxy/test_fuzzing.py
test/mitmproxy/test_server.py
test/mitmproxy/tservers.py

This extends some of the work I did for pathod and netlib to the mitmproxy test
suite. It also fixes what may be a leak in replays.
Failing on connection leak is disabled on Windows for the moment.
Fixes #1535

Roll out synchronisation for mitmproxy tests

---

mitmproxy/builtins/serverplayback.py
mitmproxy/cmdline.py
mitmproxy/console/flowlist.py
mitmproxy/console/options.py
mitmproxy/console/statusbar.py
mitmproxy/dump.py
mitmproxy/options.py
test/mitmproxy/builtins/test_serverplayback.py
test/mitmproxy/console/test_master.py
test/mitmproxy/test_dump.py

We now have so many options that we can't afford terse names any more. There's something else to keep an eye on - I think our user configuration mechanism is going to shift from configargparse to a serialization of the Options structure in the near future. At that point, clear option names will be a necessity.

Make various replay-related options clearer

---

mitmproxy/console/options.py

@cortesi renamed the kill option to replay_kill_extra in b0213a2, but
missed a usage here because it was in a string. This fixes opening the
options menu in console.

console/options: kill -> replay_kill_extra

---

mitmproxy/exceptions.py
mitmproxy/protocol/http.py
mitmproxy/proxy/server.py

This commit replaces the logging statement introduced in afe34e8b28988bdff91123862194606152c03c33 with the previous implementation where an exception is raised. ProtocolExceptions are normally logged as regular warnings, achieving the same effect for the end user. However, this retains the full stack trace for debug-level logging, which makes the analysis of client errors considerably easier.

Fix mitmdump error logging, fix #1549

---

mitmproxy/dump.py

Resolved #1505 
I think use the channel for communication between server and master is a good practice.
But I need your advise for
1. Is the notification message is OK?
2. Is override the serve_forever from TCPServer ok? Or we have some better way to do this.
Thanks!

Notify when proxy server started

---

mitmproxy/cmdline.py
mitmproxy/options.py
mitmproxy/protocol/http.py
mitmproxy/protocol/websockets.py
mitmproxy/proxy/config.py
mitmproxy/proxy/root_context.py
test/mitmproxy/protocol/test_websockets.py

@Kriechi: Can I get a quick review from you for this one?
- We now have a `--websockets/--no-websockets` switch. Off by default (like `--raw-tcp`), but there's an info log message if a client attempts a websocket connection.
- Move the websocket upgrade code into protocol/http as it is entirely HTTP specific. Before that it would have broken on non-HTTP Flows.
- Set logging verbosity of websocket data frames from debug to info (this is what #1547 was referring to, where I did not have the time to log into the code)
- Move websocket logging before calling `.send()` so that we still log if sending fails.

add websocket on/off switch, improve logging (fix #1546, fix #1547)

---

docs/features/reverseproxy.rst
mitmproxy/protocol/http.py

Follow-up to #1581 using a slightly different technique to override the header. I don't want to rely on addons for this, this should always happen.

Set Host header automatically in reverse proxy mode 

---

mitmproxy/protocol/tls.py
mitmproxy/proxy/root_context.py
test/mitmproxy/test_server.py

This fixes an SNI issue in reverse proxy mode.
1. Start a reverse proxy instance that connects to an HTTPS endpoint using SNI:
`mitmproxy -R https://www.example.com --setheader :~q:Host:www.example.com`
3. Open `https://localhost:8080/` in a web browser
mitmproxy should use the domain `www.example.com` to negotiate SNI with the server.
mitmproxy instead sends no SNI value to the server, and the request fails with the following error: `Cannot establish TLS with www.example.com:443 (sni: None): TlsException('Cannot validate certificate hostname without SNI',)`
This PR adds a `--server-sni` flag that allows you to specify an SNI value that should always be used. Thus, you can fix the original problem above by adding the new flag: `mitmproxy -R https://www.example.com --setheader …

Add command line arg to force specific SNI

---

netlib/http/cookies.py
netlib/http/response.py
test/mitmproxy/builtins/test_stickycookie.py
test/netlib/http/test_cookies.py

Support Comma Separated Cookies

---

netlib/tcp.py

I've found a fix for #1585, but I'm not sure it's complete yet, or if it might break something that I'm unaware of. I'd love some feedback as to whether this seems like a proper solution.
This fixes an issue that occurs when a user supplies a custom SSL cert w/ intermediate certs that *contradict* the default certifi set of root certificates. In particular, this addresses an issue where the "COMODO RSA Certification Authority" cert in certifi is NOT trusted on OS X by default as of OS X 10.11.6. Even when the user manually supplied a different valid "COMODO RSA Certification Authority" cert in their custom SSL cert .pem file, that cert would be overridden by certifi's default cert.
Now, when the user specifies a custom certificate, mitmproxy will load ONLY that custom certificate when …

Fix SSL error on OS X

---

docs/features/filters.rst
examples/flowfilter.py
mitmproxy/builtins/dumper.py
mitmproxy/builtins/filestreamer.py
mitmproxy/builtins/replace.py
mitmproxy/builtins/setheaders.py
mitmproxy/builtins/stickyauth.py
mitmproxy/builtins/stickycookie.py
mitmproxy/cmdline.py
mitmproxy/console/grideditor/editors.py
mitmproxy/console/help.py
mitmproxy/console/master.py
mitmproxy/flow/io.py
mitmproxy/flow/state.py
mitmproxy/flowfilter.py
mitmproxy/models/flow.py
mitmproxy/web/app.py
test/mitmproxy/test_flow.py
test/mitmproxy/test_flowfilter.py

There seems to be a bug here, which is now fixed:
https://github.com/mitmproxy/mitmproxy/blob/d068000f16cb44b7277de04ba20bd1fc62e4a956/mitmproxy/builtins/filestreamer.py#L30
Also I removed a bit of code duplication here:
https://github.com/mitmproxy/mitmproxy/pull/1587/files#diff-6aaebdf9a233f01096f39e9db9f3d091L63
Since `flow.match` will be removed, I added a `DeprecationWarning` and moved the actual function to `flowfilter.match`.

rename mitmproxy.filt -> mitmproxy.flowfilter

---

mitmproxy/dump.py
mitmproxy/flow/__init__.py
mitmproxy/flow/state.py

Most of the mitmdump memory leak turns out to be due to our leaky handling of
the state object. Since mitmdump doesn't actually use the state object, we can
replace it with a shell.

mitmdump: use a dummy state object

---

netlib/certutils.py
netlib/debug.py
test/netlib/test_certutils.py

This should be enough to give us reuse without growing infinitely. This is part of fixing the memory situation in mitmdump.
TODO: There's an opportunity here for a better algorithm, that expires certs based on least-recently-accessed time, rather than oldest generated time.

certutils: cap the cert store size at 100 by default

---

mitmproxy/contrib/tnetstring.py
mitmproxy/flow/io.py

This PR simplifies EOF handling for tnetstrings. This also allows reading Python's `zipfile.ZipExtFile`, which would previously not meet the EOF condition.

Simplify EOF detection

---

mitmproxy/builtins/dumper.py

This PR limits the URL length echoed by the dumper addon. We already do the same in the console ui, and I find it kind of useful when facing screen-filling ad tracker URLs.
Ok for everyone?

Dumper: limit url length

---

mitmproxy/addons.py
mitmproxy/builtins/wsgiapp.py
mitmproxy/console/master.py
mitmproxy/exceptions.py
mitmproxy/web/master.py

This can be raised from an addon handler to stop further processing of a flow.
Use this to prevent further handling of web app requests.

addons: add AddonHalt exception

---

examples/flowfilter.py

**Issue**
The flowfilter example does not work.
**Root cause**
The `flowfilter.match()` positional arguments are in the wrong order. See method definition here.
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/flowfilter.py#L502
**Fix**
The first argument should be the `filter`, then the `flow`.
Follow up to https://github.com/mitmproxy/mitmproxy/pull/1587/commits/36c04f1631c79ca79712873e151c7f5267cafd46

Fix method call in flowfilter example

---

mitmproxy/flow.py
mitmproxy/tools/console/flowview.py
test/mitmproxy/test_flow.py

This is now the error handler on master, so whatever the intention was it's now
definitely wrong.
This fixes a crash when intercepted flows are deleted from console (among others).

Don't call error for flow kill

---

mitmproxy/tools/main.py

This adresses https://github.com/mitmproxy/mitmproxy/issues/1646#issuecomment-255503746. There are a couple of subtle issues:
1. We need to do the check before the mitmproxy/mitmdump/mitmweb functions, because some Python files are now invalid syntax for Python 2.
1. We ideally don't want a mere module import cause side effects. However, mitmproxy is downright incompatible with 3.4-, so we surely want to do _something_. Instead of `sys.exit()`ing, we just print to stderr. The current behaviour is as follows:
Python 3.4:
```
C:\Users\user>C:\Python34\Scripts\mitmdump.exe
#################################################
#################################################
File "C:\Python34\Scripts\mitmdump-script.py", line 9, in <module> …
```

Add version check for Python 3.4-

---

examples/har_dump.py

Currently, full mimeType is included only in `content-type` request header. While the HAR spec is not very explicit and their example shows just this one example: 
```js
"postData": {
"mimeType": "multipart/form-data"
//...
}
```
Would it not make sense to include all the information necessary to parse out the post data `text`. Eg.
```json
"postData": {
"mimeType": "multipart/form-data; boundary=xYzZY",
"text": "--xYzZY\r\nContent-Disposition: form-data; name=\"sort1\"\r\n\r\noldest date first\r\n--xYzZY--\r\n"
},
```
Note that elsewhere in HAR spec they include the extra parameters, eg:
```js
"content": {
"mimeType": "text/html; charset=utf-8",
// ...
}
``` 
So one could argue that `postData.mimeType` should also include all information necessary to interpret the `text`. In case of …

Include `boudary=...` in mutipart postData

---

mitmproxy/export.py
mitmproxy/http.py
test/mitmproxy/data/test_flow_export/python_get.py
test/mitmproxy/data/test_flow_export/python_patch.py
test/mitmproxy/data/test_flow_export/python_post.py
test/mitmproxy/data/test_flow_export/python_post_json.py
test/mitmproxy/test_flow_export.py

This PR reduces the Python code verbosity in particular, e.g. by using requests' `requests.post` shorthand instead of `requests.request(method="POST", ...`.
This also fixes #1573.

Improve Flow Export

---

mitmproxy/connections.py
mitmproxy/io_compat.py
mitmproxy/tools/console/flowdetailview.py
test/mitmproxy/tutils.py

There is still one test cannot pass that I need your advise how could I solved that.
The test is ```test/mitmproxy/test_flow_format_compat.py``` that will load a dump file ```data/dumpfile-011```
The dumpfile didn't contains sni info so that when the program try deserialize from dumpfile,
the state of ClientConnection didn't contains the sni field.
Is that I need add sni in the dumpfile manually? Or there is another way?
Thanks!
```
def test_load():
with open(tutils.test_data.path("data/dumpfile-011"), "rb") as f:
flow_reader = io.FlowReader(f)
>           flows = list(flow_reader.stream())
test/mitmproxy/test_flow_format_compat.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```

Resolved #1639: display sni on ClientConnection

---

mitmproxy/options.py
mitmproxy/tools/console/master.py
mitmproxy/tools/dump.py
mitmproxy/tools/web/master.py

If noone objects, I would like to make our option classes keyword-only as proposed in [PEP 3102](https://www.python.org/dev/peps/pep-3102/):  Arguments can only be supplied by keyword and not as a positional argument.

Make Options keyword-only

---

mitmproxy/addons/dumper.py
mitmproxy/flow.py
mitmproxy/io_compat.py
mitmproxy/proxy/protocol/http.py
mitmproxy/proxy/protocol/http1.py
mitmproxy/proxy/protocol/http2.py
mitmproxy/tools/console/common.py

This PR adds an indicator to mitmproxy and mitmdump to indicate pushed streams.
To keep track of this information, the `HTTPLayer` now gets to keep track of its own `flow` as attribute.
Furthermore, this PR introduces a `flow.metadata` dict, which can be used to store additional information about flows.
This might be useful for scripts/addons to store external data:
* correlating SQL query times from an external DB system
* computed statistics
* a GUID to keep track of each flow
* etc.

http2: add an indicator for pushed streams

---

mitmproxy/addons/wsgiapp.py

Currently, mitmproxy always raises an exception when serving a wsgiapp even if everything worked as expected. This patch causes mitmproxy to only raise an exception if an error actually occurred.

Wsgiapp: Only raise exception if an error occurred.

---

test/mitmproxy/net/test_tcp.py
tox.ini

Add a bit of contextual info to our test runs to try to troubleshoot the SSL-related failures.

Fix Travis cipher-suite related breakage

---

docs/pathod/test.rst

Fix Nose link in pathod test documentation.
Current: http://docs.mitmproxy.org/en/stable/pathod/test.html
Fixed: http://imgur.com/a/aRDZS

[MINOR] fix link in documentation

---

mitmproxy/http.py

- they're unused
- if we want them, they should be set by the addon in the new metadata store

Remove sticky[auth,cookie] from http objects

---

examples/sslstrip.py

In transparent mode host is set with the target server ip.
Attribute flow.request.host is used as SNI while mitmproxy is
initiating TLS handshake, so it should be set with the pretty_host.

fix SNI for transparent mode - #1638

---

mitmproxy/addons/view.py
mitmproxy/tools/console/flowlist.py
mitmproxy/tools/web/master.py
test/mitmproxy/addons/test_view.py

This adds a set of store modification events, and uses them for flow settings.
This addresses a bug where settings could persist even after flows were deleted.

addons.view: clarify modification events

---

mitmproxy/cmdline.py
mitmproxy/options.py
mitmproxy/protocol/base.py

Exempt localhost from upstream binding introduced in #879

---

mitmproxy/addons/onboardingapp/templates/index.html

Ideally somebody would contribute installation instructions for other systems as well.
Maybe even make it fancy by only showing the correct block after clicking the icon...

add macOS/OSX installation instructions to onboarding page

---

mitmproxy/options.py
mitmproxy/proxy/protocol/base.py
mitmproxy/tools/cmdline.py

This forward ports the changes in #1735 to master, and makes the upstream bind address its own option entirely.  I'm going to build on this to allow combining upstream bind address and spoof source address options to spoof a fixed source address for all clients in another PR.

Make the upstream bind address a separate option

---

examples/dup_and_replay.py

It seems that `run_scripthooks` is dead, so this should fix this example.

Remove dead run_scripthooks example reference.

---

mitmproxy/proxy/protocol/base.py
mitmproxy/tools/cmdline.py

Allow combining --spoof-source-address and --upstream-bind-address to
spoof a fixed source address.  Also update the help text for
--spoof-source-address to indicate this new possibility.

proxy/protocol/base: Allow spoofing fixed source

---

mitmproxy/tools/console/master.py

Added a SIGINT handler to mitmproxy to catch CTRL-C key combinations and prompt the user to confirm that he indeed wants to quit. It will prevent accidentally closing down mitmproxy when using CTRL-C.
**Motivation**
For example, if you are viewing a flow and click on  `e` to edit it, but then actually reconsider and don't want to edit it after all, instinctively I would hit CTRL-C to cancel the current command. But this kills the whole process and I lose all the work I have done, which is quite frustrating.

handle SIGINT with a quit prompt

---

mitmproxy/platform/__init__.py
mitmproxy/platform/linux.py
mitmproxy/platform/osx.py
mitmproxy/platform/windows.py
mitmproxy/proxy/modes/transparent_proxy.py
mitmproxy/proxy/server.py
mitmproxy/tools/cmdline.py
test/mitmproxy/test_proxy.py
test/mitmproxy/test_server.py
test/mitmproxy/tservers.py

On Windows, we need to initialize pydivert when running in transparent mode.
Previously this was a chicken egg problem: initialization was done on
the first request, but requests would not be redirected to the proxy without
initialization.

Fix transparent mode initialisation, refactor mitmproxy.platform

---

mitmproxy/net/tcp.py
setup.py

This is already included in Python 3.5+

remove backport.ssl_match_hostname

---

setup.py

Since lint is in our control, we can bump the minimum version requirement freely.

bump dependencies

---

mitmproxy/tools/cmdline.py

As long as major HTTP/2 implementers fail to implement the spec correctly, we need to disable HTTP/2 by default. We expect this to be fixed with the next release and re-enabled by default.
refs https://github.com/mitmproxy/mitmproxy/issues/1745
refs https://github.com/mitmproxy/mitmproxy/issues/1824

Disable HTTP/2 by default, add explicit on/off switches

---

mitmproxy/utils/typecheck.py
test/mitmproxy/utils/test_typecheck.py

This should fix #1894. Checking `sys.version_info` is a bit flaky as (if I interpret the reports correctly) one can still install the typing module from pypi on older versions.

Fix compat with Python 3.5.0

---

mitmproxy/net/check.py
test/mitmproxy/net/test_check.py

Resolved #1529 
Update the regular expression to allow underscore in hostname.
The user-visible traceback mentioned at the issue seems to be fixed.
Though underscore is not recommended be part of hostname,
not sure that to display some warning message about it will help or make it better?

Allow underscore in hostname

---

mitmproxy/tools/console/grideditor/editors.py

Resolved #1901 
Encode the url encoded form before display it.
If there is any problem, please kindly let me know, thanks!

Encode urlencoded_form items when editing

---

mitmproxy/addons/dumper.py
test/mitmproxy/addons/test_dumper.py

Done with reference to #1623. Controls the length of URL displayed using the `-d` or `flow_detail` option. The full length URL is displayed if `flow_detail > 0`, else it is shortened.
Also uses the terminal width obtained from `click.get_terminal_size()` to determine the cutoff length.

Controls the length of URL displayed using the -d option

---

docs/features/serverreplay.rst

I have added some notes to serverreplay.rst as discussed in the forum topic https://discourse.mitmproxy.org/t/how-to-replay-requests-that-were-recorded-in-reverse-proxy-mode/292/2. Please revise and feel free to correct any style or imprecision in the explanation.

Added note about server-side replay for sessions recorded in reverse-proxy mode

---

mitmproxy/master.py

See https://docs.python.org/3/library/sys.html#sys.stdin:
> To write or read binary data from/to the standard streams, use the underlying binary buffer object. For example, to write bytes to stdout, use sys.stdout.buffer.write(b'abc').
However, if you are writing a library (and do not control in which context its code will be executed), be aware that the standard streams may be replaced with file-like objects like io.StringIO which do not support the buffer attribute.

mitmdump: fix reading from stdin

---

docs/transparent.rst

The rendered code snippets would be rewrapped as if it were prose, which wreaks havoc with the code.

reSt verbatim formatting error

---

mitmproxy/tools/console/flowdetailview.py

We currently don't display the request/response HTTP version in `raw_format_flow` (this is used in the flow list and the flow view header) unless it's HTTP/2.0. We should expose what has been sent by client and server somewhere. This would naturally go in the request or response view, but there's no really good place for that, unless we want to extend `raw_format_flow` to be more verbose in the flow view. This adds it to the Detail view instead... @mitmproxy/devs, what do you think?

console: display http version in details

---

test/mitmproxy/addons/test_serverplayback.py
test/mitmproxy/addons/test_stickyauth.py
test/mitmproxy/addons/test_stickycookie.py
test/mitmproxy/addons/test_streamfile.py
test/mitmproxy/addons/test_view.py

This patch pushes the coverage of ./tests/mitproxy/addons to 100% of the addons
module.

addons: unit tests to 100%

---

mitmproxy/addons/__init__.py
mitmproxy/addons/replace.py
mitmproxy/options.py
mitmproxy/tools/cmdline.py
mitmproxy/tools/console/options.py
test/mitmproxy/addons/test_replace.py
test/mitmproxy/test_cmdline.py

- Replacement specifiers can be either strings or tuples. This lets us cope
gracefully with command-line parsing (and posible quick interactive
specification) without having to special-case replacement hooks, or have
knowledge of hook specification leak outside the addon. We can also now use the
same command-line spec format in config files.
- Split replacement and replacement from file into separate addons and options.
Files are now read on each replacement, so you can edit replacement files in
place without restart.
- Modernise the test suite to use addon test helpers.
TODO: editing and displaying replace-from-file in console app

Revamp replacement hooks

---

mitmproxy/addons/setheaders.py
mitmproxy/options.py
mitmproxy/tools/cmdline.py
mitmproxy/tools/console/options.py
test/mitmproxy/addons/test_setheaders.py
test/mitmproxy/test_cmdline.py

As per replacements:
- Make the option type a string/tuple union
- Localise parsing strictly within the addon
- Adapt the console editor (we'll find a more elegant solution later)

Regularise setheaders options

---

examples/complex/dns_spoofing.py
test/mitmproxy/test_examples.py

Hi,
The `dns_spoofing.py` example works for HTTPS connections but not for HTTP. The original Host header can not be retrieved from `flow.request.pretty_host` in the `request` event.
Here is a new version of the example based on the solution suggested by @mhils in [this forum thread](https://discourse.mitmproxy.org/t/could-mitmproxy-be-used-for-reverse-proxy-for-multi-sites/253/6).

Fix for dns_spoofing.py example

---

mitmproxy/addons/script.py
mitmproxy/tools/console/master.py
test/mitmproxy/addons/test_script.py
test/mitmproxy/console/test_master.py

Done in reference to #1909 Add an except clause in `run_once` function when calling the `Script` class constructor. Returning an empty `Script` object seems more of a hassle than returning `None`, given that the returned object is never used.

Add except clause to catch script parsing errors

---

.appveyor.yml
.gitignore
.travis.yml
mitmproxy/net/http/http2/framereader.py
mitmproxy/net/http/http2/utils.py
mitmproxy/utils/debug.py
mitmproxy/utils/typecheck.py
pathod/protocols/websockets.py
test/conftest.py
test/mitmproxy/addons/test_view.py
test/mitmproxy/net/http/http2/test_framereader.py
test/mitmproxy/net/http/http2/test_utils.py
test/mitmproxy/script/test_concurrent.py
test/mitmproxy/utils/test_debug.py
test/mitmproxy/utils/test_typecheck.py
tox.ini

This PR adds a custom pytest plugin using the hooks API.
New CLI parameter are available: `--full-cov=[path]` and `--no-full-cov=[file]`.
This makes pytest fail with an exitcode if the coverage for one or more file paths is less than 100%.
The plan is to slowly increase coverage for the mitmproxy core and add more and more paths until we can just say: `--full-cov=mitmproxy` which protects everything against dropping coverage metrics.

add test coverage protection

---

mitmproxy/proxy/protocol/http.py
test/mitmproxy/protocol/test_http1.py

Checks if mode is transparent and request is of authority or absolute form and gives the message accordingly. I tried to find out the best way to check if an explicit proxy is actually set or not but couldn't find anything.  
One thing which I noticed though was, when I did 
`curl -i -v -x localhost:8080 example.com`
`Proxy-Connection: Keep-Alive` header was being sent 
If you want I can check for that instead of just checking whether mode is transparent or not or check for both
Change in line 129 because:
http://stackoverflow.com/a/3511300

Closes #1580 Gives warning when explicit proxy configured in transparent mode

---

web/src/js/components/ContentView/ContentViewOptions.jsx
web/src/js/components/ContentView/ViewSelector.jsx
web/src/js/ducks/ui/flow.js

there is a bug with the "show full content" button. if you activate the edit mode, the whole content is visible in the code editor, but if you switch between the tab (response, request,...) then the redux state will change to showFullContent=false.
the second commit removes the content  view selector, because if you modify a content without saving it you cannot use the server side content views correctly.

Content views edit

---

mitmproxy/tools/console/master.py

I caught a crash when I was viewing the issue list on github with mitmproxy on.
```python
File "/home/matthew/Hack/mitmproxy/mitmproxy/tools/console/master.py", line 281, in run
self.loop.run()
File "/home/matthew/Hack/mitmproxy/venv3.5/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
self._run()
File "/home/matthew/Hack/mitmproxy/venv3.5/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
self.event_loop.run()
File "/home/matthew/Hack/mitmproxy/venv3.5/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
self._loop()
File "/home/matthew/Hack/mitmproxy/venv3.5/lib/python3.5/site-packages/urwid/main_loop.py", line 715, in _loop
alarm_callback()
File "/home/matthew/Hack/mitmproxy/venv3.5/lib/python3.5/site-packag …
```

fix websocket message display crash in console.

---

mitmproxy/net/http/request.py
mitmproxy/net/http/url.py
test/mitmproxy/net/http/test_url.py

Handles corner case discussed in issue [#1946](https://github.com/mitmproxy/mitmproxy/issues/1946)
Only considers requests (no responses)
Works for "https://www.facebook.com/ajax/updatestatus.php"

Use existing urlencoding conventions when re-encoding edited form #1946

---

examples/complex/dns_spoofing.py
mitmproxy/export.py
mitmproxy/net/http/http1/assemble.py
mitmproxy/net/http/request.py
mitmproxy/proxy/protocol/http.py
test/mitmproxy/net/http/test_request.py

This PR introduces `request.host_header`, which transparently maps between "Host" and ":authority" headers.
fixes #2034
fixes #2036
closes #1791

Add "Request.host_header"

---

mitmproxy/utils/debug.py
test/mitmproxy/utils/test_debug.py

I added "Precompiled Binary" along with the Mitmproxy version line, so the new output for binary uses will be:
```
$ mitmproxy --version
Mitmproxy version: 2.0.0 (1.0.1dev0199-0x4cec88fc) Precompiled Binary
Python version: 3.6.0
Platform: Linux-4.8.13-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Linux distro: arch
```
This closes #2033. Please let me know if any changes are required.

Adds PyInstaller build indicator to --version argument

---

mitmproxy/tools/console/flowlist.py
test/mitmproxy/console/test_flowlist.py

#1975 had to delete the previous branch
Catch ValueErrors from calls to mitmproxy.net.http.url.parse(). Otherwise mitmproxy crashes due to uncaught exception.

Catch ValueErrors from url.parse()

---

mitmproxy/script/concurrent.py
test/mitmproxy/data/addonscripts/concurrent_decorator_class.py
test/mitmproxy/script/test_concurrent.py

Fixes #1928, I wrote a simple script to test how should we fix this:
```python
import time
from mitmproxy.script import concurrent
class ConcurrentClass:
@concurrent  # Remove this and see what happens
def request(flow):
print("handle request: %s%s" % (flow.request.host, flow.request.path))
time.sleep(5)
print("start  request: %s%s" % (flow.request.host, flow.request.path))
def start():
return ConcurrentClass()
```
If we load this script and request a web page, it will throw something like "take one positional argument but two were given", it seems that the method in the class accept a hidden parameter `self`. The first things came out of my head is adding a decorator `@staticmethod` for the methods, but that's not neat enough and also increase the burden of script developers.
Then I call …

Fix #1928, @concurrent decorator in class

---

mitmproxy/proxy/protocol/http2.py

This might have prevented https://github.com/mitmproxy/mitmproxy/pull/2034.

http2: normalize headers before sending

---

examples/complex/har_dump.py
setup.py

Removes pytz from har_dump script.
Also, this uses utcfromtimestamp 
https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/har_dump.py#L92
whereas this uses fromtimestamp
https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/har_dump.py#L201
both of these were being passed to the same function which then set the tzinfo to UTC. I think both should have been utcfromtimestamp. 
In the fix both the times give UTC date time

Remove pytz in hardump

---

mitmproxy/tools/console/palettepicker.py

Added 'console_' prefix to mitmproxy/tools/console/palettepicker.py to fix #2068.

Added console_ prefix to options in palettepicker to resolve issue #2068

---

mitmproxy/tools/web/app.py

Fix #2071 which cause a crush when visiting any website in https with mitmweb.

[web] Fix #2071, remove client_connect.mitmcert when dumping flow into json.

---

docs/certinstall.rst

the old link doesnt lead anywhere. i replaced it with a link to an answer on stackoverflow which helped me import the mitmproxy-certificate to chrome
ps: i'm not sure if the new link also applies to chrome on other operating systems? i guess it's the same for all...?

link to stackoverflow for chrome certificate management

---

docs/features/reverseproxy.rst
examples/complex/dns_spoofing.py
mitmproxy/options.py
mitmproxy/proxy/protocol/http.py
mitmproxy/tools/cmdline.py
test/mitmproxy/proxy/test_server.py
test/mitmproxy/test_examples.py

As per the discussion in [#2034](https://github.com/mitmproxy/mitmproxy/pull/2034#issuecomment-280770573) (closed) and #2039 issue, this adds a `--keep-host-header` option to avoid auto header rewrite. 
fixes #2039

Adds --keep-host-header option (#2039)

---

mitmproxy/proxy/protocol/http.py

Hi,
This allows scripts to handle HTTPException exceptions such as "HTTP Body too large" raised in [mitmproxy/net/http/http1/read.py:131](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/http/http1/read.py#L131).
This simply follows how ProtocolException exceptions are [handled](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/protocol/http.py#L212).
It also marks the flow with the error [as is done elsewhere](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/protocol/http.py#L211).
I would like to handle errors like this and I couldn't see any other way. If this commit makes sense to you and doesn't break anything I would like to get it merged in. 
I'd be happy to add a test if someone could help suggest where it should go and maybe …

Call error handler and mark flow on HTTPException

---

web/src/css/flowdetail.less

This fix the scroll bus when viewing flow details in Firefox. Works for me in both Firefox and Chrome.

[web] fix scroll bug in flow detail. (#2083)

---

web/src/css/header.less
web/src/js/components/Header/FilterDocs.jsx
web/src/js/components/Header/FilterInput.jsx

This PR makes the FilterInput box more user-friendly. Originally, the popover will appear when you click the FilterInput box, but you could not select the filter item by mouse, you have to type into the box. 
I make the item in the popover click-able, and the selected filter will appear in the input box.

[web] Add mouse support for FilterInput popover.

---

.travis.yml

Adding our Javascript tests as a seperated matrix item to Travis CI, set `allow_failures` for now. 
The test result is look like this: [https://travis-ci.org/MatthewShao/mitmproxy/jobs/208819088](https://travis-ci.org/MatthewShao/mitmproxy/jobs/208819088)

Add Javascript tests to Travis CI. (#2093)

---

docs/pathod/language.rst

I don't think the colon belongs there. Can I get a sanity review from someone?

pathoc: fix documentation for headers

---

mitmproxy/addons/proxyauth.py
test/mitmproxy/addons/test_proxyauth.py

Fixes #2111 
Add `proxyauth` metadata to previously authenticated connections

Update proxyauth.py to add proxyauth metadata

---

.travis.yml
web/src/js/__tests__/ducks/flowsSpec.js
web/src/js/__tests__/ducks/ui/flowSpec.js
web/src/js/ducks/ui/flow.js

This PR include two modifications:
1. I found the `updatFlow` action was out of dated, we should test `stopEdit` instead, however, `stopEdit` has a flaw, so I fix it as well as its test.
2. Solve all test errors.
The javascript tests on travis should be passed now.

[web] Fixes all existed tests

---

web/src/js/ducks/ui/flow.js

It seems that I made something wrong in last PR(#2133):
The flows in the table can't update the size entry and the icon on the left when finish loading. It turned out that we should not change `data` to `flow` on line 63, but change the parameter name of the `stopEdit()` function.
Sorry for the trouble.

[web] Fixes the flaw in #2133

---

web/src/js/__tests__/ducks/utils/storeSpec.js

Try to add some tests for store.js. Since this is a new test for a file that we haven't covered before, if there is anything not good enough, please let me know.

[web] Add tests for ducks/utils/store.js

---

mitmproxy/flowfilter.py
web/src/js/filt/filt.peg

Changed the ~u filter in the console UI to match the behavior of
mitmweb, which only matches against pretty_url, never against url.
-----
Fixes #2146 (thanks mhils for the hint on where to fix it)

Match ~d and ~u filters against pretty_host too

---

mitmproxy/certs.py
mitmproxy/net/http/message.py
mitmproxy/types/multidict.py
test/mitmproxy/net/http/test_message.py
test/mitmproxy/test_certs.py
test/mitmproxy/types/test_multidict.py

Python 2:
> There are no implied relationships among the comparison operators. The truth of x==y does not imply that x!=y is false. Accordingly, when defining \_\_eq\_\_(), one should also define \_\_ne\_\_() so that the operators will behave as expected.
Python 3:
> By default, \_\_ne\_\_() delegates to \_\_eq\_\_() and inverts the result.
The removed tests would still pass, but they are just baggage at this point.

py3: __ne__ delegates to __eq__ by default

---

mitmproxy/types/multidict.py
test/mitmproxy/types/test_multidict.py

It actually was there before (from serializable), but raised when invoked.

Add MultiDictView.copy()

---

.travis.yml

Using `npm install -g yarn` is easy to get into trouble, so we change to install yarn with the script given by their developer. [reference](https://yarnpkg.com/lang/en/docs/install-ci/#travis-tab)

Update .travis.yml to fix the failure about yarn

---

mitmproxy/flow.py

As discussed with @cortesi about this #2096  over IRC . Now it will set reply to DummyReply whenever we duplicate any flow. #2086 .

Fix crash when duplicating flow

---

mitmproxy/master.py
mitmproxy/net/http/request.py
mitmproxy/tools/console/flowlist.py
test/mitmproxy/net/http/test_request.py
test/mitmproxy/test_flow.py

This is a simple interface to create HTTP requests, analogous to `Response.make`. 
I deliberately placed `headers` after `content` to match the signature of `Response.make`.

Add Request.make

---

test/mitmproxy/contentviews/test_xml_html.py

When the path contains dot ".", replacing all dots will generate a non-exist result and raises a FileNotFoundError. Replacing only the last dot fixes this.

Fix test_format_xml with dot in path

---

web/src/css/header.less

Hello, I'm frank ahn. 
This is my first PR. ( even in my life lol )
Recently, I asked about changing positions of pop-up docs in the mitmweb to @mhils. 
He said yes, so I tinkered a couple of css codes. 
**Before change**
**After  change**

[web] Adjust pop-up docs position

---

mitmproxy/tools/web/app.py
mitmproxy/tools/web/master.py
web/src/js/components/Footer.jsx

Check if the `option.server` is on before printing the information about the proxy server.
In mitmweb, add `server` to `state.setting`, so we could display the correct message in the termstatus.

Fix#2184, mitmweb -n dispalys incorrect message.

---

web/package.json
web/src/js/__tests__/ducks/eventLogSpec.js

This one is easy to test.
The `testPathDirs` in Jest configuration has been replaced by `roots`, so we update that to avoid the deprecation warning.

Add coverage for eventLog.js and update Jest config.

---

mitmproxy/addons/script.py
test/mitmproxy/addons/test_script.py
test/mitmproxy/data/addonscripts/print.py

Redirect messages written to stdout in scripts to ctx.log.warn.
(closes #1530)

scripts: redirect stdout to ctx.log.warn

---

examples/complex/dns_spoofing.py
examples/complex/har_dump.py
examples/complex/remote_debug.py
examples/complex/tls_passthrough.py
examples/simple/add_header_class.py
examples/simple/custom_contentview.py
examples/simple/custom_option.py
examples/simple/filter_flows.py
examples/simple/io_write_dumpfile.py
examples/simple/log_events.py
examples/simple/modify_body_inject_iframe.py
examples/simple/script_arguments.py
examples/simple/wsgi_flask_app.py
mitmproxy/addonmanager.py
mitmproxy/addons/script.py
mitmproxy/addons/serverplayback.py
mitmproxy/eventsequence.py
mitmproxy/script/concurrent.py
mitmproxy/tools/dump.py
setup.cfg
test/mitmproxy/addons/test_script.py
test/mitmproxy/addons/test_serverplayback.py
test/mitmproxy/data/addonscripts/addon.py
test/mitmproxy/data/addonscripts/concurrent_decorator_class.py
test/mitmproxy/data/addonscripts/print.py
test/mitmproxy/data/addonscripts/recorder.py
test/mitmproxy/script/test_concurrent.py
test/mitmproxy/test_addonmanager.py

This PR implements the startup portion of the design I outline in #2144. 
* Rename `start` to `load`
* Add a loader with `add_option` and `boot_into` methods
* Expand and improve coverage
For now, this keeps a 1-for-1 correlation to the existing structure. The next PR will be a significant change to the way we handle and load sub-addons.

addon refactoring

---

examples/simple/wsgi_flask_app.py

Chrome doesn't like it if there's no TLD.

proxapp -> proxapp.local

---

.travis.yml
web/package.json
web/src/js/__tests__/ducks/settingsSpec.js

This PRs is for:
+ Add a small js dependency `jest-fetch-mock`, because `node` does not support the `fetch` function, we have to mock it when running the test. This dependency would make our test jobs easier when dealing with some async actions.
+ Add `setupJest.js` to load `jest-fetch-mock` when starting Jest.
+ Add `--coverage` argument when doing `npm test`, so we could have the coverage report on travis.
+ Reach 100% coverage for `ducks/settings.js`

[web] Update Jest config and coverage ++

---

mitmproxy/tools/console/flowlist.py

Mitmproxy crashes on pressing `g` or `G` while `eventlog` is focused and is empty. This happens due to `IndexError` in `set_focus`, so this PR just put a check by overriding it.
Mitmproxy version: 3.0.0 (1.0.1dev0502-0x60b2fdfe) 
Python version: 3.6.0
Platform: Linux-4.8.13-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Linux distro: arch
PS: Should I open a issue before sending PR?

eventlog: Override set_focus to check for index error

---

test/mitmproxy/console/test_flowlist.py

In continuation to #2220, this adds tests to cover `set_focus` in `LogBufferBox`. This will be conflicting with #2112, but even when that gets ready, we will be needing the tests and then they can shifted to other files.

Add tests for set_focus

---

docs/howmitmproxy.rst

Updating usage of 'a' or 'an' to be more consistent with general English grammatical rules. TLS is pronounced with a consonant sound for both the expanded and abbreviated versions.

Replace phrase "an TLS" with "a TLS"

---

mitmproxy/tools/web/static/vendor.js
mitmproxy/version.py

Replaced with the appropriate "in the" and "to the".
There are multiple other occurences of this but they are in upstream python modules.

Replace phrase 'the the' in 2 places

---

mitmproxy/net/http/http1/read.py
test/mitmproxy/net/http/http1/test_read.py

I noticed the following output in the event log:
```
127.0.0.1:58169: HTTP protocol error in client request: Invalid host specification: b'[2a03:2880:f003:c07:face:b00c::2]:443'
```
It appears that the authority form parser does not handle ipv6 hostnames properly. I changed the parser to:
* Split on a single colon from the right-hand-side
* Strip brackets when an ipv6 hostname is detected
I also added a test for this condition.

fixes ipv6 authority form parsing in CONNECT

---

mitmproxy/addonmanager.py
mitmproxy/addons/script.py
mitmproxy/test/taddons.py
setup.py
test/examples/test_examples.py
test/mitmproxy/addons/test_script.py
test/mitmproxy/data/addonscripts/addon.py
test/mitmproxy/data/addonscripts/concurrent_decorator_err.py
test/mitmproxy/script/test_concurrent.py

- Remove the watchdog dependency. We now just stat the script file every 2
seconds to check for an updated mtime.
- Further solidify our script testing, and in particular make the example tests
nicer. These should exemplify how we want users to test their own addon
scripts. More work on addon testing to follow.

Remove watchdog, solidify script testing

---

web/src/js/__tests__/flow/utilsSpec.js
web/src/js/__tests__/utilsSpec.js

Add coverage for js/utils.js, js/flow/utils.js. 
Now we have 100% coverage for the js files that we'd touched. :tada:

[web] Add coverage for js/utils.js, js/flow/utils.js

---

mitmproxy/net/tcp.py
mitmproxy/utils/version_check.py
setup.py

This removes OpenSSL v0.9.8 support.

bump cryptography min-version

---

mitmproxy/addonmanager.py
mitmproxy/addons/__init__.py
mitmproxy/addons/save.py
mitmproxy/addons/view.py
mitmproxy/command.py
mitmproxy/exceptions.py
mitmproxy/log.py
mitmproxy/master.py
mitmproxy/options.py
mitmproxy/optmanager.py
mitmproxy/test/taddons.py
mitmproxy/tools/cmdline.py
mitmproxy/tools/console/command.py
mitmproxy/tools/console/flowlist.py
mitmproxy/tools/console/master.py
mitmproxy/tools/console/signals.py
mitmproxy/tools/console/statusbar.py
mitmproxy/tools/main.py
mitmproxy/utils/typecheck.py
test/mitmproxy/addons/test_save.py
test/mitmproxy/addons/test_view.py
test/mitmproxy/test_addonmanager.py
test/mitmproxy/test_command.py
test/mitmproxy/utils/test_typecheck.py

Based on #2273
This has the same urgency as "info", but also signals to interactive tools that
the user's attention should be drawn to the output, even if they're not looking
at the event log. In the console app, this means the message appears in the
status bar with a timeout.

Add an "alert" log level.

---

mitmproxy/addonmanager.py
mitmproxy/addons/__init__.py
mitmproxy/addons/core.py
mitmproxy/tools/console/master.py
mitmproxy/tools/console/window.py
test/mitmproxy/addons/test_core.py

The set command sets an option using the same syntax as commandline --set.

commands: add the core command addon, and the command "set"

---

docs/scripting/overview.rst

I think our simple example scripts are a very useful resource for new addon developers, so I'd like to link to them very prominently. We of course should not see them as a replacement for textual documentation, but I think they are a very useful complement.
@cortesi, ok with you?

Prominently link to examples in script docs

---

mitmproxy/addons/__init__.py
mitmproxy/addons/cut.py
mitmproxy/command.py
mitmproxy/test/tflow.py
mitmproxy/tools/console/flowlist.py
mitmproxy/tools/console/master.py
mitmproxy/tools/main.py
mitmproxy/utils/strutils.py
mitmproxy/utils/typecheck.py
test/mitmproxy/addons/test_cut.py
test/mitmproxy/test_command.py
test/mitmproxy/test_connections.py
test/mitmproxy/utils/test_typecheck.py

This PR introduces the cuts addon, a flow dissector that  allows you to select
and operate on specific components of flows. It also adds the first consumer
for cuts - the cuts.save command.
Save the content of the focus to /tmp/foo:
cuts.save s.content|@focus /tmp/foo
Save the URL and response content-type headers for all flows currently shown to
file, comma-separated, one flow per line:
cuts.save s.url,q.header[content-type]|@focus /tmp/foo
We also use this to replace the body save shortcut in the console flowlist.

Introduce cuts: a flow dissector

---

web/package.json
web/src/js/__tests__/urlStateSpec.js
web/src/js/urlState.js
web/yarn.lock

It's a little bit tricky to complete the tests for this, so I want to explain a bit here.
The reducers(`reduceFlows`...) are require here to create a store object which our target function will operate on, so we could not mock the whole js file as we usually do. However, we don't care about the implementation of certain actions (`setFilter`...) and want to mock them up.
In this case, `jest.mock()` does not work. After looking up the documentation, I found a solution which uses `jest.spyOn()`. We could import all the reducers and actions first, and mock the action functions before calling the target function. Then we could use the handy `toBeCalledWith()` function to test if we are passing the right arguments to the action functions.
***
Now that we have covered almost all of the `.js` …

[web] Add coverage for js/urlState.js

---

mitmproxy/addons/proxyauth.py
mitmproxy/options.py
setup.py
test/mitmproxy/addons/test_proxyauth.py

Added basic LDAP Auth:
Based on ldap3, I just added the option ldap after --proxyauth :
--proxyauth ldap[s]:url_ldap:dn:group
example :
--proxyauth ldap:ldap.forumsys.com:uid=?,dc=example,dc=com:person
So the DN can be anything (should be based on the configuration of the ldap server), the username will be queried as ? in the dn. 
Basically it will connect and bind to the server and check that the user :
- Has proper creds for logging in the server
- Is part of a group (needs to be configured on the LDAP server) that will be allowed to use the proxy

Added LDAP Auth

---

docs/certinstall.rst

Even after installing certs from `mitm.it`, it's not trusted by default, user need to enable this on their own.
http://stackoverflow.com/a/43303169/1433273

Note to enable `Certificate Trust Settings` in iOS 10.3 or up

---

mitmproxy/addons/onboardingapp/templates/index.html

This is a PR for #2313 (2nd point). I used to JS to show content dynamically..
This PR does not add additional OSes/software to the list though (#2313 1st point).

Add specific instructions on mitm.it when an icon is clicked

---

mitmproxy/addons/onboardingapp/app.py
test/mitmproxy/addons/test_onboarding.py

fixes #2324
@Kriechi The test is failing sometimes on my local machine.
It throws a TypeError `TypeError: getsockaddrarg() takes exactly 2 arguments (4 given)` in tcp.create_connection on [this line](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/tcp.py#L668) when the af is AF_INET and source address is ('::1', 52418, 0, 0) 
Is it something wrong wtih the test or create_connection function? 
None of the other test fail :confused:

Handle head request on onboarding app: Fix #2324

---

web/package.json
web/src/js/__tests__/ducks/eventLogSpec.js
web/src/js/__tests__/ducks/flowsSpec.js
web/src/js/__tests__/ducks/indexSpec.js
web/src/js/__tests__/ducks/settingsSpec.js
web/src/js/__tests__/ducks/tutils.js
web/src/js/__tests__/ducks/ui/flowSpec.js
web/src/js/__tests__/ducks/ui/headerSpec.js
web/src/js/__tests__/ducks/ui/indexSpec.js
web/src/js/__tests__/ducks/ui/keyboardSpec.js
web/src/js/__tests__/ducks/utils/storeSpec.js

Here's the brief road map about adding tests for our JavaScript code.
Next step: Add tests for components in the `.jsx` files.
The reason why we need to remove `jest.unmock` has been discussed [here](https://github.com/mitmproxy/mitmproxy/pull/2212#issuecomment-289211106), I think we should keep the automocking disabled and manually mock the modules if necessary.

[WIP][web] Coverage improve

---

web/package.json
web/src/js/__tests__/components/common/ButtonSpec.js
web/src/js/__tests__/components/common/DocsLinkSpec.js
web/src/js/__tests__/components/common/DropdownSpec.js
web/src/js/__tests__/components/common/FileChooserSpec.js
web/src/js/__tests__/components/common/SplitterSpec.js
web/src/js/__tests__/components/common/ToggleButtonSpec.js
web/src/js/__tests__/components/common/ToggleInputButtonSpec.js
web/src/js/__tests__/components/common/__snapshots__/ButtonSpec.js.snap
web/src/js/__tests__/components/common/__snapshots__/DocsLinkSpec.js.snap
web/src/js/__tests__/components/common/__snapshots__/DropdownSpec.js.snap
web/src/js/__tests__/components/common/__snapshots__/FileChooserSpec.js.snap
web/src/js/__tests__/components/common/__snapshots__/SplitterSpec.js.snap
web/src/js/__tests__/components/common/__snapshots__/ToggleButtonSpec.js.snap
web/src/js/__tests__/components/common/__snapshots__/ToggleInputButtonSpec.js.snap
web/src/js/__tests__/components/helpers/AutoScrollSpec.js
web/src/js/__tests__/components/helpers/VirtualScrollSpec.js
web/src/js/components/common/DocsLink.jsx
web/src/js/components/common/FileChooser.jsx
web/yarn.lock

[WIP][web] Add tests for UI components

---

mitmproxy/net/tcp.py

The .configure and .tick events can be called before the server is running. If
an addon calls ctx.master.shutdown() at this point, the server hangs forever
waiting on __is_shutdown_set. This patch fixes this by starting off with it
already set.

net.tcp: server should be in shut-down state before start

---

test/mitmproxy/tools/web/test_app.py
web/src/js/__tests__/components/FlowTable/FlowColumnsSpec.js
web/src/js/__tests__/components/FlowTable/__snapshots__/FlowColumnsSpec.js.snap
web/src/js/__tests__/ducks/_tflow.js
web/src/js/__tests__/ducks/tutils.js

Suggested by @mhils [here](https://github.com/mitmproxy/mitmproxy/pull/2337#discussion_r117033821), we add a python test to generate `js/__tests__/ducks/_flow.js` for the components tests. In this way, each time when we run the python test, it will produce a generator function for our js tests.

[web] Add  _flow.js for component tests.

---

web/package.json
web/src/js/__tests__/components/FlowTable/FlowTableHeadSpec.js
web/src/js/__tests__/components/Header/ConnectionIndicatorSpec.js
web/src/js/__tests__/components/Header/FileMenuSpec.js
web/src/js/__tests__/components/Header/FilterDocsSpec.js
web/src/js/__tests__/components/Header/FilterInputSpec.js
web/src/js/__tests__/components/Header/FlowMenuSpec.js
web/src/js/__tests__/components/Header/MainMenuSpec.js
web/src/js/__tests__/components/Header/MenuToggleSpec.js
web/src/js/__tests__/components/Header/OptionMenuSpec.js
web/src/js/__tests__/components/Header/__snapshots__/ConnectionIndicatorSpec.js.snap
web/src/js/__tests__/components/Header/__snapshots__/FileMenuSpec.js.snap
web/src/js/__tests__/components/Header/__snapshots__/FilterDocsSpec.js.snap
web/src/js/__tests__/components/Header/__snapshots__/FilterInputSpec.js.snap
web/src/js/__tests__/components/Header/__snapshots__/FlowMenuSpec.js.snap
web/src/js/__tests__/components/Header/__snapshots__/MainMenuSpec.js.snap
web/src/js/__tests__/components/Header/__snapshots__/MenuToggleSpec.js.snap
web/src/js/__tests__/components/Header/__snapshots__/OptionMenuSpec.js.snap
web/src/js/__tests__/ducks/tutils.js
web/src/js/components/Header/ConnectionIndicator.jsx
web/src/js/components/Header/FileMenu.jsx
web/src/js/components/Header/FlowMenu.jsx
web/src/js/components/Header/MainMenu.jsx
web/yarn.lock

[WIP][web] Add tests for js/components/Header

---

web/src/js/__tests__/components/ContentView/CodeEditorSpec.js
web/src/js/__tests__/components/ContentView/ContentViewOptionsSpec.js
web/src/js/__tests__/components/ContentView/__snapshots__/CodeEditorSpec.js.snap
web/src/js/__tests__/components/ContentView/__snapshots__/ContentViewOptionsSpec.js.snap
web/src/js/components/ContentView/ContentViewOptions.jsx

[WIP][web] Add tests for components/ContentView

---

test/mitmproxy/tools/console/test_master.py

This should fix appveyor. 
Pytest's monkeypatch [doesn't work out of the box](https://github.com/pytest-dev/pytest/issues/363), so I'm just using `unittest.mock` from stdlib.

Always pretend to have a tty in tests

---

web/package.json
web/src/js/__tests__/components/ContentView/ContentLoaderSpec.js
web/src/js/__tests__/components/ContentView/ContentViewSpec.js
web/src/js/__tests__/components/ContentView/DownloadContentButtonSpec.js
web/src/js/__tests__/components/ContentView/MetaViewsSpec.js
web/src/js/__tests__/components/ContentView/ShowFullContentButtonSpec.js
web/src/js/__tests__/components/ContentView/UploadContentButtonSpec.js
web/src/js/__tests__/components/ContentView/ViewSelectorSpec.js
web/src/js/__tests__/components/ContentView/__snapshots__/ContentLoaderSpec.js.snap
web/src/js/__tests__/components/ContentView/__snapshots__/ContentViewSpec.js.snap
web/src/js/__tests__/components/ContentView/__snapshots__/DownloadContentButtonSpec.js.snap
web/src/js/__tests__/components/ContentView/__snapshots__/MetaViewsSpec.js.snap
web/src/js/__tests__/components/ContentView/__snapshots__/ShowFullContentButtonSpec.js.snap
web/src/js/__tests__/components/ContentView/__snapshots__/UploadContentButtonSpec.js.snap
web/src/js/__tests__/components/ContentView/__snapshots__/ViewSelectorSpec.js.snap
web/src/js/components/ContentView/ContentLoader.jsx
web/src/js/components/ContentView/ContentViews.jsx
web/src/js/components/ContentView/DownloadContentButton.jsx
web/src/js/components/ContentView/ShowFullContentButton.jsx
web/src/js/components/ContentView/UploadContentButton.jsx
web/src/js/components/ContentView/ViewSelector.jsx
web/yarn.lock

[WIP][web] Add tests for components/ContentView (con't)

---

test/mitmproxy/proxy/protocol/test_http1.py

This is a test for response streaming and raises an exception for request streaming as it isn't supported yet.

Test for streaming

---

mitmproxy/contrib/kaitaistruct/tls_client_hello.py
mitmproxy/contrib/tls_client_hello.ksy
mitmproxy/proxy/protocol/tls.py

Removes a redundant type in tls client hello parser
Earlier -
```
for cs in cipher_suites.cipher_suites:
print(cs.cipher_suite)
```
Now -
```
for cs in cipher_suites.cipher_suites:
print(cs)
```

Removed redundant type

---

mitmproxy/optmanager.py
mitmproxy/tools/web/app.py
mitmproxy/utils/typecheck.py
test/mitmproxy/test_optmanager.py
test/mitmproxy/tools/web/test_app.py
test/mitmproxy/utils/test_typecheck.py

The return json looks like this:
```python
[
{
"default": false, 
"help": "Add all certificates of the upstream server to the certificate chain that will be served to the proxy client, as extras.", 
"name": "add_upstream_certs_to_client_chain", 
"type": "bool", 
"value": false
}, 
{
"default": false, 
"help": "Strip out request headers that might cause the server to return 304-not-modified.", 
"name": "anticache", 
"type": "bool", 
"value": false
}, 
...]
```
The tests passed on my local repo, but kept falling on Travis... Is that because of some compatibility problem?

[WIP] Add RESTful API for mitmweb option

---

mitmproxy/master.py
test/mitmproxy/test_flow.py

Replay works with http2 flows but uses http1.1 when replaying.
Not sure if it's the intended fix though

Fixes #2197

---

mitmproxy/addons/script.py
test/mitmproxy/addons/test_script.py

Fixes #2315
Well, this was a tricky one.
**The issue -** 
We use [`load_module`](https://docs.python.org/3/library/importlib.html#importlib.abc.Loader.load_module) to load the scripts. According to the docs -
> If the requested module already exists in sys.modules, that module should be used and reloaded
So, the modified script was [`reloaded`](https://docs.python.org/3/library/importlib.html#importlib.reload) 
> When a module is reloaded, its dictionary (containing the module’s global variables) is retained. Redefinitions of names will override the old definitions, so this is generally not a problem. If the new version of a module does not define a name that was defined by the old version, the old definition remains.
**How I solved it-**
Before loading a script remove it from …

Fixes the issue of script reloader not unloading previous script

---

mitmproxy/addons/__init__.py
mitmproxy/addons/allowremote.py
test/mitmproxy/addons/test_allowremote.py

This addon decides whether clientconnect should be accepted or not.
If allow_remote option is set to false client will not be able to connect to the proxy unless it is on the same network or the proxyauth option is set. All connections from private IPs will be allowed and remote clients will be able to connect if the proxyauth option is set.
ref: https://github.com/mitmproxy/mitmproxy/issues/1293#issuecomment-313208810

Allow remote Addon

---

mitmproxy/addonmanager.py

`.tb_next` discards the first interesting frame, this shouldn't happen.

Fix addon tracebacks

---

.travis.yml
mitmproxy/addonmanager.py
mitmproxy/addons/view.py
mitmproxy/optmanager.py
pathod/language/generators.py
pathod/pathoc_cmdline.py
pathod/pathod_cmdline.py
setup.py
test/mitmproxy/addons/test_view.py

Fixed a crash when trying to load flows from a file that doesn't exist.
Added os.path.expanduser() before open() calls with user supplied paths.

Fix load flows crash

---

mitmproxy/proxy/protocol/http.py

Example script that creates response to CONNECT: 
```
from mitmproxy.http import make_connect_response
def http_connect(flow):
if flow.request.method == 'CONNECT':
flow.response = make_connect_response(flow.request.http_version)
```
Fixes #2464

Respect response to CONNECT created in http_connect function in upstream mode

---

docs/pathod/intro.rst

Fixes typo in _pathoc_ description.

docs: Fix typo

---

mitmproxy/addonmanager.py
test/mitmproxy/test_addonmanager.py

The following script previously caused an infinite error loop:
```python
from mitmproxy import log
```
I can't test with the "log" event in the tests because that's special cased, so I just re-use `.tick`.

Gracefully ignore imports with hook names

---

mitmproxy/addons/script.py
test/mitmproxy/addons/test_script.py
test/mitmproxy/test_addonmanager.py

`load_script` previously depended on `addonmanager.safecall` to redirect errors. It's more intuitive to catch those in the addon and make `load_script` pure and independent of the rest of mitmproxy and its addon system.

Make load_script pure

---

mitmproxy/master.py
mitmproxy/options.py
mitmproxy/proxy/config.py
mitmproxy/proxy/protocol/http_replay.py
mitmproxy/test/taddons.py
mitmproxy/tools/console/master.py
mitmproxy/tools/console/statusbar.py
mitmproxy/tools/dump.py
mitmproxy/tools/main.py
mitmproxy/tools/web/master.py
mitmproxy/tools/web/webaddons.py
test/filename_matching.py
test/mitmproxy/addons/test_termstatus.py
test/mitmproxy/proxy/protocol/test_http2.py
test/mitmproxy/proxy/protocol/test_websocket.py
test/mitmproxy/proxy/test_server.py
test/mitmproxy/test_addonmanager.py
test/mitmproxy/test_controller.py
test/mitmproxy/test_flow.py
test/mitmproxy/tools/console/conftest.py
test/mitmproxy/tools/console/test_master.py
test/mitmproxy/tools/console/test_statusbar.py
test/mitmproxy/tools/test_cmdline.py
test/mitmproxy/tools/test_dump.py
test/mitmproxy/tools/web/test_app.py
test/mitmproxy/tools/web/test_master.py
test/mitmproxy/tservers.py

This started as a naive attempt to move mitmweb's options into a mitmweb-specific addon, and ended in something slightly more complex:
- **Disentagle `ProxyServer/DummyServer` from the `Master` constructor:** The proxy server should ultimately be an addon itself, so this is the first step towards this by moving it out of the function signature. 
- **Replace usage of `ProxyConfig` with `Options`:** Now that `Master` may not have a server, there also is no `ProxyConfig`, so a whole bunch of tests failed. To fix this, I replaced all usages of `ProxyConfig` with the proper equivalent in `Options`, which should have been the case from in the first place.
- **Actually move mitmweb options into mitmweb-specific addon:** We can now follow up with all other options and move them into their …

Enable tool-specific options

---

mitmproxy/tools/main.py

`mitmproxy` and `mitmweb` failed to start with following error message:
```
File "/home/matthew/mitmproxy/venv/bin/mitmproxy", line 11, in <module>
load_entry_point('mitmproxy', 'console_scripts', 'mitmproxy')()
File "/home/matthew/mitmproxy/mitmproxy/tools/main.py", line 127, in mitmproxy
run(console.master.ConsoleMaster, cmdline.mitmproxy, args)
File "/home/matthew/mitmproxy/mitmproxy/tools/main.py", line 103, in run
opts.update(**extra(args))
File "/usr/lib/python3.5/typing.py", line 135, in __new__
raise TypeError("Cannot instantiate %r" % self.__class__)
TypeError: Cannot instantiate <class 'typing.CallableMeta'>
```
It was caused by the error syntax of the default value, this PR should fix that.

Fix minor typing mistake in mitmproxy/tools/main.py

---

mitmproxy/addons/core_option_validation.py
mitmproxy/optmanager.py
mitmproxy/proxy/protocol/http1.py
mitmproxy/proxy/protocol/http2.py
mitmproxy/proxy/protocol/http_replay.py
mitmproxy/utils/human.py
test/mitmproxy/addons/test_core_option_validation.py
test/mitmproxy/proxy/protocol/test_http2.py
test/mitmproxy/utils/test_human.py

Instead of having the core addon do postprocessing on body_size_limit,
we add a cache to the parsing function. First, this avoids any potential issues
with options and _processed getting out of sync. As anecdotal evidence,
the previous implementation did not clear _processed when body_size_limit was
reset to None. Second, it achieves the same end result without introducing a new
concept of a "_processed" scratch space. Third, it works even if addons aren't present,
and does not require workarounds as previously present in test_http2.py.
refs https://github.com/mitmproxy/mitmproxy/pull/2484#pullrequestreview-53101507

Remove OptManager._processed

---

mitmproxy/options.py
mitmproxy/proxy/root_context.py

See https://github.com/mhils/mitmproxy/commit/9ca6785d40ebe0293f36683250d72998f438bba9 for the motivation. This is not the final solution to the problem, but an improvement over the current state.

Re-add rawtcp mode.

---

mitmproxy/tools/console/consoleaddons.py
mitmproxy/tools/console/defaultkeys.py

This PR does 2 things - 
* Renamed intercept_toggle command to console.intercept.toggle to be consistent with existing commands  
* Update options when <kbd>I</kbd> is pressed. Currently we need to press <kbd>I</kbd> and <kbd>Enter</kbd> to toggle

Improve intercept toggle

---

mitmproxy/tools/cmdline.py

I think this is one of the more important ones we should not omit, e.g. as `--no-http2` is still needed for scripted redirection.
@Kriechi?

re-add --http2 switch

---

mitmproxy/net/tcp.py

This is a one line fix so that mitmproxy (git master version) correctly works on a system where ipv6 is disabled.
Without it, I get the following exception when trying to run mitmproxy:
```
File "/home/arch/mitm/dev/mitmproxy/mitmproxy/net/tcp.py", line 862, in __init__
self.socket = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
File "/usr/lib/python3.6/socket.py", line 144, in __init__
_socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
During handling of the above exception, another exception occurred:
File "/home/arch/mitm/dev/mitmproxy/mitmproxy/proxy/server.py", line 46, in __init__
(config.options.listen_host, config.options.listen_port)
File …
```

Fallback correctly to ipv4 when ipv6 is not supported

---

docs/install.rst

We only need pip3 now on all OSes as cryptography now ships wheels on Linux :tada:.
Also remove `pip3 install --user` recommendation because that won't end up on $PATH.

docs: simplify install instructions

---

setup.py

Reverts mitmproxy/mitmproxy#2511 because requests v2.18.4 fixes this.

Revert "Fix version conflict"

---

mitmproxy/tools/web/static_viewer.py
test/mitmproxy/tools/web/test_static_viewer.py
web/src/js/backends/static.js

The generation of `setting.json` improve the extensibility of static viewer, for now, it could display the version of mtimproxy. We could include other settings in `settings.json` in the future.

[web] Add settings.json to Static viewer

---

mitmproxy/net/tcp.py
mitmproxy/net/tls.py
mitmproxy/options.py
mitmproxy/proxy/config.py
mitmproxy/proxy/protocol/tls.py
pathod/pathoc.py
pathod/pathoc_cmdline.py
pathod/pathod.py
pathod/pathod_cmdline.py
setup.cfg
test/mitmproxy/net/test_tcp.py
test/mitmproxy/net/test_tls.py
test/mitmproxy/proxy/test_server.py

We can re-use the context bits for the sans-io branch, so it makes sense to separate this now.

Split TLS parts from net.tcp into net.tls

---

mitmproxy/flowfilter.py

The expression for body of response is "bs", not "bq".

Fix typo in the docstring of flowfilter

---

test/conftest.py
test/mitmproxy/net/test_tcp.py

Travis tests are currently failing because travis migrated their precise builds [1] from their container-based infrastructure to full virtual machines, which apparently don't support IPv6. This PR skips the IPv6 tests on systems where no IPv6 support is present.
[1] We use those so that our PyInstaller inaries are compiled with an old glibc version. Otherwise, they do not work on old systems (and AWS Lambda).

Skip ipv6 tests on sudo-enabled travis builds

---

mitmproxy/addonmanager.py
test/mitmproxy/addons/test_script.py

This is invoked by print() statements within addons, so it better be safe.

Make master.add_log threadsafe

---

mitmproxy/proxy/config.py

Certs provided through the --cert argument or config yaml get stored in the certs dictionary as a str. This causes issues because the keys created by get_certs method are byte strings. So any provided certs wind up being ignored and the generated certs still get stored as byte strings.
1. Start the proxy and provide a cert through the command line or config.yaml options:
```bash
mitmproxy --cert [domain=path to pem]
```
2. Attach to the process using the debugger and set a breakpoint in `certs.py` at the `get_cert` method.  
3. Step through the method until you get to `if name:`
This was found when trying to modify requests while keeping certificate pinning enabled using a second cert I have pinned and have the private key to. Once I converted the spec to bytes the domain and certificate …

Fixes bug where loaded certs are stored in the certs dict as str

---

mitmproxy/addons/clientplayback.py
mitmproxy/flow.py
mitmproxy/http.py
mitmproxy/proxy/protocol/http_replay.py
test/mitmproxy/addons/test_clientplayback.py
test/mitmproxy/test_flow.py

- always refresh UI after flow is finished (refs #2616)
- count currently active replay
- make replay thread daemonic so that users can exit mitmproxy
if replay hangs. This is not perfect yet, but vastly better
than how it has been.

Improve Clientreplay

---

mitmproxy/addons/__init__.py
mitmproxy/addons/browser.py
mitmproxy/tools/console/defaultkeys.py
test/mitmproxy/addons/test_browser.py

A simple addon that starts an instance of Chrome attached to the current
proxy. The instance is isolated in its own user data directory, and addons are
turned off.
Future work:
- I wasn't able to test the Windows executable path - a Windows dev should
confirm this for us.
- In future it would be nice to support other browsers like Firefox.

browser addon: start an isolated browser attached to the proxy

---

mitmproxy/command.py
test/mitmproxy/test_command.py

Fixes #2652, and many other possible crashes on user input.

commands: verify command function signatures before call

---

pathod/pathoc.py

This is required by the new HTTP RFCs.

Add host header to pathoc's CONNECT requests

---

mitmproxy/addons/core.py
mitmproxy/addons/view.py
mitmproxy/command.py
mitmproxy/tools/console/consoleaddons.py
mitmproxy/tools/console/defaultkeys.py
mitmproxy/utils/typecheck.py
test/mitmproxy/addons/test_core.py
test/mitmproxy/test_command.py

The big thing in this PR is a mechanism that lets us specify that a command argument should be one of a set of options returned by another command. This is used for runtime checking of invoked commands.
The mechanism here is extremely ugly, but works. We want to construct types that have two attributes - they should be resolved as *str* by mypy, and they need an additional attribute for us to work with at runtime. The annotations mechanism is very general, and makes this a piece of cake. Unfortunately mypy itself is super restrictive about what it accepts as a type specification. Almost any attempt to construct these types at runtime is doomed to fail. There is some discussion about this on the mypy issue tracker, but nothing immediate on the cards to improve things. I'm open to …

Command improvements

---

mitmproxy/addons/core.py
mitmproxy/addons/cut.py
mitmproxy/addons/export.py
mitmproxy/addons/save.py
mitmproxy/addons/view.py
mitmproxy/command.py
mitmproxy/tools/console/consoleaddons.py
test/mitmproxy/test_command.py

This is just an alias for str, and in this patch is used mostly to give an
appropriate type in help strings. More to come.
Fixes #2198

commands: add a Path argument type

---

mitmproxy/addons/core.py
mitmproxy/command.py
mitmproxy/tools/console/consoleaddons.py
mitmproxy/utils/typecheck.py
test/mitmproxy/test_command.py

This makes it possible to specify more specific type annotations at runtime, so that both mypy and our command system are happy. The `.argument(name, type=)` syntax is similar to click's, so it should be fairly extensible if we need it.

Introduce @command.argument

---

mitmproxy/tools/console/eventlog.py
mitmproxy/tools/console/flowview.py

This fixes the second bullet point at https://github.com/mitmproxy/mitmproxy/issues/2658#issue-280835169

Don't display contentview errors too prominently.

---

mitmproxy/addons/clientplayback.py
mitmproxy/addons/core.py
mitmproxy/addons/cut.py
mitmproxy/addons/export.py
mitmproxy/addons/save.py
mitmproxy/addons/serverplayback.py
mitmproxy/addons/view.py
mitmproxy/command.py
mitmproxy/exceptions.py
mitmproxy/tools/console/commander/commander.py
mitmproxy/tools/console/consoleaddons.py
mitmproxy/types.py
test/mitmproxy/test_command.py
test/mitmproxy/test_types.py
test/mitmproxy/tools/console/test_commander.py
test/mitmproxy/utils/test_typecheck.py

The type system was scattered over a number of places, making it hard to
follow. This collects all command types in types.py, and completion, validation
and parsing for each type is centralised. We should use the same mechanism for
options.

commands: refactor types

---

docs/certinstall.rst

Actually, these instructions were mostly already there, but not under the iOS section which made them hard to find (I completely missed them). Put them in the correct section and expand them a little.

Move trust instructions for ios

---

mitmproxy/script/concurrent.py
test/mitmproxy/data/addonscripts/concurrent_decorator_class.py

``` python
import time
from mitmproxy.script import concurrent
class ConcurrentClass:
@concurrent  # Remove this and see what happens
def request(self, flow):
print("handle request: %s%s" % (flow.request.host, flow.request.path))
time.sleep(5)
print("start  request: %s%s" % (flow.request.host, flow.request.path))
addons = [ConcurrentClass()]
```
`@concurrent` only works for class staticmethod for now, I make it works for normal class method.

@concurrent decorator works for class methods.

---

mitmproxy/utils/human.py
test/mitmproxy/utils/test_human.py

The set of people who understand "0.0.0.0" (and/or "::") is a subset of
the set of people who understand "*", so we can make things easier to understand
by using the less technical notation.
Empirical Evidence:
- https://discourse.mitmproxy.org/t/unable-to-use-mitmproxy-on-windows/735
- https://discourse.mitmproxy.org/t/how-to-view-the-proxy-servers-url/23

Display "*" when listening on all interfaces

---

mitmproxy/command.py
test/mitmproxy/tools/console/test_defaultkeys.py

This seems to generally work, but it's currently complains about https://github.com/mitmproxy/mitmproxy/issues/2693 and fails. Not sure if there are further issues beyond that.

Test that default key bindings are valid commands

---

mitmproxy/addons/clientplayback.py
test/mitmproxy/addons/test_clientplayback.py

Check whether the flows are live before doing a replay.

Fix #2766.

---

mitmproxy/tools/console/commander/commander.py
mitmproxy/tools/console/statusbar.py

ref: #2776 
Not sure if it's the best fix.
Type of `self._w` can be `urwid.Edit` or `commander.CommandEdit`. 
`urwid.Edit` doesn't have a get_value method so I changed commander.CommandEdit's method to match that of urwid.Edit's 
If you want to keep the function name we can check for the type of `self._w` before extracting the text

Fix crash when searching

---

mitmproxy/flow.py
mitmproxy/stateobject.py
mitmproxy/utils/typecheck.py
setup.cfg
test/mitmproxy/test_stateobject.py
test/mitmproxy/utils/test_typecheck.py

This PR improves our stateobject to handle nested types such as `typing.List[typing.Tuple[int, str]]`. This will enable storing TLS extensions on `flow.client_conn` later for #2788.

stateobject: use typing, enable tuples and more complex datatypes

---

mitmproxy/net/http/url.py
test/mitmproxy/net/http/test_url.py

A bug appeared in this line https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/http/request.py#L444
If `form_data` is an empty list and `similar_to` is a string that makes internal `remove_trailing_equal` become `True`, then an exception occurs.
I just check, whether internal `encoded` is empty or not.

Issue 2399

---

mitmproxy/command.py

If posix=False, quotes are not stripped from parsed tokens:
```python
>>> list(shlex.shlex("foo 'bar baz'"))
['foo', "'bar baz'"]
>>> list(shlex.shlex("foo 'bar baz'", posix=True))
['foo', 'bar baz']
```
@cortesi, was this intentionally left in non-posix mode? I haven't fully looked into this, but I believe this breaks flowspec filter resolution at the moment: `replay.client "~m GET"` does not work, `replay.client ~s` does.

Parse Commands in POSIX mode

---

.gitignore
mitmproxy/addons/cut.py
mitmproxy/addons/export.py
mitmproxy/tools/console/consoleaddons.py
test/mitmproxy/addons/test_cut.py
test/mitmproxy/addons/test_export.py

Continuation of https://github.com/mitmproxy/mitmproxy/pull/2761 
I added tests with mocked `open` function. I hope it is the right way to test such things. 
Now, when you press `w`, `e` or `b` and input invalid file path, you will get something like:

Fix for #2750 and #2783

---

mitmproxy/tools/console/statusbar.py

Now flow counter in the bottom left corner is updated only when we press `down`-`up` buttons or use mouse wheel. I think it will be more useful, if we make this counter work in real-time.
When new flow is added, it is sent to all receivers through `sig_view_add` - https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/view.py#L305
So, we just redraw our statusbar every time, when new flow is sent through `sig_view_add`
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/statusbar.py#L145

Real-time flow counter

---

mitmproxy/tools/console/grideditor/base.py
mitmproxy/tools/console/grideditor/col_subgrid.py
mitmproxy/tools/console/grideditor/editors.py
mitmproxy/tools/console/window.py

The main problem of this issue is absence of `view_grideditor` in mitmproxy v3.0.0
An exception occurs in this line https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/grideditor/col_subgrid.py#L30
`view_grideditor` in mitmproxy v2.0.x pushes the whole widget into the stack, but in v3.0.0 we have `push` method instead of `view_grideditor`, which pushes only the name and then mitmproxy retrieves necessary widget by its name from `self.windows`. 
I had a few variants of how to fix it and I am not sure I chose the best one :)
First of all, we must fix another related issue, which I described in the comments https://github.com/mitmproxy/mitmproxy/issues/2753#issuecomment-359825373. It happens because of this https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/to …

Fix #2753. Fix resetting editings.

---

mitmproxy/tools/console/overlay.py

Shortcuts for all overlays. 
Now it is much easier to choose menu item at the bottom of any overlay.
If there is a situation, when your overlay has so many items, that mitmproxy doesn't have so many shortcuts (what if!), you will see the warning message: `Too few available shortcuts.` and anyway you will be able to use remaining shortcuts.
Examples:
If there aren't available shortcuts:
P.S. Now you can leave overlay by pressing `q` as well.

Issue #2785. New shortcuts.

---

web/package.json
web/src/js/ducks/utils/store.js
web/yarn.lock

This is more complex then it looks like:
1. we want to have the descending/ascending argument, so we should use [_.orderBy](https://lodash.com/docs/4.17.4#orderBy) here.
2. The `makeSort` function will be invoked in other places like [here](https://github.com/mitmproxy/mitmproxy/blob/master/web/src/js/ducks/flows.js#L108) and [here](https://github.com/mitmproxy/mitmproxy/blob/master/web/src/js/ducks/utils/store.js#L195), so we cannot just eliminate it.
We should have a stable sort now, I tried it with a bunch of flows which have same status code, they remained the same order after the sorting.

[web] Fix unstable sorting

---

docs/transparent/osx.rst

The previous config threw a syntax error when saving.

Fixes issue with the pfctl config on OSX

---

mitmproxy/connections.py
mitmproxy/net/tls.py
mitmproxy/proxy/protocol/http_replay.py
mitmproxy/proxy/protocol/tls.py
test/mitmproxy/test_connections.py

The main change is [here](https://github.com/mitmproxy/mitmproxy/compare/master...mhils:always-use-tls-settings?expand=1#diff-25279a87d148019fc400b43bae211647), where we now also use the TLS settings specified in the options.

Use TLS options also for request replay

---

mitmproxy/tools/console/commander/commander.py
mitmproxy/tools/console/consoleaddons.py
mitmproxy/tools/console/defaultkeys.py
test/mitmproxy/tools/console/test_commander.py

The issue says only about _view filter_. But I think we should extend it. The issue is relevant to intercept option(`i`) and stream to file(`W`) as well.
Now after pressing `f`, `i` or `W` and setting any value, you can press the button again and correct a typo or set new similar value without reprinting the whole value from scratch.

Persist flowfilter when editing it, fix #2777

---

docs/scripting/events.rst

This PR fixes a tiny typo in the documentation.

Fix a typo in events.rst

---

mitmproxy/platform/linux.py

This fixes #2869 with the help of @aniketpanjwani.
@aniketpanjwani: If you find some time could you check if this code works for you? I improved the IPv4 detection heuristic a bit. Pretty sure it should work, but I'm still mostly coding in the dark here as we can't write sensible tests for this.

Linux: support IPv6 destinations in transparent mode

---

mitmproxy/tools/console/defaultkeys.py

This is a bit verbose, but intuitive in all layout configurations. Let's ditch this once the Windows guys have fixed it.

Add alternative keybindings for changing the layout pane on WSL (#2720)

---

mitmproxy/tools/console/consoleaddons.py

There was a bug:
1. Create a flow and  enter its details.
2. Press `m` and choose `multipart form` or `protocol buffer`.
You will see `command argument mismatch: too many positional arguments`
We call `console.flowview.mode.set` here https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/consoleaddons.py#L264-L267
When `repl` is `multipart form` or `protocol buffer`, it is splitted into two parts inside. Thus `console.flowview.mode.set` gets more args that it can accept.

Fix a bug with two-words contentview modes

---

examples/simple/custom_contentview.py
mitmproxy/contentviews/__init__.py
mitmproxy/contentviews/auto.py
mitmproxy/contentviews/base.py
mitmproxy/contentviews/css.py
mitmproxy/contentviews/hex.py
mitmproxy/contentviews/image/view.py
mitmproxy/contentviews/javascript.py
mitmproxy/contentviews/json.py
mitmproxy/contentviews/multipart.py
mitmproxy/contentviews/protobuf.py
mitmproxy/contentviews/query.py
mitmproxy/contentviews/raw.py
mitmproxy/contentviews/urlencoded.py
mitmproxy/contentviews/wbxml.py
mitmproxy/contentviews/xml_html.py
mitmproxy/tools/console/common.py
test/mitmproxy/contentviews/test_api.py

**Earlier:**
We pressed `m` and had to choose a necessary shortcut from the string in statusbar.
https://github.com/mitmproxy/mitmproxy/blob/3d4d580975731215d58a629755e94b5913e67dc3/mitmproxy/tools/console/flowview.py#L609-L617
Every contentview had own shortcut. All shortcuts were collected in [`mitmproxy.contentviews.view_prompts`](https://github.com/mitmproxy/mitmproxy/blob/3d4d580975731215d58a629755e94b5913e67dc3/mitmproxy/tools/console/flowview.py#L610)
Now we shouldn't have it, because we use overlay widget to choose necessary contentview.
I didn't find these prompts used anywhere.
**Now** there are cleanup of:
- hotkey prompt in every contentview class (in base class as well);
- all code, which concerns contentview prompts in `mitmproxy.contentviews.__init__.py`;
- …

Hotkeys cleanup. #2877

---

mitmproxy/tools/main.py

I delete `args.options or args.commands`, because it seemes to haven't any effect.
I suppose, the idea was to set other verbosity level and show it in `--options` output. It won't work, because only default options values are collected for output https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/optmanager.py#L404

Fix verbosity mode. Fix #2885

---

mitmproxy/tools/console/commander/commander.py
test/mitmproxy/test_command.py

Previously, quotes would disappear during editing, making it
impossible to enter command arguments with spaces.

Fix an issue with quoting and commands

---

setup.py

pyperclip version 1.6.0 introduces an API change: the class `pyperclip.exceptions.PyperclipException` is moved to `pyperclip.PyperclipException`. As mitmproxy uses the latter, it's better to explicitly declare the requirement.
https://github.com/mitmproxy/mitmproxy/blob/7733252/mitmproxy/addons/cut.py#L144

Explicitly declare pyperclip requirement

---

mitmproxy/net/http/cookies.py
test/mitmproxy/net/http/test_cookies.py

Currently, when mitmproxy parses a Set-Cookie header with no cookie key and value but some attributes, the attribute will be interpreted as the cookie key and value (#2829). This PR fixes the problem by recognizing any string with the character `=` as a valid key/value pair. This also means that, even the attributes can be an empty key/value pair. Of course, this won't happen in legitimate HTTP responses, but the change is in the spirit of being as permissive as possible so we should accept any string that can be interpreted by human.

Parse Set-Cookie header more permissively. Fix #2829

---

CHANGELOG
examples/addons/events.py
examples/complex/README.md
examples/complex/stream_modify.py
examples/complex/xss_scanner.py
mitmproxy/addons/cut.py
mitmproxy/addons/proxyauth.py
mitmproxy/addons/upstream_auth.py
mitmproxy/addons/view.py
mitmproxy/addons/wsgiapp.py
mitmproxy/certs.py
mitmproxy/command.py
mitmproxy/controller.py
mitmproxy/io/compat.py
mitmproxy/net/http/http1/read.py
mitmproxy/platform/windows.py
mitmproxy/proxy/protocol/http.py
mitmproxy/proxy/protocol/http2.py
mitmproxy/proxy/protocol/tls.py
mitmproxy/test/taddons.py
mitmproxy/tools/console/consoleaddons.py
pathod/pathoc.py
test/mitmproxy/net/test_tcp.py

Found via `codespell -q 3 -I ../mitmproxy-word-whitelist.txt`
Where whitelist contains:
```
cas
doubleclick
nd
ot
seeked
statics
te
thru
```

Misc. typos

---

test/examples/test_xss_scanner.py

- Add mock implementation for `gethostbyname` in test_xss_scanner.
- Fix failed tests when running `tox` without an internet connection.
- Fixes #2867

Fix test fails in test_xss_scanner when running tox without internet connection.

---

mitmproxy/utils/arg_check.py

- Fixes #2906 
- Move --socks option from `DEPRECATED` to `REPLACED` in [arg_check.py](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/utils/arg_check.py)

Fix --socks option deprecated info in command line args check.

---

mitmproxy/addons/script.py

This must have slipped through in the first conversion.

script.run takes a path argument

---

mitmproxy/addons/core.py
mitmproxy/connections.py
mitmproxy/proxy/config.py
mitmproxy/proxy/protocol/tls.py
test/mitmproxy/addons/test_core.py
test/mitmproxy/proxy/test_config.py
test/mitmproxy/test_proxy.py

I need 65b8b65 to be backported to 3.0.x as well.

Cleanup ProxyConfig

---

mitmproxy/tools/console/flowview.py

While displaying extra-extra long urls in Flow Detail View, there was a no max_url_len value set causing a n overflow of url on the screen. The fixes get the max_cols from the ui and sets it to max_url_len
- Fixes #2818

Fix for wrapping up extra-long urls in flowdetailview

---

mitmproxy/tools/console/master.py
mitmproxy/tools/console/statusbar.py
test/mitmproxy/tools/console/test_statusbar.py

PR snips any message that came to statusbar to the first line. It also invites users to see more in eventlog according to #1433. 
**P.S.**
https://github.com/mitmproxy/mitmproxy/compare/master...kajojify:shortening?expand=1#diff-5e13e3689fcd12fb5c83c66addc0e13bR99
Sometimes statusbar gets messages with "\n" or "\t" symbols at the beginning. Thus sometimes statusbar shows just `Error: `.  We want more.
Variant | Result
------------ | -------------
1 | ![image](https://user-images.githubusercontent.com/20267977/36923844-3fc11544-1e75-11e8-988e-2c332c7c5055.png)
2 | ![image](https://user-images.githubusercontent.com/20267977/36923888-6225dcd2-1e75-11e8-9fed-a207bdb9083b.png)
3 | ![image](https://user-images.githubusercontent.com/20267977/36924014-b94e92c4-1e75-11e8-9ff2-781bbca104f3.png)
4 | …

Polite shortening of statusbar messages. Fix #1433

---

docs/bucketassets/error.html
docs/bucketassets/robots.txt
docs/build
docs/setup
docs/src/themes/mitmproxydocs/static/css/style.css
docs/style/style.scss
docs/upload-archive
docs/upload-master
docs/upload-stable

This begins to set up the infrastructure for docs.mitmproxy.org. It includes some upload scripts, plus a set of base assets for the domain (robots.txt and error.html). The CDN is not set up yet, so invalidation is commented out for now.
The next step is to have our CI render the docs with ./build, and then upload to master with ./upload-master.

docs: start move to docs.mitmproxy.org

---

mitmproxy/addons/browser.py

Hi,
I am running Arch Linux, with google chrome installed via Arch User repo the executable name is google-chrome-stable. [https://aur.archlinux.org/packages/google-chrome/](url)
This pull request allows for this to work without the error "Your platform is not supported yet - please submit a patch."
Thanks,

Added Support for AUR Google Chrome

---

examples/addons/events.py

The correct class name should be `WebSocketFlow`

events.py typo fix

---

docs/src/content/howto-transparent.md

Fixed typo referencing `en2` when it should mention `en0` on https://docs.mitmproxy.org/stable/howto-transparent/

Fixed Typo in Transparent Proxy Setup for Mac

---

mitmproxy/tools/console/window.py

`--no-mouse` is deprecated. Changed parameter to `--set console_mouse=false`

Fixed --no-mouse parameter message

---

mitmproxy/addons/termstatus.py
mitmproxy/controller.py
mitmproxy/master.py
mitmproxy/proxy/protocol/http_replay.py
mitmproxy/tools/console/master.py
mitmproxy/tools/main.py
mitmproxy/tools/web/master.py
release/README.md
test/mitmproxy/data/addonscripts/shutdown.py
test/mitmproxy/proxy/protocol/test_http2.py
test/mitmproxy/proxy/protocol/test_websocket.py
test/mitmproxy/proxy/test_server.py
test/mitmproxy/test_controller.py
test/mitmproxy/test_flow.py
test/mitmproxy/test_fuzzing.py
test/mitmproxy/tools/test_main.py
test/mitmproxy/tservers.py

This patch shifts mitmproxy's core event loop to asyncio. It also changes both mitmproxy console and mitmweb to run off the same asyncio event loop as core, unifying event handing in the main thread. This is just a first step - there are many obvious next steps that will follow in the weeks to come. 
I used a modified version of the benchmark to pump 1000 requests through each proxy tool with a concurrency of 50. 
Before:
After:
Before (!!!!!):
After:
Before:
After:

shift core event loop to asyncio

---

mitmproxy/proxy/protocol/http.py
test/mitmproxy/proxy/test_server.py

This fixes #3038. The problem with the old implementation is that `self.send_request_headers(f.request)` may not raise, which makes us fail in scenarios where we shouldn't.
If this is successful, we should roll a 3.0.x patch release.

fix http retry timeout

---

mitmproxy/net/tcp.py

I have no idea why we did this, but the default value is 128, and setting it
this low drops connections under conditions our users can reasonably be expeted
to reach.

Remove socket listen backlog constraint

---

mitmproxy/addons/script.py
test/mitmproxy/addons/test_script.py

Hi,
This PR introduces a unified handler which will handle all the user's scripts exception as mentioned in #2962 .
I was finally able to include a short message in the signature which is an optional argument and if it's not provided then the name of the exception type will be printed instead.
The test is a very basic one because of the fact that once merged other tests will do an extensive testing of the function as we move forward to using this function to display error messages. 
Closes #2962

A unified handler for user's scripts exception

---

mitmproxy/addons/script.py
test/mitmproxy/addons/test_script.py
test/mitmproxy/data/addonscripts/recorder/error.py

Hi,
Have used `script_error_handler` to fix #2839.

Handling user script's exceptions, fix #2839

---

mitmproxy/tools/main.py
test/mitmproxy/tools/test_main.py

- Ignore the NotImplementedError raised by add_signal_handler on Windows.
- Entrypoints return an integer exit code, or None. Adjust our type annotations
and code to suit.
Fixes #3061

Ignore signal errors on windows + various fixes

---

mitmproxy/master.py
mitmproxy/tools/console/master.py

- Add a master.run_loop function. This encapsulates our run behaviour so that
it can be used by implementations that need to manage their own run loop (like urwid).
- Shift crash exit message to the common core. I'm not convinced we really need
this, but if we want it it should be centralised.
- Clean up an extra exception that can be thrown by asyncio itself on "dirty"
termination after a mitmproxy crash.

asyncio: fix exit behaviour for console

---

mitmproxy/net/tcp.py

On our proxy server, after adding SO_KEEPALIVE, memory consumption is reduced from 23G to 16G.

add SO_KEEPALIVE

---

mitmproxy/addons/clientplayback.py
mitmproxy/addons/keepserving.py
mitmproxy/addons/readfile.py
mitmproxy/addons/serverplayback.py
mitmproxy/master.py
mitmproxy/test/taddons.py
mitmproxy/tools/console/commandexecutor.py
mitmproxy/tools/console/flowlist.py
mitmproxy/tools/console/flowview.py
mitmproxy/tools/console/statusbar.py
mitmproxy/tools/main.py
test/mitmproxy/addons/test_keepserving.py
test/mitmproxy/addons/test_readfile.py
test/mitmproxy/addons/test_serverplayback.py
test/mitmproxy/test_taddons.py
test/mitmproxy/tools/console/test_statusbar.py

This is a grab-bag of commits that redesigns our keepserving mechanism and deals with its sequelae. The core idea is to move keepserving to a clean implementation that only uses the command mechanism to communicate with other addons. This lets us remove the custom "processing_complete" event, and lets us shift sever replay away from the "tick" mechanism. Together, these changes set the scene for further cleanups, including removing the "tick" event altogether.

Redesign keepserving

---

examples/complex/dup_and_replay.py
mitmproxy/addons/view.py

- Exposes view.add as a command
- Copes with cases where a view addon isn't present
- Avoids infinite loop caused by replaying replays
Fixes #3096

Revamp dup_and_replay example

---

mitmproxy/addonmanager.py
test/mitmproxy/test_addonmanager.py

These were always weird, and were added to support exit when processing
completed to mitmdump. We now have better ways to do this.

Remove custom events

---

mitmproxy/addons/readfile.py
test/mitmproxy/addons/test_readfile.py

This broke `mitmdump -nr empty`.

Remove leftover processing_complete

---

examples/complex/har_dump.py

When I was reading this example, I didn't know how to use it. The methods used on the Internet have expired, such as `mitmdump -s "./har_dump.py ./out.har"`. Later, after reading the document carefully, I learned how to use it. So I want to write usage in the file so that others can use it.

add har_dump example cmdline invocation

---

.appveyor.yml
.travis.yml
docker/Dockerfile
docker/README.md
docker/docker-entrypoint.sh
release/README.md
release/cibuild.py
tox.ini

The plan is to ditch the "automated build" feature of Docker Hub, and instead build & push our own images. We use Travis to perform this, the same way we already build our wheels and pyinstaller files and upload them. This means we do not need the separate docker-release repository any more, and our release check-list shrinks as well, because we don't need to update and tag and push in a second repo any more.
This PR contains general improvements and cleanup things regarding our release workflow.

add docker to the main repository

---

release/cibuild.py
setup.cfg
test/release/test_cibuild.py
tox.ini

Pull all the cibuild state management and computation into a testable class. Isolate environment access to a single function. Add unit tests simulating common CI scenarios. General cleanups.
There's more to be done, but this is a good start.

Tame cibuild (somewhat)

---

mitmproxy/optmanager.py
mitmproxy/tools/console/options.py

The existing options for the console were not being updated when a new
addon was added. This triggers the changed blinker signal when an option
is added, and also recreates self.opts when this signal is received.
Fixes #3147

Adjust options when changed

---

release/cibuild.py
test/release/test_cibuild.py

Cater for the corner case where commits are incorporated on a maintenance
branch. We should be able to test these without adding a dev suffix to the tool
versions.

cibuild: permit non-dev versions on maintenance branches

---

mitmproxy/stateobject.py
test/mitmproxy/test_stateobject.py

An ugly solution for an ugly little problem. This patch uses JSON's type
checker to validate Any values in stateobject, in order to avoid a circular
import of tnetstrings.
This is a temporary solution - stateobject is going to go away entirely once the new serialization is in place. 
Fixes #3180

Add typechecking of Any values for state object

---

examples/complex/dns_spoofing.py

Hello!
I found that the CLI usage comment is not up to date while updating to mitmproxy 4.

Update CLI usage instructions for dns_spoofing example

---

mitmproxy/tools/web/app.py

This PR attempts to guard mitmweb against DNS rebinding attacks. 
See also:
- https://github.com/mitmproxy/mitmproxy/issues/3234
- http://www.tornadoweb.org/en/stable/guide/security.html#dns-rebinding
@atx: My understanding is that enforcing the hostname to match `'(localhost|\d+\.\d+\.\d+\.\d+)'` should effectively mitigate this while still enabling users to access mitmweb from other hosts if they so desire. Do you see errors in my thinking?
In the long term we should probably adopt a jupyter-style solution, but it's more important to get this fixed quickly now.

mitmweb: protect against dns rebinding

---

mitmproxy/tools/console/commander/commander.py
mitmproxy/tools/console/statusbar.py
test/mitmproxy/tools/console/test_commander.py

This PR implements command history. It tries to work similar to the history in the ubuntu terminal.
1. Start mitmproxy.
2. Press `:` and start typing in the status bar.
3. Input a few commands.
4. Press `up` button to see previous command if available. Press `down` button to see next command. 
**A few moments to know.** 
The history contains of `CommandBuffer` objects, not text objects. It was done in order to save cursor position and autocompletion state.
When we press `up` button, the command buffer currently typed in the status bar will be saved to the command history. But if the last history buffer has the same text as the current one buffer, the last buffer will be replaced with the current one. We can also add command with `execution` param. It will mean, whenever we decide to …

Command history

---

test/bench/serialization-bm.py

A cleaner and updated addon to test performance of protobuf module.
Right now, the addon: 
- Constantly generates flows with optional size content;
- Periodically gathers generated flows in bunch of N=150;
- Measures time to dump, and store in DB, the bunch;
- Write stats to file (in the form of num_dumps / time_spent) and exits.
Any idea you'd want to see realized here to improve this profiling? Or more, something you feel is not correct in the benchmark process, which makes it not reliable?  
I felt it was necessary to clean and use this, since protobuf interface has evolved more complex, and I had to make sure that performances stayed on par.

Protobuf - Benchmark Script

---

mitmproxy/language/lexer.py
mitmproxy/language/parser.py
test/mitmproxy/test_command.py

Support for the new features:
1. Chained commands. 
We can chain commands for example like `abc.command(1 2 3 def.command(4 5 ghi.command()) 6)`. 
Calling command with parentheses means that the outermost command will use the return of this command as a value for the corresponding argument.
2. Arrays.
We can use more familiar notation for arrays now. So, earlier it was `elem1,elem2,elem3`, now it is `[elem1 elem2 elem3].` Yes, it still works like conversion from `elem1,elem2,elem3` under the cover. It will be changed in the next PRs.
My next step is to rewrite the current commands and default key bindings relying on the provided changes.

Brackets support

---

mitmproxy/language/lexer.py
mitmproxy/language/parser.py
test/mitmproxy/test_command.py
test/mitmproxy/test_types.py

Hello everyone!
This PR provides basic pipes support.
As we discussed earlier pipes syntax is just a syntactic sugar.
`@focus | replay.client` is the same as `replay.client @focus` or `replay.client(@focus)`
Pipes are just moving the resulting value from the left-hand side  to the right-hand side command as the first argument. One more example:
`console.choose Part [request response] | cut.clip @focus` is the same as 
`cut.clip console.choose(Part [request response]) @focus`
**Implementation details**
Pipe elements are executed one by one from left-hand side to the right-hand side, like in this picture:
As soon as the result of the particular pipe element is given, we save it into `self._pipe_value`. In other words, `self._pipe_value` stores the current pipe element value.
As soon as the …

Pipes initial support

---

mitmproxy/certs.py

Helps with Chrome's "certificates can not be valid longer than 27,5 month"
Fixes #3273

Add DEFAULT_EXP_DUMMY_CERT and set to two years

---

web/src/js/__tests__/ducks/flowsSpec.js
web/src/js/ducks/flows.js

Correct the outdated API for `uploadContent`.

[web] Fixes #3228:API endpoint error

---

mitmproxy/addons/session.py
mitmproxy/io/protobuf.py
mitmproxy/io/sql/session_create.sql
test/mitmproxy/addons/test_session.py

Here we are, this is a crucial step in the development of the Session addon. Considering this, I would appreciate so much any critic, review and comment which can ensure this piece of work to meet the standard quality of the codebase.
This PR contains code to implement, in Session, the following features:
- View (as ordered list of ids);
- View (re)ordering / (re)filtering;
- Storage layer (both in memory, for flows not flushed, and on disk);
- Logic to capture flows -> save them to hot flows -> periodically flush flows to disk -> retrieve them;
- Logic to detect for updated flows already in state, and to replace them opportunely in storage;
- An initial strategy to adapt flush parameters to the incoming load (much prone to improvements);
I've sketched down how the logic behind the …

Session - Storage Layer

---

mitmproxy/command.py
mitmproxy/exceptions.py
mitmproxy/language/lexer.py
mitmproxy/language/parser.py
mitmproxy/language/traversal.py
mitmproxy/optmanager.py
mitmproxy/tools/console/commandexecutor.py
mitmproxy/tools/console/commands.py
mitmproxy/tools/console/consoleaddons.py
mitmproxy/tools/console/defaultkeys.py
mitmproxy/tools/console/keymap.py
mitmproxy/tools/console/overlay.py
test/mitmproxy/language/test_traversal.py
test/mitmproxy/test_command.py
test/mitmproxy/test_optmanager.py
test/mitmproxy/tools/console/test_defaultkeys.py

Hi there! This PR makes initial steps porting the current command system to asyncio. Some parts don't work correctly yet (like `console.key.bind`). And yes, I understand, that copying the same code in two different places is the last thing we want to do :) But after reading some documentation and stackoverflow answers, I understood, that dealing with sync and async code in one function isn't a good idea. So sometimes you can see two functions/methods, which do the same thing: one does synchronously, the other - asynchronously. 
As you remember, my last PR provided pipes support. Now the main features of the language are more or less in the workable state, but the thing is our commands and types checking implementations aren't adapted to the ideas of these features. I will give you an …

Async commands support

---

setup.py

See https://bitbucket.org/ruamel/yaml/issues/234/ruamelyamlsafe_load-includes-a-in-folded

Pin ruamel.yaml to working version

---

mitmproxy/addons/browser.py

On archlinux, if you install `google-chrome-dev` from AUR, the chrome binary is called `google-chrome-unstable`. It shouldn't hurt to try if everything else fails.

addons/browser: fallback to google-chrome-unstable as last try

---

docs/src/content/howto-ignoredomains.md

This PR fixes the documentation about domains whitelisting. Previous pattern did not work, and solution was given by @mhils in #2994.
I don't think this should close this ticket as there should be a clear way to specify if the pattern should match the IP address and/or the domain, but at least, this PR prevents confusion and gives a workaround.

Fixed doc about domain whitelisting

---

mitmproxy/contentviews/__init__.py
mitmproxy/contentviews/base.py
mitmproxy/options.py
mitmproxy/tools/console/flowview.py

Currently mitmproxy by default limits a flow content to 512 lines. This PR makes that cutoff configurable.

Make content view lines limit configurable

---

docs/src/content/concepts-certificates.md

In the page https://docs.mitmproxy.org/stable/concepts-certificates/, there is usage of mitm.it and it is not a link which seems odd on reading through the documentation. This PR adds the link to the usage.

docs: Add mitm.it link in the certificates docs.

---

.gitignore
mitmproxy/certs.py
mitmproxy/proxy/protocol/tls.py
test/mitmproxy/test_certs.py

Some clients (for example, the client below) will check organization fields`(O)` to avoid fake certificate generated by others. So I chang the tls layer and cert store to support the organization field`(O)` in the generated certificate.
So far, the organization field`(O)` will be duplicated from the original certificate from server.
> Though unbelievable, some clients check their certificate by its Organization field.

Add Organization field for the generated certificate

---

mitmproxy/certs.py
mitmproxy/proxy/protocol/tls.py
test/mitmproxy/test_certs.py

Follow up for PR #3376 as per [comment](https://github.com/mitmproxy/mitmproxy/pull/3376/#issuecomment-437286850) , replacing the variable `o` with `organization`.

Change variable o to organization for generated certficates.

---

mitmproxy/contentviews/base.py
mitmproxy/contentviews/query.py
mitmproxy/contentviews/urlencoded.py
test/mitmproxy/contentviews/test_base.py
test/mitmproxy/contentviews/test_query.py

Fix for #3072 and #3254 
Added `format_pair` function and changed the implementation of `format_dict`.
Did relevant changes in urlencoded.py

Query array fix

---

web/src/js/ducks/ui/keyboard.js

I tested `e.metaKey` and it returns `true` when the command key is pressed.
resolves #2910

fixes copying on macos

---

docs/src/content/howto-transparent.md

divert-to does not work with '0.0.0.0' or similar listen address, so we
need to specify listen address that we provided to `pf`.

openbsd: divert-to requires exact listen address

---

test/mitmproxy/test_proxy.py

Apparently macOS Mojave allows non-root users to bind ports < 1024. Similar reports:
* https://github.com/nodejs/node/pull/23550/files
* https://news.ycombinator.com/item?id=18302380

Fix a failing test on macOS Mojave

---

README.rst

I think this can be useful for contributors if they want to find out which lines they are missing while testing individual files.
I know we can do this using `tox -- --verbose --cov-report=term`. But for speedier testing this might come in handy.
Any thoughts?

Suggestion: Update Readme to improve testing 

---

docs/src/content/howto-transparent.md

Hey folks,
I was configuring mitmproxy as a transparent proxy on macOS and found this minor issue in the documentation, so I decided to just go ahead and open a quick PR fixing them. Should take just a couple of minutes to review.

Doc fix regarding transparent proxy on macOS

---

mitmproxy/net/http/cookies.py
mitmproxy/net/http/response.py
test/mitmproxy/net/http/test_response.py

This fixes issue #3502 by using the usegmt argument for email.utils.formatdate.  
https://docs.python.org/3/library/email.utils.html#email.utils.formatdate
https://docs.python.org/2/library/email.utils.html#email.utils.formatdate
> Optional usegmt is a flag that when True, outputs a date string with the timezone as an ascii string GMT, rather than a numeric -0000. This is needed for some protocols (such as HTTP). This only applies when localtime is False. The default is False.

Fix #3502 by using email.utils.formatdate's usegmt argument.

---

setup.py
tox.ini

brotlipy is stuck at brotli 0.6 and upstream is inactive. Let's switch
to the official binding which is up-to-date and has same interfaces.

Use Brotli instead of brotlipy

---

docs/src/content/howto-wireshark-tls.md

Fixed a typo in describing the master keys. `SSL/SSL` -> `SSL/TLS`

Typo in howto-wireshark-tls.md

---

mitmproxy/tools/_main.py
mitmproxy/tools/cmdline.py

This removes the deprecated `--confdir` argument from the `--help` output, and no longer accepts the value even if specified.

Remove the confdir argument

---

mitmproxy/addons/core.py
mitmproxy/net/http/encoding.py
mitmproxy/net/http/message.py
mitmproxy/net/http/request.py
setup.py
test/mitmproxy/net/http/test_encoding.py

```
Handles zstandard-compressed bodies labeled as zstd.
```
I doubt this is all that common, but I did run into zstd in the Twitter Android app and adding support for it was trivial enough.

Add support for zstd Content-Encoding

---

examples/complex/har_dump.py

the HAR file spec (http://www.softwareishard.com/blog/har-12-spec/#timings) states that timings that do not apply for a certain requests should be set to -1, this example may set -1000 as a timings value for certain requests.
This ends up producing invalid HAR files in many cases.
My proposed fix is to assign -1 into the dic and only multiply by 1000 for other values

Updated har_dump,py timings dictionary function

---

mitmproxy/tools/console/common.py
mitmproxy/tools/console/flowlist.py
mitmproxy/tools/console/flowview.py
mitmproxy/tools/console/palettes.py

- Present the flow list as a table with one line per flow, instead of two or more rows
- Use a combination of fixed-width and variable-width columns to present flow properties
- Indicate field truncation appropriately using an ellipsis
- Colour each column individually according to its content
- Request type: spot POST or other (OPTIONS, HEAD) requests easily
- Protocol: spot insecure connections easily
- Hostname: right-align to give priority to top-level domains instead of subdomains
- Content-type: colour according to general category
- Size and duration: use a gradient (with full colour range on high-colour terminals) to spot slow / large requests
Current version only includes palette colour entries for the Dark and SolarizedDark (default) palette.

[RFC] Tabular flow list

---

mitmproxy/tools/web/app.py

I am using mitmweb and on clicking to "Verify server certificates"
I investigated the problem and the "ssl_insecure" option was missing from the "option_whitelist".
The same setting could be toggled from the option popup:
Now it works from both places.
This should fix the following issue: #3625

ssl_insecure added to option_whitelist because it was missing

---

docs/src/content/howto-transparent.md

As mentioned in https://github.com/mitmproxy/mitmproxy/issues/3255
Didn't find out how to deal with the ```redir_users = "{ !=" $tproxy_user "}"``` syntax, and I removed it 😅 , feel free to enlight me

fix pf.conf on macOS

---

mitmproxy/flowfilter.py
test/mitmproxy/test_flowfilter.py

Fixes #2951 
Hi! Initially I thought this should be easy to fix but struggled due to wrong approach. Later I found that `pyparsing`  included several unicode character ranges that can help to set non-ascii filters.
Would be Glad to add if I missed something.

filter unicode fix

---

mitmproxy/net/http/url.py
test/mitmproxy/net/http/test_url.py

Checks non ascii characters in url and escapes/quotes them using `urllib.parse.quote`
Fixes #2272 and #3439

Non ascii characters in url

---

mitmproxy/tools/console/consoleaddons.py

Fixes: #3288 
Since URLs can be long and unwieldy they should be edited in an external editor instead of in the action bar.

Edit URLs in external editor

---

docs/src/content/howto-transparent-vms.md

Newer versions of Ubuntu have more dependencies on systemd. The names of the interfaces changed and systemd-resolved provides a stub DNS provider that interferes with dnsmasq. This commit/PR makes some adjustments in order to provide instructions for newer Ubuntu versions.

Update howto-transparent-vms.md for newer versions

---

mitmproxy/certs.py
mitmproxy/options.py
mitmproxy/proxy/config.py
mitmproxy/tools/cmdline.py
pathod/pathod.py
test/mitmproxy/test_certs.py

While using `mitmproxy` on a remote server I noticed that it uses the pre-defined `2048` bit key size for CA and also interception certificates.
A higher bit size would be better especially when testing with remote instances. /paranoia
I modified this manually for my use case but thought it would make sense to have this as an option as well.  Please review.

Add key_size option to define rsa key size

---

mitmproxy/certs.py

An attempt to fix https://github.com/mitmproxy/mitmproxy/issues/3649 (I have not been able to test it functionally yet with iOS 13)
From: https://support.apple.com/en-gb/HT210176
> TLS server certificates must contain an ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.
Relevant information: 
- https://community.letsencrypt.org/t/extendedkeyusage-tls-client-authentication-in-tls-server-certificates/59140
- https://letsencrypt.org/documents/isrg-cps-v2.0/

Add EKU extension for dummy certificates

---

docs/README.md

Wanted to build docs according to quick start and noticed that you have to run ./build-current script in order to start hugo

hugo server -D fails if html file in docs/src/generated are not present

---

mitmproxy/addons/clientplayback.py

If the `:authority` header is not found, we can try to guess it from
variable `flow.request.pretty_host` as .pop() accepts a fallback
parameter.

fixes #3559

---

docs/src/content/howto-install-system-trusted-ca-android.md

It took me some time to figure out these steps, so I wanted to share them.
I also saw a discussion about that here: #2054 
The procedure was tested with API Level 24, 27 and 28.
As I am not a native English speaker, please feel free to improve my spelling/wording.
Cheers!

Add howto insert mitmproxy CA cert into the android system certificate store

---

mitmproxy/flowfilter.py
setup.cfg

This PR fixes some minor flow filter issues:
- don't double-unescape `\` for binary filters
- simplify unicode logic
- replace deprecated usage of `pyparsing.operatorPrecedence`
/cc @typoon

Improve flowfilter

---

mitmproxy/addons/serverplayback.py

This PR takes the non-controversial changes from #3086.

allow server replay functionality to run on a different port

---

mitmproxy/tools/_main.py

Currently hitting q inside of mitmproxy prompts the user before quitting. Ctrl-C should match that behavior and prompt the user before quitting.

Ctrl-C should prompt the user before exiting

---

README.rst
docs/src/content/overview-installation.md

Prompted by @ylmrx's #3715 regarding the same issue, here's a counter-proposal. This simplifies install instructions in the following ways:
- Replace pip3 installation instructions with [pipx](https://pipxproject.github.io/pipx/). This is much less overhead for users unfamiliar with the Python ecosystem. I've used it a couple of times in the last months and was overall _very_ happy with how pipx performed.
- Fix location of binary packages. We now just link to mitmproxy.org, which has the big OS-specific download button.
- Streamline development setup a bit. Invoking `tox` to test _all_ Python versions more confusing than anything else, `tox -e py` and `tox -e lint` are more adequate.
@ylmrx, would that also address your concerns?

Simplify install instructions

---

mitmproxy/tools/console/commander/commander.py

Added some navigation keys to the command bar to imitate Linux terminals.
Ctrl+A or Home: Go to the beginning of the line.
Ctrl+E or End: Go to the end of the line.
Alt+B: Go left (back) one word.
Ctrl+B: Go left (back) one character.
Alt+F: Go right (forward) one word.
Ctrl+F: Go right (forward) one character.

Commander bar navigation keys 

---

mitmproxy/addons/__init__.py
mitmproxy/addons/command_history.py
mitmproxy/command.py
mitmproxy/tools/_main.py
mitmproxy/tools/console/commander/commander.py
mitmproxy/tools/console/statusbar.py
mitmproxy/utils/debug.py
test/mitmproxy/addons/test_command_history.py
test/mitmproxy/tools/console/test_commander.py

This is the implementation of a feature that saves all user executed commands (`:` prompt) to a file so that the next time they open mitmproxy those commands are already in their command history.
This has been pretty useful for me when testing issues that would cause mitmproxy to crash (so I didn't have to re-type a bunch of commands again). It has also been pretty useful for the cases when I have to close mitmproxy for any reason during my workflow and reopen it and continue where I left of.

Save user executed commands to a history file

---

web/src/js/components/ContentView/ContentViews.jsx

[WebP is an image format](https://en.wikipedia.org/wiki/WebP) employing both lossy and lossless compression. As a derivative of the VP8 video format, it is a sister project to the WebM multimedia container format. The canonical Internet media type is `image/webp` and is currently [supported by the major web browsers](https://caniuse.com/#feat=webp).

Fix #3571 to support image/webp in mitmweb to display previews

---

setup.py

This marks the package as annotated to allow it's types to be inferred by [mypy][1] when used as a library some another application. More details about this in [PEP-561][2].
Without this, running mypy on some code that uses mitmproxy returns these errors:
```python
test_stubs.py:1: error: Cannot find implementation or library stub for module named 'mitmproxy'
test_stubs.py:2: error: Cannot find implementation or library stub for module named 'mitmproxy.net.http'
test_stubs.py:3: error: Cannot find implementation or library stub for module named 'mitmproxy.utils'
```
Once I added this to the package and installed the latest dev version, the errors are removed. Unfortunately, in some other modules I see these errors:
```python
/Users/pavel.savchenko/.virtualenvs/stub_test/lib/python3.6/site- …
```

Add py.typed stub as per PEP-561

---

mitmproxy/tools/_main.py

Catching SIGTERM and prompting for exit instead of just shutting down is pretty annoying.
I have scripts to manage mitmproxy, and this behavior was preventing them from working.

Exit on SIGTERM instead of prompting

---

mitmproxy/command.py
mitmproxy/tools/console/commandexecutor.py
mitmproxy/tools/console/consoleaddons.py
mitmproxy/types.py

This PR fixes several issues I've encountered while using mitmproxy in console mode:
1. Trying to manually change to "multipart form" contentview failed because ViewMultipart.name has a space in it. This also affected my custom contentview, so I had to choose a name without spaces.
2. Said error was not visible in the event log, just in the status bar (where it wasn't even informative because it just said "(more in eventlog)"...)
3. When I did manage to show the full exception in the event log, tabs ('\t') were displayed as '?'.
4. A re-raised error (when I run a command with an "invalid choice") would display an empty error string because it was raised like this: `raise exceptions.CommandError from e`
I solved (1) by exposing CommandManager.call_strings and calling it directly, because …

Fix console command quotes issues

---

docs/src/content/tute-clientreplay.md

Foxyproxy is a commonly used Firefox addon with more than 180k users. Would this be a good replacement for Toggle Proxy?

Fix broken link with link to similar addon. This fixes issue #3775.

---

mitmproxy/proxy/protocol/http2.py
test/mitmproxy/proxy/protocol/test_http2.py

I am simulating interrupts during http2 responses for Wget2's test suite, while using mitmproxy to debug some of the tests that are not working. 
RST_STREAM frames were received by mitmproxy from the server, but were not sent to the client from mitmproxy. As this is inconsistent with what happens when the proxy is disabled, I have modified mitmproxy to send all stream resets from server to client (and probably client to server) to correct this.

http2: send all stream reset types to other connection

---

mitmproxy/addons/onboardingapp/templates/index.html

This change will make sure that a user can click
on a link to install the CAs even if displaying
the logos fails.

onboardingapp: Fix bugs 3397,3034 & link pems properly

---

mitmproxy/proxy/config.py

The "not" with "any" statement mistaken if the expect behavior of --allow-hosts is that only allow host matched any given regex.

Fix wrong behavior of --allow-hosts options

---

docs/src/content/tute-clientreplay.md

In mitmproxy -c file command -c is replace with -C but docs still shows -c

c is deprecated

---

mitmproxy/proxy/protocol/base.py

Fixes #3880
It looks like there are no tests for events so far? I'm not familiar with Python especially testing frameworks and stuff. But I guess it makes sense to look into that?

Only emit "serverconnect" after successfully connecting

---

mitmproxy/net/http/http1/assemble.py
test/mitmproxy/net/http/http1/test_assemble.py

It is not really clear why we did this, so we stop doing this and see who complains.

Don't force host header on outgoing requests

---

mitmproxy/certs.py

Safari will, later this year, no longer accept new HTTPS certificates that expire more than 13 months from their creation date.
#3748 was a helpful reminder that we need to do this.

Reduce leaf certificate lifetime to one year

---

mitmproxy/tools/console/keymap.py
test/mitmproxy/tools/console/test_keymap.py

When reading `keys.yaml` file for a specific key and context, instead of removing all contexts bound with this key, it will only overwrite the specific context. This change allows user to bind 1 key with different commands for different contexts.

#3911 Support keybinding for different contexts with different commands

---

release/cibuild.py

@Kriechi: Docker CI doesn't run for external PRs because it is too slow and only tests the deploy, so if we work on that we need to use branches on mitmproxy/mitmproxy.

Fix docker smoke test

---

mitmproxy/addons/clientplayback.py
mitmproxy/addons/view.py
mitmproxy/flow.py
mitmproxy/http.py
mitmproxy/tcp.py
mitmproxy/tools/console/common.py
mitmproxy/tools/console/consoleaddons.py
mitmproxy/tools/console/flowdetailview.py
mitmproxy/tools/console/flowlist.py
mitmproxy/tools/console/flowview.py
mitmproxy/tools/console/palettes.py
test/mitmproxy/addons/test_clientplayback.py
test/mitmproxy/addons/test_view.py
test/mitmproxy/test_http.py
test/mitmproxy/tools/console/test_common.py

This PR adds a very simple TCP Flow UI based on the fabulous work by @Jessonsotoventura and @nikitastupin. Thank you two!
- I've taken Nikita's PR and added the most important bits from Jesson's PR, as that seemed easier than removing the TCPViewEntry stuff in there. The end result is somewhere in the middle.
- After delving into the code I got a bit sidetracked with fixing the terrible mess of `format_flow` and its descendants¹. Two main changes here: First, I've removed the two_line/extended/layout convolution and replaced with it with a single RenderMode enum that signals in which context we're currently rendering. Second, I've removed the awful dict-passing code and replaced it all with explicit variables. This may seem verbose, but allows us to do proper typechecking, which makes the …

TCP Flow UI

---

examples/simple/wsgi_flask_app.py

`example/simple/wsgi_flask_app.py` uses a magic domain `proxapp.local` which cannot be resolved on OS X hosts. This is because Apple uses `.local` as a reserved domain for device discovery in Bonjour's mDNS. 
Reference: https://support.apple.com/en-us/HT207511
Environment: OS X 10.5.2 + mitmproxy 5.1.1
1.  Directly load `wsgi_flask_app.py` example on a OS X host 
```
> mitmproxy --mode transparent --showhost -s examples/simple/wsgi_flask_app.py
```
2. Visit `http://proxapp.local` in Chrome. An `ERR_NAME_NOT_RESOLVED` error is shown.
It seems OS X will always route `.local` domain to Bonjour's mDNS before passing it through a mitmproxy (even if it's running in global transparent mode).
3. Open `wsgi_flask_app.py` and change the magic domain to `example.com`
4. Open chrome and visit …

Improve compatibility of wsgi_flask_app example on OS X

---

mitmproxy/contentviews/__init__.py
mitmproxy/tools/console/common.py
mitmproxy/tools/console/flowview.py
mitmproxy/tools/console/palettes.py

Hey! Just did Step 2 of https://github.com/mitmproxy/mitmproxy/issues/1020#issuecomment-609906840. Here is how it looks like on a real MQTT connection.
Raw contentview:
Hex contentview:

Integrate contentviews to TCP flow details

---

mitmproxy/tools/console/consoleaddons.py

When opening command console by tapping a shortcut, there is no space after prefilled command string, the user has to type a `space` first then user input. For example:
- Type `w` in mitmproxy flow view, see console:
```
: save.file @shown█
```
(█ is current cursor position)
To enter the path `~/test`, user has to enter a `space` first:
```
: save.file @shown ~/test█
```
It's a bit inconvenient every time to type the additional `space`...
After this commit, a `space` is inserted after command string and the initial cursor position is:
```
: save.file @shown █
```

Add a space after prefilled console command string

---

mitmproxy/websocket.py

Closes #3986
To test backward compatibility, I did the following:
```shell
$ mitmdump -w stable.mitmdump -q
$ mitmdump -w patched.mitmdump -q
$ cat ws.py
from mitmproxy import ctx
def websocket_message(flow):
message = flow.messages[-1]
ctx.log.info(repr(message.get_state()))
if message.from_client:
ctx.log.info(f'Client sent a message at {message.timestamp}: {message.content}')
else:
ctx.log.info(f'Server sent a message at {message.timestamp}: {message.content}')
$ mitmdump -nr stable.mitmdump -s ws.py -v >stable.out_stable
$ mitmdump -nr patched.mitmdump -s ws.py -v >patched.out_stable
$ mitmdump -nr stable.mitmdump -s ws.py -v > stable.out_patched
$ mitmdump -nr patched.mitmdump -s ws.py -v > patched.out_patched
$ diff -qs stable.out_*
Files stable.out_patched and stable.out_stable are …
```

Record float timestamp for WebSocket messages instead of truncating to int

---

docs/src/content/howto-kubernetes.md

This references a project I recently released which automates proxying Kubernetes Services using mitmproxy: https://github.com/soluble-ai/kubetap
Thanks for all your hard work, without which Kubetap wouldn't exist!
Feel free to amend the weight.

Add Kubernetes HOWTO to docs

---

mitmproxy/net/http/response.py
test/mitmproxy/net/http/test_response.py

Fixes an error triggered when displaying an HTTP2 response loaded from a file.
Using this script saved as `reason_none.py`:
```
from mitmproxy.io import protobuf
def response(flow):
repr(protobuf.loads(protobuf.dumps(flow)))
```
Run:
```
$ mitmdump --save-stream-file google.flow
<in another terminal>
$ curl -k --http2 --proxy localhost:8080 https://google.com
```
Crashes:
```
$ mitmdump --rfile google.flow --script reason_none.py 
Loading script reason_none.py
Proxy server listening at http://*:8080
[::1]:51048: GET https://google.com/ HTTP/2.0
<< 301  220b
Addon error: Traceback (most recent call last):
File "reason_none.py", line 4, in response
repr(protobuf.loads(protobuf.dumps(flow)))
File "/Users/rbdixon/src/mitmproxy/mitmproxy/http.py", line 174, in __repr__
return …
```

HTTP2 response reason is None, render as '' in property.

---

mitmproxy/tools/web/webaddons.py

[`wslview`](http://manpages.ubuntu.com/manpages/eoan/man1/wslview.1.html) is a utility that ships with the newer versions of WSL as a way of opening links in the default web browser on the Windows host.

Support using `wslview` as a browser to open web url

---

docs/src/content/concepts-modes.md

I couldn't find anywhere in the docs that said what port mitmproxy runs on, or how to find out which port it runs on, so I think it would be good to add it to this page.

Document default listen port is 8080

---

docs/src/content/concepts-protocols.md

I just fixed the link attached to wsproto.

the link of wsproto was not displayed right.

---

README.rst
docs/modd.conf

The docs generation fails with 2 errors on Ubuntu 18.04:
```
❯ modd
16:10:34: prep: build.sh
"build.sh": executable file not found in $PATH
exit status 1
16:10:34: daemon: cd src; hugo server -D
>> starting...
Error: Error building site: TOCSS: failed to transform "style.scss" (text/x-scss): resource "scss/style.scss_b95b077eb505d5c0aff805
5eaced30ad" not found in file cache
Building sites … Built in 28 ms
exited: exit status 1
```
The first error from modd is fixed by adding `./`to the path.
The second error is fixed by using the extended version of hugo, see https://discourse.gohugo.io/t/tocss-ressource-not-found-in-file-cache/24858

fix docs generation

---

docs/src/content/overview-features.md
mitmproxy/addons/__init__.py
mitmproxy/addons/modifyheaders.py
mitmproxy/addons/setheaders.py
mitmproxy/tools/cmdline.py
mitmproxy/tools/console/statusbar.py
test/mitmproxy/addons/test_modifyheaders.py
test/mitmproxy/addons/test_setheaders.py
test/mitmproxy/tools/console/test_statusbar.py

This PR improves the `SetHeaders` addon with 3 changes:
1) The flow-filter is now the last parameter in the configuration pattern, as it is optional.
2) The user can now remove existing headers by specifying an empty `header-value`.
3) Updated docs to reflect changes.
refs #3948

Improve SetHeaders addon

---

test/mitmproxy/tools/console/test_commander.py

`tctx` clashes with an omnipresent fixture on my sans-io branch and my IDE is not smart enough to figure out which one is which.

minor: rename pytest fixture

---

.github/pull_request_template.md
CHANGELOG

as discussed with @mhils, we should keep the changelog up2date at all times to avoid this daunting task before cutting a release.
This PR adds all recent PRs since the last release to the changelog.
This PR adds a PR template to instruct users to add new changelog entries directly into their newly sent PRs.

Update changelog and add PR template

---

CHANGELOG
docs/src/content/overview-features.md
mitmproxy/addons/__init__.py
mitmproxy/addons/mapremote.py
mitmproxy/tools/cmdline.py
test/mitmproxy/addons/test_mapremote.py

Added a new addon (`MapRemote`) to rewrite URLs of requests before the request is performed.
refs #3948

add mapremote addon to modify request URLs

---

.github/workflows/main.yml

This happens quite a bit, so let's stop failing tests for that.

Don't fail on covecov errors

---

mitmproxy/tools/console/commander/commander.py
test/mitmproxy/tools/console/test_commander.py

Options was not cycled right for tab auto-completion. Using tabs and shift-tabs mixed up when you are in cut.clip for instance. You would see the options just don't go back right when you press shift-tab, and it wouldn't go forward right for some occasion caused by the same bug. 
The code before did not even care if tab or shift tab was pressed and set the previously calculated position as the new position of the options, then calculate the next position after it. 
So fix was fairly simple. Check if tab or shift tab was pressed and calculate the new position according to it. A little difficult part was how to deal with the first time the tab or shift tab was pressed, but it could be handled by setting sys.maxsize as the initial value for the position.
Probably the code itself would …

List was not cycled right for tab auto-completion

---

mitmproxy/utils/typecheck.py
test/examples/test_examples.py
test/mitmproxy/utils/test_typecheck.py

Fix #4059 
The file examples/addons/options-configure.py uses typespec "typing.Optional[int]"  which was not implemented in typespec_to_str function.
So, I implemented it.

Fix typespec_to_str funcion to process typing.Optional[int]

---

CHANGELOG
mitmproxy/certs.py

Fix #4057 
I changed iteration to list comprehension in order to prevent "RuntimeError: dictionary changed size during iteration" in the "expire" function of "mitmproxy/certs.py"

Fix "RuntimeError: dictionary changed size during iteration" in the "expire" function of "mitmproxy/certs.py"

---

mitmproxy/net/tcp.py

Fix #4028 
The socket.gettimeout function returns None when timeout value isn't set by the socket.settimeout function.
I added a default timeout value for the situation that socket.gettimeout function returned None.

Added default timeout value

---

mitmproxy/addons/clientplayback.py

Fix #4037 
When we execute the command "replay.client.stop", this function is called.
```@command.command("replay.client.stop")
def stop_replay(self) -> None:
with self.q.mutex:
lst = list(self.q.queue)
self.q.queue.clear()
for f in lst:
f.revert()
ctx.master.addons.trigger("update", lst) 
ctx.log.alert("Client replay queue cleared.")
```
In this function, "ctx.master.addons.trigger("update", lst)" is called inside "with self.q.mutex".
This causes a deadlock.
So, I moved "ctx.master.addons.trigger("update", lst)" outside of "with self.q.mutex"

Fix deadlock caused by the "replay.client.stop" command

---

docs/src/content/howto-transparent.md

In the title _Work-around to redirect traffic originating from the machine itself_, the command `sudo` is used without the flag `-H`. 
As stated by `sudo` manual :
> -H, --set-home
Request that the security policy set the HOME environment variable to the home directory specified by
the target user's password database entry.  Depending on the policy, this may be the default behavior.
Without this flag, in some Linux distros (I tested on Ubuntu 16.04), pip will try to install `mitmproxy` in the home directory of the user launching the command, and not in the directory of the user _mitmproxyuser_

Command that can generates errors in the documentation

---

mitmproxy/addons/intercept.py
mitmproxy/tools/console/consoleaddons.py
mitmproxy/tools/console/flowview.py
test/mitmproxy/addons/test_intercept.py

Hi team, 
In this pull request I've implemented MVP for Step 3 of https://github.com/mitmproxy/mitmproxy/issues/1020#issuecomment-609906840. Right now it allows to intercept and modify TCP messages. However I suppose that we need to add several cosmetic features to this pull request which will greatly increase usability:
@mhils , any additional features from your side? Feedback on above list of features will be helpful too.
P.S. Slowly but surely #1020 moves to an end 😃

Add minimal TCP interception and modification!

---

mitmproxy/contrib/urwid_escape.py
mitmproxy/contrib/urwid_monkeypatch.py
mitmproxy/tools/console/master.py
setup.py

This PR pins urwid back to 2.0.1. Once 2.1.1 is out, we can hopefully just revert this.
refs https://github.com/mitmproxy/mitmproxy/issues/3936
refs https://github.com/mitmproxy/mitmproxy/issues/3967

downgrade & pin urwid to 2.0.1

---

CHANGELOG
mitmproxy/flowfilter.py
mitmproxy/master.py
test/mitmproxy/test_flowfilter.py
tox.ini

fixes #3990 by also matching HTTP-WebSocket handshake flow with `~websocket`.
Also add py38 to the default tox env list.

match HTTP-WebSocket handshake flow for ~websocket filter

---

mitmproxy/options.py
mitmproxy/proxy/protocol/http.py

Add an option to bypass the call to `validate_request_form` when activated, as suggested in #848.
It's probably not enough to fix the whole issue, but it was enough to solve my issue and I guess that even though it's incomplete, adding a flag disabled by default is okay.

First step to fix #848 by adding a relax_http_form_validation option.

---

docs/src/content/overview-features.md

minor fixes: remove not needed escaping; add note about http2 incompatibility.

fix docs for Map* addons

---

setup.cfg
tox.ini

A common pattern in sans-io is to essentially match on all variants of
an enum, and then have a `else: raise AssertionError` in the end.
This increases robustness as we spot incomplete coverage instead of
silently passing. However, it makes no sense to explicitly test these
asserts.

Don't count overage for AssertionErrors

---

CHANGELOG
web/src/js/__tests__/components/Header/__snapshots__/OptionMenuSpec.js.snap
web/src/js/__tests__/components/common/__snapshots__/DocsLinkSpec.js.snap
web/src/js/components/Header/OptionMenu.jsx
web/src/js/components/common/DocsLink.jsx

Mitmweb has a bug that it links to http://docs.mitmproxy.org/en/stable/features/anticache.html, which just redirects to the home page of the docs of mitmweb.
This changes two things:
* fixes that link to point to the current version at https://docs.mitmproxy.org/stable/overview-features/#anticache
* also changes all doc link to use HTTPS, as there is no reason not to do this :shrug: :smiley:

Fix link to anticache docs in mitmweb

---

mitmproxy/tools/console/defaultkeys.py

Fixes https://github.com/mitmproxy/mitmproxy/issues/4109
I hope this also fixes the docs, because it is the only instance where I've found that string. The [docs](https://github.com/mitmproxy/mitmproxy/tree/master/docs) seem to somehow autogenerate the options tabel/text, so I don't know what else may need editing.
Note you also have no `CONTRIBUTING.md` or so that could explain it to me.

Fix intercept toggeling doc

---

CHANGELOG
mitmproxy/net/http/message.py
test/mitmproxy/net/http/test_message.py

In the wild https://github.githubassets.com/assets/site-77cb67c5e6c23f78d6d0327713f088c4.css
Relevant docs https://developer.mozilla.org/en-US/docs/Web/CSS/@charset
The rules are very strict, so this should work in all valid cases.
> must be double-quoted, following exactly one space character (U+0020), and immediately terminated with a semicolon

Use @charset to decode CSS files if available

---

CHANGELOG
mitmproxy/proxy/modes/transparent_proxy.py
mitmproxy/proxy/protocol/base.py

This is obviously not a security feature, it just prevents the most obvious shoot-yourself-in-the-foot type of thing. For example if I don't specify listen_host and then connect to the proxy via it's local IP (192.168.0.6 right now) it cannot detect that this is actually it's own. We might be able to extend this later tho if DoS is a relevant concern. Right now a single `curl` command will drain all resources and for example result in "OSError: [Errno 24] Too many open files". You can even exit the curl process and mitmproxy will keep doing it's endless loop.
Are there integration tests for this kind of thing? Might be worth setting up using Docker containers (maybe using compose) to test different network combinations. I don't really feel comfortable modifying these core things and don't …

Prevent transparent mode from connecting to itself in the basic cases, references #4128

---

docs/src/config.toml
docs/src/themes/mitmproxydocs/layouts/partials/footer.html

We already removed this from the main page, let's get rid of it here as well.

Disable Google Analytics for docs

---

mitmproxy/options.py

Just an options help-text change to replace deprecated `--ignore` reference with ``ignore-hosts`.

Replaced reference to deprecated --ignore option with --ignore-hosts.

---

CHANGELOG
mitmproxy/tools/console/master.py

In some cases, such as with firefox, the file is removed before the viewer is
finished loading.
1 second delay in another thread and then unlink
- [-] I have updated tests where applicable.

Add small delay before unlinking file in external viewer fixes #4152

---

.github/workflows/main.yml
codecov.yml
setup.py

Python 3.9 Compatibility

---

CHANGELOG
mitmproxy/net/http/encoding.py

I've come across an application that makes requests with a `Content-Type` of `application/json` and a `Content-Encoding` of `deflateRaw`. Without this change, the parser attempts to parse it as JSON due to a matching `Content-Type` and a non-matching `Content-Encoding`, which then fails since it's compressed binary data.
With this change, mitmproxy correctly decodes the data with the hack described [here](https://github.com/mitmproxy/mitmproxy/blob/46fbba639dd3581fa427db6d26fa4775a991da59/mitmproxy/net/http/encoding.py#L191-L198), and then successfully passes it off to the JSON view.
I don't know how widespread it is to have a `Content-Encoding` of `deflateRaw`, so up for debate whether this is worth adding in this special case, but seems like it's pretty safe hopefully!

Handle "deflateRaw" Content-Encoding as "deflate".

---

CHANGELOG
mitmproxy/proxy/protocol/http.py
mitmproxy/proxy/protocol/http2.py
test/mitmproxy/proxy/protocol/test_http2.py

http2: fix missing END_STREAM flag on requests without body

---

CHANGELOG
docs/src/content/concepts-protocols.md
examples/addons/http-trailers.py
mitmproxy/net/http/http1/assemble.py
mitmproxy/net/http/message.py
mitmproxy/proxy/protocol/http1.py
test/mitmproxy/net/http/http1/test_assemble.py
test/mitmproxy/net/http/test_message.py

Add support for sending request and response trailer headers. Support for _parsing_ http/1 is not added (I'm not actually sure where that code goes). This support is sufficient for injecting trailer headers into http/1 requests or responses.
Partial completion for "Wait if anyone ever requests HTTP/1.0 trailer support." in #2474

Send http/1 request and response trailer headers

---

release/hooks/hook-passlib.py
release/hooks/hook-publicsuffix2.py
release/hooks/hook-pydivert.py

These parts have been upstreamed:
- https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/39
- https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/40
- https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/41
🤸

Remove upstreamed pyinstaller hooks

---

setup.py
test/mitmproxy/addons/test_readfile.py

This is an implementation of
https://github.com/mitmproxy/mitmproxy/issues/4020
Tested to work fine here with Python 3.8.6.
Replace asynctest with stdlib mock

Replace asynctest with stdlib mock

---

test/mitmproxy/addons/test_readfile.py

Skip async tests on old python versions

---

mitmproxy/addons/dumper.py
mitmproxy/addons/termstatus.py
mitmproxy/flow.py
mitmproxy/http.py
mitmproxy/tools/_main.py
mitmproxy/utils/compat.py
test/mitmproxy/addons/test_dumper.py
test/mitmproxy/addons/test_termstatus.py
test/mitmproxy/utils/test_compat.py

This PR adds a simple switch for sans-io, which is currently hardcoded to off.
@Kriechi: I've though a bit about we could handle the coexistence of both stacks. It's a bit tricky because we need to know at import time for some stuff. I think one approach that works is to define out-of-band settings for `mitmproxy.util.compat.new_proxy_core` to be true. For example, we could check for the presence of `$MITMPROXY_NEW_CORE` on startup and then act accordingly. What do you think?

Add a switch for sans-io proxy core

---

CHANGELOG.rst
mitmproxy/addons/command_history.py
test/mitmproxy/addons/test_command_history.py

command-history: fail-safe file handling

---

CHANGELOG.rst
mitmproxy/utils/arg_check.py
test/mitmproxy/utils/test_arg_check.py

Informs the user when an underscore-formatted option is used. Currently, only an error is thrown. Replaces the underscore option and gives the correct format.
- [*] I have updated tests where applicable.
- [*] I have added an entry to the CHANGELOG.

Inform user when underscore-formatted options are used.

---

mitmproxy/net/tls.py
setup.py
test/mitmproxy/net/test_tls.py

This PR fixes #3994, but requires a new pyOpenSSL release to be shipped first. Putting this here because I depend on it for sans-io debugging.

Use OpenSSL's keylog callback for SSLKEYLOGFILE (#3994)

---

mitmproxy/addons/clientplayback.py

Http2 replay is broeken as per: https://github.com/mitmproxy/mitmproxy/issues/4318 
this patch fixes this.
Tested with 
```
curl --http1.1 https://httpbin.org/get -k -x localhost:8080
curl --http2 https://httpbin.org/get -k -x localhost:8080
```

fix http2 request replay missing host header

---

mitmproxy/tools/console/consoleaddons.py

There is a small typo in mitmproxy/tools/console/consoleaddons.py.
Should read `viewer` rather than `viewier`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, viewier -> viewer

---

CHANGELOG.md
mitmproxy/net/server_spec.py
test/mitmproxy/net/test_server_spec.py

When specifying a reverse proxy, the user can supply [scheme://]host[:port]. We previously always assumed scheme="https" if no scheme was given, but that is ugly when proxying non-HTTP protocols. For example, `mitmproxy --mode reverse:smtp.gmail.com:25` would falsely assume TCP-over-TLS and then fail. This PR changes it so that we only assume HTTPS if no custom port has been provided by the user.

Reverse proxy: do not assume TLS for non-standard ports

---

mitmproxy/utils/arg_check.py

Else the user sees
```
--replace is deprecated.
Please use `--replacements` instead.
mitmdump: error: unrecognized arguments: --replace
```
and then
```
mitmdump: error: unrecognized arguments: --replacements
--replacements is deprecated.
Please use `--modify-body` or `--modify-headers` instead.
```
and feels silly

Upon --replace, suggest --modify-body / --modify-headers

---

mitmproxy/master.py

If we ever decide to rename the issue template file, then GitHub will simply render a default empty issue form.

deep-link to create a new GitHub bug report

---

CHANGELOG.md
mitmproxy/net/http/url.py
test/mitmproxy/net/http/test_url.py

Before calling `.decode("idna")` first extract the port number. Attempt to fix issue #4409
If the port is present it can lead to a UnicodeError exception causing net.http.url.parse_authority to incorrectly return False.
The existing test passes because `.decode("idna")` accepts a port number some of the time:
```
>>> b"xn--aaa-pla.example:80".decode("idna")
'äaaa.example:80'
```
However this results in a UnicodeError exception:
```
>>> b"xn--r8jz45g.xn--zckzah:80".decode("idna")
File "/usr/lib/python3.6/encodings/punycode.py", line 207, in decode
res = punycode_decode(input, errors)
File "/usr/lib/python3.6/encodings/punycode.py", line 194, in punycode_decode
return insertion_sort(base, extended, errors)
File "/usr/lib/python3.6/encodings/punycode.py", …
```

Extract port number from authority before IDNA decode 

---

examples/contrib/test_har_dump.py

To run the test, I had to copy `conftest.py` to examples.
```bash
cp test/conftest.py examples
pytest examples/contrib/test_har_dump.py
```
This fixes the `fixture 'tdata' not found` error.

Fix location for contrib har_dump.py in its test

---

CONTRIBUTING.md

run `venv/bin/pip install -e .[dev]`  failed in mac zsh:
> zsh: no matches found: .[dev]
`venv/bin/pip install -e ".[dev]"` works well in both mac bash, mac zsh and debian

Imporove document, pip install -e .[dev] error in mac zsh

---

CHANGELOG.md
mitmproxy/addons/export.py
test/mitmproxy/addons/test_export.py

Unless this is done, the SNI server name will not be sent, often making
the curl/httpie command have different behaviour than the original
request (most often in the form of failing to establish a TLS
connection).
With this change, we always use the original host, fixing this failure.
However, if the original host is a domain, it may sometimes resolve to
a different IP address later on. In curl, we solve this problem by
forcing it to connect to the original IP using `--resolve`. For httpie
there is currently no easy solution (see:
https://github.com/httpie/httpie/issues/414).
(Note: Ugh, ignore the name change. I sent the initial PR by accident, where I was using the showhost for controlling this, before I decided this has nothing to do with showhost.)

Use original flow host instead of IP when exporting to curl/httpie.

---

examples/contrib/har_dump.py
examples/contrib/test_har_dump.py

The reason was an invalid import of `connections` which is gone in d159897d98d47034827714bd0298268d1b9af6f0, but the loading error was silently ignored (#4438) resulting in a misleading exception at a later stage.
The way to run tests from examples.
ln -sr test/conftest.py examples
pytest examples/contrib/test_har_dump.py -k simpl
The way to see the execution flow with silenced exceptions.
from hunter import trace, Q
trace(Q(stdlib=False), ~Q(filename_contains='site-packages'))
Fixes #3377
Fixes #3855

Fix HAR dump

---

mitmproxy/net/http/http1/read.py
test/mitmproxy/net/http/http1/test_read.py

Fix ValueError when splitting on a request URI without a path part.
Consulted [HTTP 1.1 spec](https://tools.ietf.org/html/rfc2616#section-5.1.2) where it says that proxy should append "/" to URI's path if it already doesn't have one.

Fixes #4416

---

mitmproxy/net/tls.py

As per @r00t-'s investigation at https://github.com/mitmproxy/mitmproxy/issues/4451#issuecomment-780315521, OpenSSL does not like to be alled with an empty ALPN. This fixes it on our end, pyOpenSSL should probably still raise here.

Don't call set_alpn_protos if ALPNs are empty, refs pyca/pyopenssl#992

---

mitmproxy/addons/save.py
test/mitmproxy/addons/test_save.py

This PR makes the Save addon store (and forget about) flows immediately when they error. The new sans-io core guarantees that _either_ error or end is called, so this should work just fine. 
Thinking a bit more long term, it will make a lot of sense to introduce general `flow_start` and `flow_end` events that get triggered for all flow types.

Memleak: immediately store errored flows, refs #4456

---

mitmproxy/proxy/layers/http/__init__.py
mitmproxy/proxy/layers/http/_http2.py
mitmproxy/proxy/layers/http/_http_h2.py
test/mitmproxy/proxy/layers/http/test_http2.py

@r00t-'s comment in #4451 pointing to Facebook was a useful one - their custom HTTP/2 stack exposed some interesting race conditions in ours, which I believe I fixed all now.
@r00t-: Could you check out this branch and see if that fixes your Facebook POST requests in particular? 🍰

Speculative HTTP/2 fixes, refs #4451

---

docs/scripts/clirecording/Dockerfile

Speed up `git clone` in docs Dockerfile by reducing the git repository clone depth for the commit history, which is not useful in this case.

Speed up `git clone` in docs Dockerfile

---

mitmproxy/addons/dumper.py

Tests for `4` already exist https://github.com/mitmproxy/mitmproxy/blob/8178f6c77b715cd342f8be161d5ca5da8938645c/test/mitmproxy/addons/test_dumper.py#L59
Not a fan of the `70` magic number here, but this PR references #4476
https://github.com/mitmproxy/mitmproxy/blob/8178f6c77b715cd342f8be161d5ca5da8938645c/mitmproxy/addons/dumper.py#L110-L113
Next: make the 70 configurable. I think merging `3` and `4` is not a good idea, truncating megabytes of responses is usually a good thing. So a new option `dumper_lines_cutoff` could be introduces that only affects `flow_detail = 3`

document flow_details 4

---

mitmproxy/addons/tlsconfig.py
mitmproxy/net/tls.py
test/mitmproxy/net/test_tls.py

I unfortunately lost track where this was reported, but this PR makes it so that our TLS client does not send IP addresses as SNI, which is against the spec.

Don't set IP addresses as SNI

---

mitmproxy/addons/next_layer.py
mitmproxy/proxy/layers/modes.py
test/mitmproxy/addons/test_next_layer.py
test/mitmproxy/proxy/layers/test_modes.py
test/mitmproxy/proxy/layers/test_socks5_fuzz.py

This PR adds SOCKS5 proxying to the sans-io implementation. 🥳

[sans-io] Add SOCKS5 proxy mode

---

docs/scripts/clirecording/Dockerfile

Remove unnecessary apt & pip packages temp/cache files, prevent additional & unnecessary apt packages, result in saving more than 300 MB in the image size:
```$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
after                         latest              c523c04f38f8        25 minutes ago      437MB
before                        latest              3c427b69e9f8        39 minutes ago      785MB
```

Refactor docs clirecording Dockerfile

---

.github/workflows/main.yml
CHANGELOG.md
release/docker/Dockerfile
release/docker/docker-entrypoint.sh

As @mhils invited, help rewrite the Docker image to replace Alpine Linux. The final image size is about 179MB, compared with original 123MB, should be not too big :D
It's a large rewrite and I'm not very familiar with mitmproxy, so please help test its functionality to be as expected, thanks.
fix #3712

Switch Docker release to be based on Debian instead of Alpine

---

docs/ci.sh
docs/upload-archive.sh
mitmproxy/contrib/kaitaistruct/make.sh

- Double quote variable to prevent globbing and word splitting
- Use `./*.ksy` instead of `*.ksy` so names with dashes won't become options
- Use `-n` instead of `! -z` double negative condition for better readability and understanding
I believe there isn't a problem here right now as they're already working for a long time, but a better styling can help prevent problem and help improve the maintainability of the scripts ;)

Improve Shell Script syntax

---

examples/addons/websocket-inject-message.py
mitmproxy/addons/proxyserver.py
mitmproxy/io/compat.py
mitmproxy/proxy/commands.py
mitmproxy/proxy/events.py
mitmproxy/proxy/layer.py
mitmproxy/proxy/layers/http/__init__.py
mitmproxy/proxy/layers/tcp.py
mitmproxy/proxy/layers/websocket.py
mitmproxy/proxy/tunnel.py
mitmproxy/tools/console/flowview.py
mitmproxy/websocket.py
test/mitmproxy/addons/test_proxyserver.py
test/mitmproxy/proxy/layers/http/test_http.py
test/mitmproxy/proxy/layers/test_tcp.py
test/mitmproxy/proxy/layers/test_websocket.py
test/mitmproxy/proxy/test_layer.py

<s>I still need to fix test coverage for proxyserver.py,</s> but I figured this can already take some review. 😃 
This PR introduces the `inject` command, which can be used to inject messages into running TCP and WebSocket connections. The implementation here is _very_ different from the previous `flow.inject_message` API as we want to keep our sans-io proxy sans-io. 😄 In a nutshell, injected messages are modeled as an external Event, similar to DataReceived/ConnectionClosed. They get passed into the proxy core from the outside (`.server_event`), passed through to the target layer, and then processed there. Most notably, injected messages now also trigger the associated `*_message` hooks.

Add WebSocket/TCP Message Injection

---

mitmproxy/addons/proxyserver.py
mitmproxy/proxy/server.py
test/mitmproxy/addons/test_proxyserver.py

In short, we don't want mitmproxy to connect to itself. That generates quite unfortunate recursion chains:
```
$ mitmdump
$ curl -x localhost:8080 -k http://localhost:8080
```
runs into an infinite connect loop. With this patch applied:
```
127.0.0.1:50219: GET http://localhost:8080/
<< Connection killed: Stopped mitmproxy from recursively connecting to itself.
```

Detect recursive self-connects and stop them

---

mitmproxy/addons/next_layer.py
mitmproxy/addons/proxyserver.py
mitmproxy/addons/tlsconfig.py
mitmproxy/connection.py
mitmproxy/contentviews/query.py
mitmproxy/proxy/events.py
mitmproxy/proxy/layers/http/__init__.py
mitmproxy/proxy/layers/http/_http_h2.py
mitmproxy/proxy/layers/modes.py
mitmproxy/proxy/layers/tls.py
mitmproxy/proxy/tunnel.py
test/mitmproxy/addons/test_next_layer.py
test/mitmproxy/addons/test_tlsconfig.py
test/mitmproxy/proxy/layers/http/test_http.py
test/mitmproxy/proxy/layers/test_modes.py
test/mitmproxy/proxy/layers/test_tls.py
test/mitmproxy/proxy/test_layer.py
test/mitmproxy/proxy/test_tunnel.py

This PR fixes a rather long list of smaller bugs I found during testing. Most importantly, it also sets the `connection_strategy` option to `eager` by default. 
`connection_strategy` is a new sans-io feature that we haven't really talked about much yet, although it controls a fundamental aspect of mitmproxy's proxy logic:
```python
loader.add_option(
"connection_strategy", str, "eager",
"Determine when server connections should be established. When set to lazy, mitmproxy "
"tries to defer establishing an upstream connection as long as possible. This makes it possible to "
"use server replay while being offline. When set to eager, mitmproxy can detect protocols with "
"server-side greetings, as well as accurately mirror TLS ALPN negotiation.",
choices=("eager", "lazy")
)
```
Mitmproxy 6 …

Sans-IO Improvements: Connection Strategy

---

CHANGELOG.md
release/README.md

Fix typo: Github should be GitHub

---

docs/scripts/clirecording/Dockerfile

clean up tmux dir in clirecording Dockerfile, will save the image size a little bit.

docker: clean up tmux dir in clirecording Dockerfile

---

release/docker/Dockerfile

This will help we keep the image not too heavy that caused by those
additional, suggestion apt packages.
Only install the packages we explicitly want.

docker: avoid additional apt packages by `--no-install-recommends`

---

docs/README.md

I was confused what `mitmproxy Python package` meant. At first I did `pipx install mitmproxy`, but that didn't work. Then I realized I needed it as a library/module, not cli.
Changed `build.sh` to `build.py` since it was deleted on commit a7d1f32c89f3ea8b989a2d63fac13a44bc34f946

docs(docs-readme): clarify documentation readme

---

docs/README.md

After only installing the "normal" version of hugo the ./build.py script failed because of some SCSS errors. After installing the extended version using snap, everything worked fine.
I also didn't know that the venv had to be activated manually, so I put a small comment, pointing that out.

docs: add more precise instructions on docs setup

---

CHANGELOG.md
mitmproxy/addons/browser.py
test/mitmproxy/addons/test_browser.py

Allow `browser.start` to be executed multiple times to open new browsers.

Allow browser.start to open multiple browsers.

---

CHANGELOG.md
mitmproxy/tools/console/flowdetailview.py

Addresses https://github.com/mitmproxy/mitmproxy/issues/4549
Delimit SHA256 bytes to make fingerprint easier to read.
- [] I have updated tests where applicable.

Improve certificate fingerprint readability

---

docs/src/content/concepts-certificates.md

Instructions on how to add certificate to MacOS keychain programmatically.

Add certificate CLI Installation method for MacOS

---

CHANGELOG.md
mitmproxy/proxy/server.py

Fixes https://github.com/mitmproxy/mitmproxy/issues/4563
This fix ensures that first we write out all pending bytes to the client before requesting more from the server.
Potentially this impacts performance.
CC @mhils

Fix: check pending writes before requesting more from server

---

docs/src/content/concepts-certificates.md

Extend documentation on what format the `mitmproxy-ca.pem` needs to
conform with so it can be used as a CA.
Fixes #4598

docs: requirements for custom mitmproxy-ca.pem

---

mitmproxy/certs.py

We need to restrict `CERT_EXPIRY` because modern browsers only accept a ~ <= 1year period for certs, but re-reading all prior commits and issues as well as the CA/Browser Forum Baseline Requirements on the topic, it looks like we don't actually need to restrict our CA lifetime by that much. Let's try out a longer validity and see if anyone complains.

Make the CA cert live longer

---

mitmproxy/http.py

Fixes #4617
I'm not sure if my wording is accurate. But since HTTP/2 allows multiple Cookie headers (which HTTP/1 didn't) folding now becomes relevant here too.

Document Cookie header folding issues

---

mitmproxy/addons/next_layer.py

This PR fixes #4642. In short, we erroneously assigned two ServerTLSLayers if the following conditions were met:
1. Reverse Proxy Mode
2. TLS between mitmproxy and server.
3. TLS between client and mitmproxy.
4. Client sends its ClientHello before server sends its server greeting.

Fix HTTPS Reverse Proxy TLS Layer Logic

---

docs/src/content/addons-api-changelog.md

This PR includes some initial documentation on how to upgrade existing addons to mitmproxy 7. For most addons, no changes should be necessary. If you encounter any issues not listed here, please leave a comment so that we can address them! 😃

Add Addon Upgrade Docs for mitmproxy 7

---

docs/scripts/api-events.py
mitmproxy/addons/tlsconfig.py
mitmproxy/proxy/layers/tls.py
mitmproxy/proxy/server.py
test/mitmproxy/addons/test_tlsconfig.py
test/mitmproxy/proxy/layers/test_modes.py
test/mitmproxy/proxy/layers/test_tls.py

Tests pass and I did a smoke test with one website.
I think this also made the internal code cleaner, there were multiple if/else blocks for these two cases.
There's one open question that only you can decide: does it make sense that `TlsStartData` is used for both hooks? Or is something about that superfluous?
I'll accept :cake: or :broccoli:

separate tls_start hooks for client and server, fixes #4665, refs #4547

---

mitmproxy/addons/dumper.py
mitmproxy/addons/termlog.py

passing sys.stdout to click does not work under some circumstances.
For example, we cannot `click.echo("\u2026")` from pyinstaller binaries in a Docker container
with `file=sys.stdout`. Instead, we shall pass `err`, which somehow works.

Termlog: let click figure out stdout/stderr

---

docs/scripts/pdoc-template/module.html.jinja2
mitmproxy/addons/proxyserver.py
mitmproxy/command.py
mitmproxy/command_lexer.py
mitmproxy/tools/console/grideditor/col_bytes.py
mitmproxy/types.py
mitmproxy/utils/strutils.py
mitmproxy/websocket.py
test/mitmproxy/addons/test_proxyserver.py
test/mitmproxy/test_command.py
test/mitmproxy/test_command_lexer.py
test/mitmproxy/test_types.py
test/mitmproxy/test_websocket.py
test/mitmproxy/tools/console/test_defaultkeys.py

@Prinzhorn: Very early WIP - My plan is to change the command arguments to bytes (simple, see below) and handle the conversion as part of the commands processing logic (harder, to be done). Would that generally satisfy your use case? :)
Also thanks again for your `.is_text` input. That was really quite useful. The public API is now just that, while we internally keep the opcode around, which is not much more effort.

[WIP] Fix WebSocket/TCP injection

---

mitmproxy/connection.py
test/mitmproxy/test_connection.py

First of all, congrats on shipping 7.0! Lots of nice improvements and I'm seeing the benefits of sans-io in making my own mitmproxy integrations more testable :smile:
Calling `Flow.set_state(state)` on a flow implicitly calls `Server.set_state()` if there's an existing server connection. In the `response` addon hook the `Flow`'s `server_conn.state == ConnectionState.OPEN`, which causes the `Server.address` mutation check to `raise` if you call `flow.set_state(state)`.
This works around that issue by checking if the `Server.address` attribute's value is actually being changed rather than just checking if it's being set.

Allow no-op assignments to Server.address when connection open

---

CHANGELOG.md
mitmproxy/addons/tlsconfig.py
mitmproxy/certs.py
mitmproxy/proxy/layers/tls.py
test/mitmproxy/addons/test_tlsconfig.py
test/mitmproxy/test_certs.py

This PR fixes the two issues described in #4689:
1. When the client did not send a SNI and we don't know anything about an upstream server, we now use our local IP address as the certificate subject. This is necessary for secure web proxies that are interfaced by IP address as the TLS SNI must not contain a raw IP address.
2. Firefox apparently now supports HTTP/2 proxies, i.e. proxies where the `CONNECT` request is handled via HTTP/2 as well. We don't support that (yet), so with this PR we make sure that we don't negotiate a `h2` ALPN. I'm not sure if we want to support the HTTP/2 proxy protocol in the future, things get quite unwieldy once we have a ton of TLS negotiations in a single connection. We'd essentially need to clone our `context.Client` object for each CONNECT stream so that …

Fix Secure Web Proxy compatibility with some clients (#4689)

---

CHANGELOG.md
mitmproxy/addons/tlsconfig.py
mitmproxy/certs.py
mitmproxy/net/tls.py
test/mitmproxy/test_certs.py

I initially wanted to reuse a single OpenSSL context for all client requests, but that does not work as some of the APIs we are using are not connection-specific (e.g. `SSL_CTX_add_extra_chain_cert` has no `SSL_add_extra_chain_cert` equivalent). Turns out we can tackle this entire problem much easier by just caching per host! We only need to cache calls to `create_proxy_server_context` and `create_client_proxy_context`. This allows us to perform session resumption instead of full TLS handshakes in a significant number of cases.

Perf: reuse OpenSSL context to reduce number of TLS handshakes

---

mitmproxy/addons/asgiapp.py
test/mitmproxy/addons/test_asgiapp.py

Lowercasing headers is required by the spec, not doing so breaks Flask's `Content-Length` detection.

ASGI Apps: lowercase header names

---

mitmproxy/tools/console/keybindings.py
mitmproxy/tools/console/options.py
test/mitmproxy/tools/console/test_integration.py

Per #4614 this change fixes a crash that results from using home or end keys in the options or keybindings windows.

Fix #4614 Options and Keybinding screen: home and end crash mitmproxy

---

.github/workflows/main.yml
mitmproxy/proxy/events.py

We will try to switch all builders to 3.10 once the final hits, but for now let's just run tests and see what happens.

Add CI for Python 3.10rc1

---

mitmproxy/proxy/layers/tls.py
test/mitmproxy/addons/test_tlsconfig.py

This PR makes it possible to access the raw [`ClientHello`](https://github.com/mitmproxy/mitmproxy/blob/c4dd46c3db97eabedf14fc54a23dae8d167fdad2/mitmproxy/net/tls.py#L284) object in the `tls_clienthello` hook as `data.client_hello`.
```python
def tls_clienthello(data):
print(data.client_hello)
```

Expose full ClientHello object in tls_clienthello hook

---

examples/contrib/har_dump.py

I noticed `DeprecationWarning` while running har_dump.py:
```python
examples/contrib/har_dump.py:157: DeprecationWarning: Server.ip_address is deprecated, use Server.peername instead.
entry["serverIPAddress"] = str(flow.server_conn.ip_address[0])
```

Fix DeprecationWarning in har_dump.py

---

CHANGELOG.md
mitmproxy/__init__.py
test/mitmproxy/tools/web/test_app.py

This is not necessary anymore, and greatly improves the number of open sockets we can handle on Windows.
fixes #4742

Remove asyncio event loop workaround for tornado

---

mitmproxy/http.py

We previously did not detect `<meta charSet="utf-8"/>` (only `<meta charset="utf-8"/>`), this PR fixes this. 😃

charset detection: ignore case when searching in HTML

---

mitmproxy/http.py

Escape backslashes in pydocs containing '\*' (markdown escape sequence).
This removes the one warning I saw when running `pytest`:
/mitmproxy/mitmproxy/http.py:97: DeprecationWarning: invalid escape sequence \*

Fix warning in pytest

---

mitmproxy/certs.py
test/mitmproxy/test_certs.py
web/src/js/__tests__/components/__snapshots__/FlowViewSpec.tsx.snap
web/src/js/__tests__/ducks/_tflow.ts

I noticed when running tests the output of
`web/src/js/__tests__/ducks/_tflow.ts` would change depending on how I
set my timezone, e.g.
$ TZ=America/Los_Angeles pytest --quiet \
test/mitmproxy/tools/web/test_app.py >/dev/null \
&& grep --extended-regexp 'not(after|before)' web/src/js/__tests__/ducks/_tflow.ts
"notafter": 2235132207,
"notbefore": 1604415807,
$ TZ=Asia/Tokyo pytest --quiet \
test/mitmproxy/tools/web/test_app.py >/dev/null \
&& grep --extended-regexp 'not(after|before)'  web/src/js/__tests__/ducks/_tflow.ts
"notafter": 2235074607,
"notbefore": 1604354607
It looks like this is because the `cert_to_json` function simply calls
`timestamp` the `datetime` object from
`x509.Certificate.not_valid_before`, however, this `datetime` object is
not timestamp aware, from the docs [1]:
> …

Make Cert.not{before,after} timezone aware

---

mitmproxy/tools/web/app.py
test/mitmproxy/tools/web/test_app.py

Handle this server-side rather than passing the message content encoding
details back when fetching flow content. If {en,de}coding fails, return
the raw request contents.
This addresses https://github.com/mitmproxy/mitmproxy/issues/4809

mitmweb: handle {en,de}coding on server-side

---

CHANGELOG.md
mitmproxy/http.py
mitmproxy/proxy/layers/http/_http1.py
test/mitmproxy/proxy/layers/http/test_http.py
test/mitmproxy/test_http.py

When updating the response content for a response, avoid adding the
'content-length' header if the response contains a 'transfer-encoding'
header, from the spec [1]:
> When a message does not have a Transfer-Encoding header field, a
Content-Length header field can provide the anticipated size, as a
decimal number of octets, for a potential payload body
Note the 'transfer-encoding' header is not used with HTTP/2
https://httpwg.org/specs/rfc7230.html#header.content-length

Don't set 'content-length' with 'transfer-encoding'

---

mitmproxy/tools/console/searchable.py

Resolves #4491 
Websocket view will now jump to bottom every time a new message arrives.

Fix websocket view jumps to top bug

---

CHANGELOG.md
mitmproxy/addons/clientplayback.py
test/mitmproxy/addons/test_clientplayback.py

Upstream replays used to do a CONNECT even for plaintext HTTP which some proxies did not understand. This was removed, the test catching this deviation was removed

Fix #4876 Don't do CONNECT on plaintext HTTP replays via upstream

---

release/docker/Dockerfile

Container sizes went from [`73MB` in Version 7.0.4](https://hub.docker.com/layers/mitmproxy/mitmproxy/7.0.4/images/sha256-36e9f5397302341d55fec03953e04cd69c47038e051d5ccec6d9e84f987527cc?context=explore) to [`359MB` in `dev`](https://hub.docker.com/layers/mitmproxy/mitmproxy/dev/images/sha256-c418f4eda4a30f486b76a3004e6a04e8fd172095ac29b29de8371b06d41aed25?context=explore). Also the image now contains tools like `imagemagick`, `git` and `libbluetooth3`.
The change was introduced in [commit `fffed0cb`](https://github.com/mitmproxy/mitmproxy/commit/fffed0cb3aa121b6c3735ca3f6beeb4b2356b4e6#diff-5ff03f5acddd8edc535d5ec30b70e78468bf1e748e126ba3ac39c67a28a6af40) where the base image was changed from `python:3.9-slim-buster` to `python:3.9-bullseye`. It was probably an oversight that "slim" was …

Use the slim base image for container

---

mitmproxy/contrib/urwid/raw_display.py

Console: add error message for older Windows versions

---

CHANGELOG.md
mitmproxy/flowfilter.py
test/mitmproxy/test_flowfilter.py
web/src/js/filt/filt.peg

Add 2 font MIME type patterns to the asset filter (~a) to both `mitmproxy` and `mitmweb`:
- `font/*`
- `application/font-*`

Add font types to asset filter (~a)

---

mitmproxy/proxy/layers/websocket.py

There may already have been a disconnect, which is still in the processing queue.
fix #4931

WebSockets: don't assert that server is connected upon initialization

---

mitmproxy/platform/windows.py

If we haven't connected to the upstream host in transparent mode, then the call to `write` on line 74 will raise an `AttributeError` as we haven't initialised `self.wfile`.
If we add `AttributeError` to the `except` line, then we'll catch the exception and call `_connect`, which will in turn initialise `wfile`.

Fixes AttributeError in transparent mode

---

CHANGELOG.md
mitmproxy/controller.py

Add a `__deepcopy__()` method so that when an intercepted flow or a flow loaded from a file is displayed using `view.flows.resolve` the flows are able to be deepcopy()'ed.

Add deepcopy to allow view.flows.resolve (issue #4916)

---

CHANGELOG.md
docs/src/content/overview-features.md

Trivial documentation fix, the `User-Agent` header modification [example](https://docs.mitmproxy.org/stable/overview-features/#examples-4) was incorrect, specifying the `Host` header. Copy/paste error by the looks of it.

Example specified incorrect header

---

mitmproxy/master.py

Set the loop explicit in `asyncio.wrap_future` call  
When I call shutdown with a different loop in the current thread from MITM loop, it's crashes with the error:
`ValueError: The future belongs to a different loop than the one specified as the loop argument`

Fix crush shutdown when MITM has it's own loop

---

mitmproxy/http.py
test/mitmproxy/test_http.py

Fix a crash when refreshing headers with a negative unix timestamp

---

CHANGELOG.md
mitmproxy/net/tls.py

Passing zero for the size_t length argument of
X509_VERIFY_PARAM_set1_host causes MITM Proxy to crash when used with
BoringSSL.
https://www.openssl.org/docs/man1.1.1/man3/X509_VERIFY_PARAM_set1_host.html
https://boringssl.googlesource.com/boringssl/

Pass length of hostname.encode() to X509_VERIFY_PARAM_set1_host

---

mitmproxy/addons/onboardingapp/templates/index.html

I have updated instructions for installing certificate on iOS 15 (basing on version 15.1). The second commit contains small formatting fixes and a typo within the source file.
I don't think it's worth to mention this in the CHANGELOG.
- [] I have updated tests where applicable.
- [] I have added an entry to the CHANGELOG.

iOS 15 certificate installation instructions update

---

CHANGELOG.md
mitmproxy/proxy/server.py
mitmproxy/proxy/server_hooks.py

I tried with some live traffic and it behaved as expected. Also the demo add-on no longer logs server_connected and request interleaved.

await server_connected hook before doing something with the connection, fixes #5108

---

CHANGELOG.md
mitmproxy/http.py
test/mitmproxy/test_http.py

Real world issue: https://www.youtube.com/s/desktop/245f415e/jsbin/desktop_polymer_inlined_html_polymer_flags.vflset/desktop_polymer_inlined_html_polymer_flags.js
This JavaScript file contains a matching meta tag and the encoding ended up being a literal backslash `\` which I passed along to `codecs.lookup(enc).name`. The added check will catch html and xhtml.
I think we want to rewrite/improvie the guessing anyway with better tests, e.g. #4415

Fixed encoding guessing: only search for meta tags in HTML bodies

---

CHANGELOG.md
examples/contrib/httpdump.py

Adds `httpdump.py` example.
```
usage: mitmdump -s httpdump.py "~ts application/json"
options:
- dumper_folder: content dump destination folder (default: ./httpdump)
- open_browser: open integrated browser with proxy configured at start (default: true)
```

Add httpdump.py example

---

CHANGELOG.md
mitmproxy/addons/view.py
mitmproxy/flow.py
mitmproxy/io/compat.py
mitmproxy/test/tflow.py
mitmproxy/tools/console/common.py
mitmproxy/tools/web/app.py
mitmproxy/version.py
test/mitmproxy/addons/test_view.py
web/src/js/__tests__/ducks/_tflow.ts
web/src/js/flow.ts

This PR adds `Flow.timestamp_created`, which is used to make sure that replayed flows retain their position in the flow list. They don't jump to the bottom of the list anymore.
@Prinzhorn / @Kriechi, given that this is a public API change, any comments?

Add `Flow.timestamp_created` to retain list order on replay

---

CHANGELOG.md
mitmproxy/tools/console/common.py
test/mitmproxy/tools/console/test_common.py

This commit fixes crashing when TruncatedText couldn't properly truncate string contains full-width characters.
Fixes #2894

Fix text truncation for full-width characters

---

CHANGELOG.md
web/src/js/contrib/clipboard.tsx
web/src/js/flow/export.ts

https://github.com/mitmproxy/mitmproxy/issues/5264
The browser disables the navigator.clipboard object for non-secure domains.
- startup parameters: `mitmweb -p 8888 --web-host 192.168.0.124`
- browser console error : `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'writeText')`
The security domain includes addresses for local access and TLS security authentication, such as `https` protocol addresses, `127.0.0.1` or `localhost`.
So I submit a PR:
- Use `navigator.clipboard` in the secure domain to improve efficiency, and fall back to `document.execCommand('copy');` in the non-secure domain to ensure that the function is available.

Fix mitmweb export copy failed in non-secure domain

---

CHANGELOG.md
examples/contrib/http_manipulate_cookies.py

Added example on how to manipulate (outbound and inbound) cookies for http flows.
Added an example script to `examples/contrib`

Example: manipulate http cookies

---

mitmproxy/addons/onboardingapp/templates/index.html

Updated the onboarding documentation for Android (mitm.it) with the Android 12 flow and a added a link to the Android network security config.

Extend Android onboarding documentation

---

mitmproxy/addons/errorcheck.py
mitmproxy/master.py

sys.exit() causes a CancelledError to be thrown. ErrorCheck._shutdown_if_errored
fires sys.exit after self.running() returns, causing the CancelledError to
appear in Event.wait() and preventing Master.done() from being called. This can
result in terminal breakage when using the CLI, and is especially apparent if
any errors occur during startup (e.g. port is not available, script has a syntax
error, etc.).
The fix is simply to ensure that Master.done always gets called.
Note that this doesn't handle the case of people calling `sys.exit` or throwing some other `BaseException` from a `running` hook; this ideally should be a very rare occurrence, so it's probably not worth specially handling.

Fix terminal breakage if an error occurs at startup

---

CHANGELOG.md
mitmproxy/tools/console/master.py

Resolves #5297
Removed mailcap usage. Behaviour should not change on non-UNIX platforms, on UNIX it is unified with macOS and Windows.
- [ N/A ] I have updated tests where applicable.
- [ N/A ] I have added an entry to the CHANGELOG.

Remove usage of deprecated mailcap module

---

mitmproxy/utils/asyncio_utils.py

Remove outdated doc comment in asyncio_utils.create_task.

Remove outdated doc comment in asyncio_utils.create_task

---

CHANGELOG.md
mitmproxy/contentviews/__init__.py
mitmproxy/tools/console/flowview.py
test/mitmproxy/tools/console/conftest.py
test/mitmproxy/tools/console/test_contentview.py

Fix CommandError when adding a custom view after startup.
Previously, hot-reloading a script with a custom view after at least one flow
was viewed could throw "CommandError: Not viewing a flow" due to show() being
called while the flow view window was not visible.
Additionally, this patch also refreshes the FlowView when a custom view is
removed.
Fixes #5319.

Fix CommandError when loading a new contentview

---

CHANGELOG.md
mitmproxy/proxy/layers/http/_upstream_proxy.py
test/mitmproxy/proxy/layers/http/test_http.py

Encode host part of authority using idna in upstream proxy, rather than the system encoding.
Fixes #5316.

Properly encode hostname for upstream requests.

---

CHANGELOG.md
mitmproxy/proxy/layers/http/_http1.py
test/mitmproxy/proxy/layers/http/test_http_version_interop.py

Merge multiple Cookie headers when proxying HTTP/2 to HTTP/1 (more information, please see #5337)
Fix #5337

Fix handling of multiple Cookie headers when proxying HTTP/2 to HTTP/1

---

CHANGELOG.md
mitmproxy/proxy/layers/http/_http1.py
test/mitmproxy/proxy/layers/http/test_http.py

See #5372 for initial bug report with reproduction steps.
> TL;DR: An excess empty chunk `\r\n0\r\n` has been sent to the downstream for HEAD request.

Fix a bug where an excess empty chunk has been sent for chunked HEAD request

---

examples/addons/wsgi-flask-app.py

Update the WSGI addon example.
The WSGI example still had old documentation for HTTPS usage and I updated it to make clear how to use it with HTTPS (#3786).

Fix WSGI HTTPS example

---

CHANGELOG.md
mitmproxy/contrib/kaitaistruct/exif.py
mitmproxy/contrib/kaitaistruct/exif_be.py
mitmproxy/contrib/kaitaistruct/exif_le.py
mitmproxy/contrib/kaitaistruct/gif.py
mitmproxy/contrib/kaitaistruct/google_protobuf.py
mitmproxy/contrib/kaitaistruct/ico.py
mitmproxy/contrib/kaitaistruct/jpeg.py
mitmproxy/contrib/kaitaistruct/png.py
mitmproxy/contrib/kaitaistruct/tls_client_hello.py
mitmproxy/contrib/kaitaistruct/vlq_base128_le.py
setup.py

Droped pkg_resources dependency used by kaitaistruct version checking
Droped kaitaistruct version checks
Removed setuptools that provides pkg_resources from setup.py

Drop pkg_resources dependency used by kaitaistruct version checking (#5401)

---

CHANGELOG.md
mitmproxy/proxy/layers/http/_http2.py
mitmproxy/proxy/layers/http/_http_h2.py
test/mitmproxy/proxy/layers/http/test_http2.py

BufferedH2Connection is able to buffer huge response and send it to client, properly following flow control specs.
But trailers are not subject to flow control and were mistankenly sent immediate.
That led to the situation that mitmproxy worked fine on small responses (that fit in 65k bytes - initial size of flow control window) and broke on huge responses.
With this changes I delay trailers until all data gets sent.
I also altered `end_stream` method because it is hard to expose proper stream state to `Http2Connection.is_closed` now.
Without the change an empty data frame with `end_stream` flag was sent before trailers and it also violated protocol.
Fixes #5428
I will remove excessive logging and add tests/changelog in the next iterations.
@mhils are you ok with the solution?

fix huge (>65kb) http2 responses corrupted

---

CHANGELOG.md
mitmproxy/contentviews/grpc.py

Following https://github.com/python/cpython/issues/88840 , python 3.11a4 and later disallows unhashable objects to be defaults. This results in a `ValueError` exception when setting default value of `parser_options` field. Fixes #5474.

use default_factory for parser_options field

---

CHANGELOG.md
mitmproxy/addons/tlsconfig.py

This led to confusion previously, see https://github.com/mitmproxy/mitmproxy/discussions/5416#discussioncomment-3079358.

tlsconfig: don't connect upstream if connection strategy is lazy

---

setup.py

When pyOpenSSL version 21 is installed, mitmproxy won't start due to missing constants like `DTLS_SERVER_METHOD`.
These features have been introduced in https://github.com/pyca/pyopenssl/commit/e84e7b57d1838de70ab7a27089fbee78ce0d2106. Pumping to version 22 solves the issue.

Require pyOpenSSL version 22.

---

CHANGELOG.md
mitmproxy/contentviews/grpc.py
test/mitmproxy/contentviews/test_grpc.py

content-type `application/prpc` is being used for gRPC communication by a chromium infra tool, luci-go/cipd. seems to be an internal abstraction over gRPC?
luci-go/cipd source code: https://chromium.googlesource.com/infra/luci/luci-go/+/refs/heads/main/cipd/
luci-go/cipd binary builds: https://chrome-infra-packages.appspot.com/p/infra/tools/cipd
example flows from luci-go/cipd: https://matrix.laura.pm/_matrix/media/r0/download/laura.pm/iFkCPHZPthZJgzzLGiAviixw

render application/prpc as grpc protobuf

---

mitmproxy/addons/tlsconfig.py
mitmproxy/net/tls.py
test/mitmproxy/net/test_tls.py

This should cause not functional differences, but increase performance and memory usage.
Currently depends on unreleased cryptography bindings which will be part of the 38.0 release (https://github.com/pyca/cryptography/pull/7210).

share `SSL.Context` for all client <-> proxy connections

---

release/docker/DockerHub-README.md
release/docker/docker-entrypoint.sh

This PR changes our Docker entrypoint to not blindly `chown` an existing `~/.mitmproxy` folder, but instead just assume the uid/gid of the existing user. This idea was born out of #5419 to make sure that we don't break setups.
Not sure if this is the right approach, I'd definitely appreciate a second pair of eyes with more Docker experience.

Docker: assume uid of who holds permissions

---

web/src/js/__tests__/components/ProxyAppSpec.tsx
web/src/js/__tests__/components/contentviews/HttpMessageSpec.tsx
web/src/js/components/FlowView/Messages.tsx
web/src/js/components/contentviews/HttpMessage.tsx
web/src/js/components/contentviews/useContent.tsx

Make mitmweb use option "content_view_lines_cutoff" (https://github.com/mitmproxy/mitmproxy/issues/5398)
The previous pr was automatically merged as I tried the sync fork feature of github.
The content_view_lines_cutoff is used when viewing details of the request. so the component needs to wait response before rendering.

Make mitmweb use option "content_view_lines_cutoff"

---

web/src/js/__tests__/components/FlowTable/__snapshots__/FlowColumnsSpec.tsx.snap
web/src/js/components/FlowTable/FlowColumns.tsx

issue #5198 mitmWeb crashed when scroll the window, and get error message like this:
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
code Logic:
Function "onViewportUpdate()" is used to control how many flows displayed in flow-table, In component FlowTable(components/Modal/FlowTable.jsx).
When user scroll the "flow-table", the procedure is as follows:
step1 div whose className is"flow-table" onScroll callback onViewportUpdate() is called
step2 setState({vScroll, viewportTop}) after calcVScroll()
step3 componentDidUpdate() is called to update component "FlowTable"
step4 onViewportUpdate() is called again
step5 normally …

fix issue #5198: mitmWeb crash

---

CHANGELOG.md
examples/contrib/http_manipulate_cookies.py

Improve the example helper functions to use the get_all functions recommended in the Header class docs for use with cookies data. This will avoid errors when dealing with multiple headers.
https://github.com/mitmproxy/mitmproxy/blob/cf655a664fda68de9f80de2056beabef95fafeb1/mitmproxy/http.py#L148 https://github.com/mitmproxy/mitmproxy/blob/cf655a664fda68de9f80de2056beabef95fafeb1/mitmproxy/http.py#L91

Improve http_manipulate_cookies.py example

---

mitmproxy/addons/dumper.py
mitmproxy/command.py
mitmproxy/net/udp.py
mitmproxy/proxy/layers/http/_http1.py
mitmproxy/proxy/layers/http/_upstream_proxy.py
mitmproxy/proxy/mode_servers.py
mitmproxy/proxy/server.py
test/mitmproxy/net/test_udp.py
tox.ini

Turns out mypy works better if you also install dependencies in the relevant tox environment. 🙃 
@decathorpe: This works now due to your new mitmproxy-wireguard version. If I manually install the old one, mypy now correctly complains about the missing `is_closing` method.

Re-add `is_closing` check, fixup mypy.

---

CHANGELOG.md
mitmproxy/tools/web/webaddons.py

Fixes #5522
mitmweb now opens for me properly on Ubuntu 22.04

Fix mitmweb not properly opening a browser and being stuck on some Linux

---

docs/src/content/concepts-modes.md
docs/src/content/howto-transparent.md

There's a new section for "wireguard" mode in the "Modes of operation" page, below the existing docs for the "transparent" mode. I included documentation for all configuration knobs (i.e. how to specify the path to the file with encryption keys, and how to set a custom listen port) and a short explanation of the limitations of the new mode.
I also added a short note to the "Transparent HOWTO" page pointing out that the new WireGuard mode might be easier to use and that it works on Windows (which `--mode transparent` apparently doesn't? TIL).

docs: add documentation for wireguard mode

---

README.md

Pretty straightforward: The current "dev docs" badge points to a non-existent page (<https://docs.mitmproxy.org/main/>), the actual link to deployed docs for "main" is at <https://docs.mitmproxy.org/dev/>.

README: fix link to "dev" documentation in badge

---

examples/contrib/har_dump.py

Dump the real url rather than the url containing ip address when mitmproxy works in transparent mode.
Currently, flow.request.url shows the ip address rather than host name when mitmproxy works on transparent mode.
flow.request.pretty_url can show the correct url.

har_dump.py - get real url in transparent mode

---

CHANGELOG.md
mitmproxy/contentviews/json.py
mitmproxy/contentviews/msgpack.py
mitmproxy/tools/console/palettes.py
test/mitmproxy/contentviews/test_json.py
test/mitmproxy/contentviews/test_msgpack.py
web/src/css/contentview.less

Adds support for syntax highlighting in the mitmweb content view for JSON and msgpack bodies. Closes #5623
Visually speaking, they look identical in the content view, except msgpack supports a few types which JSON does not. These are left unhighlighted, but the formatting function should be easy to extend to cover these if desired.
Summary of changes:
- Modified existing JSON token labelling function to distinguish keys from regular strings
- Modified msgpack formatting function to add token labelling 
- Added stylesheet colours for msgpack and json colours 
- I just picked a few random colours that looked half-decent, but I haven't given too much thought to accessibility/colourblindness. Open to discussion on changing these.
- Modified test_json.py and test_msgpack.py to test the output …

Add content view syntax highlighting for JSON and msgpack

---

CHANGELOG.md
web/src/js/__tests__/components/__snapshots__/FlowTableSpec.tsx.snap
web/src/js/__tests__/components/helpers/VirtualScrollSpec.tsx
web/src/js/components/FlowTable.jsx
web/src/js/components/helpers/VirtualScroll.tsx

This PR is an alternative fix for #5658: `calcVScroll` now bounds viewportTop so that additional checks should not be necessary.
@LIU-shuyi, can you verify that this works as expected please? 😃

fix vScroll calcuation, refs #5658

---

examples/contrib/har_dump.py

Firefox Developer Tools reject to load HAR files that do not have `har.log.pages` element (see
<https://bugzilla.mozilla.org/show_bug.cgi?id=1691240>). Adding a placeholder entry fixes it.

Make HAR files compatible with Firefox DevTools

---

examples/contrib/har_dump.py

I wanted to dump websocket messages in har file under entries.
Like:
**<details><summary>mitmdump.har:</summary>**
<p>
```json
{
"log": {
"version": "1.2",
"creator": {
"name": "mitmproxy har_dump",
"version": "0.1",
"comment": "mitmproxy version mitmproxy 9.0.0.dev"
},
"entries": [
{
"startedDateTime": "2022-10-20T08:48:38.013394+00:00",
"time": 900,
"request": {
"method": "GET",
"url": "https://demo.piesocket.com/v3/channel_1?api_key=VCXCEuvhGcBDP7XhiJJUDvR1e1D3eiVjgZ9VRiaV&notify_self",
"httpVersion": "HTTP/1.1",
"cookies": [
{
"name": "_ga",
"value": "GA1.2.1088248006.1666255585",
"httpOnly": false,
"secure": false
},
{
"name": "_gid",
"value": "GA1.2.117276119.1666255585",
"httpOnly": false,
"secure": false
}
],
"headers": [
{
"name": "Host",
"value": "demo.piesocket.com"
},
{ …
```

add websocket messages in HAR file

---

mitmproxy/tools/console/consoleaddons.py

Fixed the incorrect docstring of console.view.eventlog inside `tools/console/consoleaddons.py`. Fixes issue #5671

Fixed docstring of console.view.eventlog

---

CHANGELOG.md
mitmproxy/addons/browser.py

When starting a browser with `browser.start` and the `listen_port` value set to default the proxy is started with `--proxy-server=127.0.0.1:None`. This causes Chrome to ignore the proxy.

Fix missing proxy port when starting a browser.

---

CHANGELOG.md
mitmproxy/addons/termlog.py
test/mitmproxy/addons/test_termlog.py

Supersedes #5133, fixes #4669
I cannot figure out how to actually trigger the raise in the test (it successfully logs the `info` log), but I verified that the fix itself works.

Hard exit when mitmproxy cannot write logs

---

examples/contrib/har_dump.py

The currently used implementation in browsers is HAR version 1.2. The `Pages` object is not required and can be an empty list. According to the documentation below, in case we decide to include other objects in the `Pages` list, they should contain four defined keys: `startedDateTime`, `id`, `title` and `pageTimings`. As it stands, only the `pageTimings` field is defined, which is redundant because it is empty.
Defining only one field can mislead third-party tools (such as `har-to-k6` [https://github.com/grafana/har-to-k6], which incorrectly reads fields for this very reason), because on the one hand we indicate that there is an object inside the `Pages` list, while it is incomplete. We can read in the documentation that:
> In case when an HTTP trace tool isn't able to group requests by a …

One of several required fields of the Pages object deleted (pageTimings)

---

.github/workflows/main.yml

It looks like codecov finally shut down their v1 API, so we need to update to v3. The official codecov action is unusable for us as it cannot pinned, so I've come up with a custom action that is more sane.

Use latest codecov uploader

---

CHANGELOG.md
mitmproxy/addons/serverplayback.py
test/mitmproxy/addons/test_serverplayback.py

Added a command `replay.server.add` for appending flows to server replay responses.
I find it easier to use when you need to add new flows for server playback instead of replacing them.

Added a command for appending flows to server replay list

---

test/mitmproxy/net/http/test_cookies.py

Background:
As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +16 years, because that is how long I expect some software will be used in some places.
This showed up failing tests in our package build.
See https://reproducible-builds.org/ for why this matters.
Make tests pass after 2037

Fix tests after 2037

---

examples/contrib/mitmproxywrapper.py

- Add `-w` option to run `mitmweb` instead of `mitmproxy`.
- Add `-P` option to choose a random port.
- Clean up proxy settings on `^C`.

Add enhancements for contrib/mitmproxywrapper.py

---

docs/src/content/concepts-certificates.md
mitmproxy/addons/onboardingapp/templates/index.html

Added instructions to install mitmproxy-ca-cert.pem on fedora.

Add Fedora certificate installation instructions

---

CHANGELOG.md
mitmproxy/contentviews/raw.py
test/mitmproxy/contentviews/test_raw.py

Removed escaping string to get real raw view

---

mitmproxy/proxy/layers/http/_http2.py
test/mitmproxy/proxy/layers/http/test_http2.py

Temporary fix for #5880. `AlternativeServiceAvailable` event will generate a log command. I'm unsure if the test I've written is correct, please suggest changes if it isn't

temporary fix for unhandled AlternativeServiceAvailable event

---

CHANGELOG.md
examples/contrib/tls_passthrough.py

when peername returned None, the script would not working. use serveral alternatives for `server_address` variable.
- [*] I have updated tests where applicable.
- [*] I have added an entry to the CHANGELOG.

Fix server addr issue in tls_passthrough example.

---

release/docker/docker-entrypoint.sh

Current docker-entrypoint.sh [0][1] runs
gosu mitmproxy "$@"
for mitmproxy, mitmdump and mitmweb. There is a problem with this
approach: bash becomes a parent process for mitmproxy [2][3], but when
signals are sent by docker-compose to mitmproxy container they are sent
to bash, but they are not delivered to mitmproxy [4]. This leads to a
slow shutdown of the container, because by default docker sends SIGTERM,
waits for 10 seconds and then sends SIGKILL if the container is still
alive [5].
This patch solves the issue by replacing bash process with mitmproxy
entirely using "exec" - this way the signals are delivered to mitmproxy
directly.
To test the patch a Dockerfile [6] that applies the patch to the release
image from the dockerhub could be used along with slighly modified
compose.yml …

pass signals to mitmproxy in docker-entrypoint.sh

---

CHANGELOG.md
mitmproxy/tools/console/flowview.py

Fixes #5921. In the stream view for TCP and UDP flows in the console, the direction indicators (from client, to client) would always alternate and not represent the actual direction. This PR fixes that bug.

console: fix bug that caused wrong direction indicators in message stream flow view

---

CHANGELOG.md
docs/src/content/howto-install-system-trusted-ca-android.md

Using Magisk and a Magisk module containing the mitmproxy CA certificate, one can use Google Play builds with mitmproxy. Previously, the documentation stated that this is not possible.
- [N/A] I have updated tests where applicable.

Add a section on using Magisk and Magisk modules in the Android howto

---

test/mitmproxy/proxy/test_mode_servers.py

The wireguard test only check the system but didn't check the architecture.
For example, a non-x86 machine running Linux will fail the test.
Because the binary file is hardcoded in the test, I added the architecture check to skip the wireguard test on non-x86 machine.

fix: add the architecture determination when running the wireguard test

---

CHANGELOG.md
mitmproxy/addons/next_layer.py
mitmproxy/connection.py
mitmproxy/net/tls.py
mitmproxy/options.py
mitmproxy/proxy/layers/http/__init__.py
mitmproxy/proxy/layers/modes.py
mitmproxy/proxy/layers/quic.py
mitmproxy/proxy/layers/tls.py
mitmproxy/proxy/tunnel.py
setup.cfg
setup.py
test/mitmproxy/addons/test_next_layer.py
test/mitmproxy/addons/test_proxyserver.py
test/mitmproxy/contentviews/test_http3.py
test/mitmproxy/net/test_tls.py
test/mitmproxy/proxy/layers/test_modes.py
test/mitmproxy/proxy/layers/test_quic.py
test/mitmproxy/proxy/layers/test_tls.py
web/src/js/ducks/_options_gen.ts

This PR makes our logic to determine the next protocol layer more explicit, and handles UDP and TCP in a uniform way. We also now make heavy use of `match` statements combined with `typing.assert_never`, which allows us to assert that we exhaust all options in many cases. Finally, I'm adding an `http3` option which can be used to block QUIC traffic in transparent mode. 🎉

Update next layer detection, add option to block HTTP/3.

---

.github/workflows/autofix.yml
web/README.md
web/package.json

I prefer that over `npx`. You can also locally run `npm run prettier` to update all files without knowing the cli arguments for prettier.

Add a prettier npm script

---

mitmproxy/proxy/__init__.py

Fixed a small typo in `__init__.py`.

Fixed typo in `__init__.py`

---

mitmproxy/command.py

Fixes execution of commands from modules with `from __future__ import annotations`
Resolves #6029

Command signature inspection fix (#6029)

---

web/src/js/components/helpers/AutoScroll.tsx

Fixed a bug that could prevent mitmweb autoscroll from working properly.
This bug was caused by the fact that clientHeight and scrollHeight returned integers, but scrollTop returned a decimal number.
[https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface](https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface)

Fixed a bug with auto scroll in mitmweb

---

release/docker/DockerHub-README.md

Being unfamiliar with the docker options, I thought the square brackets could be part of the command.
Instead, they refer to the sentence *after* the command, that is, they meant "optionally".
To remove the ambiguity, I put it onto different lines with an explanation.
I think neither are applicable?

DockerHub-README.md: reword ambiguous command

---

CHANGELOG.md
mitmproxy/tools/console/defaultkeys.py
mitmproxy/tools/console/keymap.py

The escape key can now be used to exit the current view, alongside the pre-existing `q` key. Fixes #6085.

Add escape key as another shortcut to exit current view.

---

CHANGELOG.md
mitmproxy/contentviews/grpc.py

Adds zstd to valid gRPC encoding schemes. Spotted some `grpc-encoding: zstd` in the wild, and this trivial fix was found working.
(I assume existing gzip test is acceptable, we're relying on `mitmproxy.net.encoding.decode()` anyway)

grpc: enable decompressing zstd responses

---

CHANGELOG.md
mitmproxy/addons/tlsconfig.py
test/mitmproxy/addons/test_tlsconfig.py

this unbreaks reverse proxy setups that are directly addressed by IP.

Always include either SNI or target IP address as SAN

---

mitmproxy/proxy/layers/quic.py
mitmproxy/proxy/mode_servers.py
mitmproxy/proxy/mode_specs.py
test/mitmproxy/addons/test_proxyserver.py
test/mitmproxy/proxy/test_mode_servers.py
test/mitmproxy/proxy/test_mode_specs.py

Those will come back after shipping a reverse-proxy MVP.

Temporarily disable half-broken HTTP/3 modes

---

CHANGELOG.md
mitmproxy/addons/tlsconfig.py
mitmproxy/net/tls.py
test/mitmproxy/net/test_tls.py

This PR fixes the issue discussed in #5422 when connecting to a server with outdated/misconfigured SSL. This is a draft PR to discuss if a full PR would be accepted. A full PR would only add the `OP_LEGACY_SERVER_CONNECT` SSL context flag if the `ssl_insecure` switch is passed.

Enable unsafe legacy SSL renegotiation

---

mitmproxy/addonmanager.py
mitmproxy/addons/asgiapp.py
mitmproxy/addons/clientplayback.py
mitmproxy/addons/script.py
mitmproxy/log.py
mitmproxy/master.py
mitmproxy/proxy/server.py
test/mitmproxy/addons/test_script.py

Instead of formatting the traceback on site, we not pass the exception info to the logging machinery. This allows addons to hook in and for example report to Sentry.
/cc @erikshestopal @kgriffs

Improve how we log tracebacks

---

mitmproxy/addons/proxyserver.py
mitmproxy/master.py
mitmproxy/proxy/mode_servers.py
test/mitmproxy/addons/test_proxyserver.py

This fixes compatibilit with the new macOS transparent mode, where the client's peername is unspecified (which otherwise leads to duplicates).

Use `client.id` as connection id where possible

---

CHANGELOG.md
mitmproxy/tools/web/master.py

A temporary fix to allow up to 4GB dump to be uploaded by supplying max_buffer_size of the HTTPServer constructor to be 2**32 (4GB).
(Perhaps it is better to be a configurable item, or change the post mechanism to stream instead if there ever is any security concern implied due to usage or hardware limitations)
By default, if no argument is supplied, the maximum buffer size is 100MB, which causes saved dump file to be unreadable through the web interface.
Reference Documentation: [Link](https://www.tornadoweb.org/en/stable/httpclient.html#:~:text=a%20simple%20mapping.-,max_buffer_size,-(default%20100MB)%20is)
Possibly:
Resolves #4651, resolves #5609

mitmweb: Allow up to 4GB dump to be uploaded

---

CHANGELOG.md
mitmproxy/certs.py

`Cert.dummy_cert` creates certificates for domains and signs them with the configured CA certificate. Currently, these certificates are generated without the `SubjectKeyIdentifier` or `AuthorityKeyIdentifier` extensions. Normally this is fine, however in OpenSSL 3.x, it is required that these extensions be present if `X509_V_FLAG_X509_STRICT` is set. For such clients, mitmproxy right now serves "broken" certificates and nothing works. With this change, we add those two extensions to get the certificates generated by `dummy_cert` in compliance with those strict checks.

fix certificates generated by dummy_cert on clients that require AuthorityKeyIdentifier

---

CHANGELOG.md
mitmproxy/addons/onboardingapp/templates/layout.html
mitmproxy/tools/web/templates/index.html
test/mitmproxy/tools/web/test_app.py
web/src/js/backends/websocket.tsx
web/src/templates/index.html

mitmweb currently serves up urls that are relative to the document root of the webserver, e.g. `/static/app.js`
This is fine when running mitmweb in a conventional sense, i.e. running on one machine and clients directly connecting to it.
However, if the mitmweb server is provided as part of another document tree, it may not be at the top level.  This causes connections to `/static/app.js`, as well as all other assets and the `/updates` websocket to not work correctly, as they now point to a page that does not exist on that server
For example:
Working ok:
```
https://example.com/index.html
-->https://example.com/static/app.js
```
Not working:
```
https://example.com/mysubdir/index.html
-->https://example.com/static/app.js
```
File not found.
What we need is for index.html to reference with …

Make mitmweb use relative paths to connect to its resources.

---

CHANGELOG.md
mitmproxy/http.py

Fix path() docstring per #6345
Before:
https://docs.mitmproxy.org/stable/api/mitmproxy/http.html#Request.path
After:

Fix path() docstring per #6345

---

CHANGELOG.md
mitmproxy/addons/proxyauth.py
mitmproxy/utils/arg_check.py
test/mitmproxy/addons/test_proxyauth.py
test/mitmproxy/utils/test_arg_check.py

https://github.com/mitmproxy/mitmproxy/issues/6426
When I used ldap as a proxy authentication method, I found that the filter key was hardcoded, so I made it possible to pass in this item.

fix #6426 - Optimize LDAP Proxy Auth

---

CHANGELOG.md
mitmproxy/addons/savehar.py

Use `.get` when retrieving "path" from the `attrs` cookie dict. This avoids the occasional `KeyError`. 
Modifies a line in the `format_response_cookies` function in the `savehar.py` addon. I'm not sure if there is another underlying issue preventing the "path" key from making it into the `attrs` dict, but either way this solved issues I was experiencing.

Handle "path" KeyError in the savehar addon

---

mitmproxy/addons/errorcheck.py

It's hard to debug errors raised in addon scripts during startup as only a generic message is output on the console. Using logger.format() to format errors that occurred during startup instead of only displaying the LogRecord.msg improves the output if an exception is present by showing the stack trace. An additional newline was added for better readability.
Comparison with the load_error.py test script, before:
$ mitmproxy -s test/mitmproxy/data/addonscripts/load_error.py
Error logged during startup: Addon error:
After:
$ mitmproxy -s test/mitmproxy/data/addonscripts/load_error.py
Error logged during startup:
Addon error:
File "test/mitmproxy/data/addonscripts/load_error.py", line 2, in load
raise ValueError()
ValueError
Relates to issue #5935 and PR …

Show exception and stack trace on startup errors

---

CHANGELOG.md
mitmproxy/net/http/cookies.py
test/mitmproxy/net/http/test_cookies.py
test/mitmproxy/test_http.py

Currently when an empty cookie attribute (`Secure`, `HttpOnly` ...) is encountered while parsing a `Set-Cookie` header it will create a `CookieAttrs` object containing a (key, value) pair with an empty string for the attribute value ie:
```python
CookieAttrs[('Secure', ''), ('HttpOnly', ''), ('Path', '/')]
``` 
Resulting in an updated `Set-Cookie` header for the `Response` object with invalid values for those empty attributes ie:
```python
(b'SetCookie', b'value=XYZ; Secure=; HttpOnly=; Path=/')
``` 
My browser (Firefox 95.0.1) does not pickup these attributes so the cookie looses them.
______
This fix replaces the empty string attribute for empty cookie attributes by the value `None` ie:
```python
CookieAttrs[('Secure', None), ('HttpOnly', None), ('Path', '/')]
``` 
So that they can be …

Parse set header cookies properly

---

CHANGELOG.md
mitmproxy/optmanager.py
test/mitmproxy/data/test_config.yml
test/mitmproxy/test_optmanager.py

Make the paths to scripts found in config.yml relative to
the directory where config.yml is instead of where the command
is ran.

Make scripts in config.yml relative to config.yml

---

CHANGELOG.md
mitmproxy/http.py
mitmproxy/io/har.py
mitmproxy/io/io.py
mitmproxy/net/http/headers.py
test/mitmproxy/data/har_files/charles.json
test/mitmproxy/data/har_files/chrome.json
test/mitmproxy/data/har_files/firefox.json
test/mitmproxy/data/har_files/head-content-length.har
test/mitmproxy/data/har_files/head-content-length.json
test/mitmproxy/data/har_files/safari.json
test/mitmproxy/net/http/test_headers.py

Closes https://github.com/mitmproxy/mitmproxy/issues/6547
Responses in flows constructed from HAR files were using the `Response.make` utility which resulted in the injection of `content-length` headers. When a `content-length` header existed already, this could cause failures during replay. See the linked issue or https://github.com/mitmproxy/mitmproxy/pull/6548/commits/91bc983410b6074e44ae70500a24e3bdfefa5c6b for a concrete example.

Fix response `content-length` when reading from HAR files

---

CHANGELOG.md
mitmproxy/certs.py

This fixes #6494: if CA and leaf share the same Subject Key Identifier, SChannel gets confused. So we just skip the SKI for leafs, which is still fine with OpenSSL 3.x (this was previously fixed by @mmaxim) and RFC 5280.
@driuba did the hard work of nailing down the issue, this here is a slightly simpler (and more performant) fix for the problem.
closes #6546

do not include subject key identifier in leaf certificates

---

CHANGELOG.md
mitmproxy/tools/console/consoleaddons.py
mitmproxy/tools/console/defaultkeys.py
mitmproxy/tools/console/quickhelp.py

Changed the default keybinding for exporting flows from "e" (also used by Edit) to "x".
Resolves #6225

Change default keybind to export flow to "x"

---

CHANGELOG.md
mitmproxy/addons/tlsconfig.py
mitmproxy/certs.py
mitmproxy/tools/console/flowdetailview.py
mitmproxy/tools/web/app.py
test/mitmproxy/addons/test_tlsconfig.py
test/mitmproxy/test_certs.py

Represent SubjectAltNames as cryptography.x509.GeneralName objects, not strings.

---

README.md
docs/src/content/overview-getting-started.md

We want to focus on GitHub Discussions going forward.

Remove Links to Slack Workspace

---

docs/src/content/overview-installation.md

Currently Installation page doesn't mention that Rosetta is required on Apple Silicon. That is the case and might be confusing to some trying to install it on such a machine, without Rosetta, and get an error message of `bad CPU type in executable`.
Related to https://github.com/mitmproxy/mitmproxy/issues/6590.

Note on Installation page that Rosetta is required on Apple Silicon

---

CHANGELOG.md
mitmproxy/proxy/layers/http/__init__.py

websockets: do not process start event before redirecting event handlers

---

CHANGELOG.md
mitmproxy/addons/next_layer.py
test/mitmproxy/addons/test_next_layer.py

Regression fix: it seems that [#6594](https://github.com/mitmproxy/mitmproxy/pull/6594) has broken IPv6 connections:
```
[1]$ mitmdump --ignore-hosts mitmproxy.org
[2]$ curl -kx 'http://127.0.0.1:8080' 'https://httpbin.dmuth.org/ip/v6'
```
```
[18:18:05.571] HTTP(S) proxy listening at 127.0.0.1:8080.
[18:18:07.791][127.0.0.1:54626] client connect
[18:18:08.066][127.0.0.1:54626] server connect httpbin.dmuth.org:443 ([2a09:8280:1::6a6e]:443)
[18:18:08.405] Addon error: too many values to unpack (expected 2)
File "/usr/lib/python3.11/site-packages/mitmproxy/addons/next_layer.py", line 111, in next_layer
nextlayer.layer = self._next_layer(
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/mitmproxy/addons/next_layer.py", line 133, in _next_layer
if …
```

Fix IPv6 matches against the full host:port string

---

CHANGELOG.md
mitmproxy/addons/savehar.py
mitmproxy/test/tflow.py
test/mitmproxy/addons/test_savehar.py

Fix issue #6579
This saves failed CONNECT request URLs to HAR files correctly.

fix: save failed connect request urls to har files correctly

---

CHANGELOG.md
mitmproxy/addons/dns_resolver.py
test/mitmproxy/addons/test_dns_resolver.py
test/mitmproxy/addons/test_proxyserver.py

Fixes #6647 by assuming all DNS queries are made over UDP, will need to be reworked when TCP support is added.

Remove duplicate answers in DNS queries

---

CHANGELOG.md
mitmproxy/proxy/mode_servers.py

Fix issue #6656
This generates a wireguard config with the correct endpoint when using two or more active NICs.

fix: generate wireguard config with correct endpoint when using two or more active nics

---

mitmproxy/proxy/layers/tls.py
test/mitmproxy/proxy/layers/test_tls.py

This re-adds some log messages adjusted in 2a82674fdc7aa1b7dde398565f6524f6dbab7828. We shouldn't fail tests for this.
refs https://github.com/pyca/cryptography/pull/10391

Make tests pass on older OpenSSL

---

CHANGELOG.md
mitmproxy/certs.py

Unfortunately 0b5e310881f0116c9e8e2ca5b9da98e258de0a11 broke mitmproxy's ability to issue leaf certificates if `ca_file` contains multiple CAs. This PR restores that capability.
The issue lies in `mitmproxy/certs.py` - specifically, in the `from_files` method of the `CertStore` class. Before 0b5e310881f0116c9e8e2ca5b9da98e258de0a11, the issuing CA was identified like this:
``` python
raw = ca_file.read_bytes()
key = load_pem_private_key(raw, passphrase)
…
certs = re.split(rb"(?=-----BEGIN CERTIFICATE-----)", raw)
ca = Cert.from_pem(certs[1])
```
This worked even when `ca_file` contained multiple CAs. For example, consider this example:
```
-----BEGIN PRIVATE KEY-----
REDACTED
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MIICmTCCAfqgAwIBAgIRAIqaBJ6aU5wXT+5JAn8Uj1IwCgYIKoZIzj0EAwQwM …
```

Fix ca_file containing multiple CAs

---

CHANGELOG.md
mitmproxy/addons/serverplayback.py
test/mitmproxy/addons/test_serverplayback.py

Fixes #4506
`mitmproxy` during server-replay mode, calculates the hashes of flows from input files based on user defined filters and uses them to compare against hashes of incoming requests to serve the corresponding stored response by matching the hash. However, during runtime, if the user changes any of the filters, `mitmproxy` fails to recalculate the hashes of input flows and hence doesn't return the intended response. This PR fixes this issue by recomputing the hashes for every flow whenever a filter(option) used for computing hashes is changed.

Allow runtime modifications of HTTP flow filters for server replays

---

CHANGELOG.md
mitmproxy/addons/next_layer.py
test/mitmproxy/addons/test_next_layer.py

The mutual exclusivity of the allow-hosts and ignore-hosts parameters looks like an unnecessary obstacle and does not make much sense.
It is very convenient to use a proxy only for the domain of your service, but at the same time ignore some subdomains, especially when they serve some kind of CDNs with a large amount of data.
Although this filtering could be implemented using regexp with negative lookahead, but it complicates configuration and is not as clear as conjuction of allow and deny filters.

Allow --allow-hosts and --ignore-hosts to work together

---

test/mitmproxy/addons/test_script.py

This allows the "nonexistent" file error check to pass on systems that don't use English as their primary language. With this, all mitmproxy tests can pass on non-English machines.
Fixes #6723

Update error check on test_load_script

---

CHANGELOG.md
mitmproxy/contentviews/__init__.py
mitmproxy/contentviews/multipart.py
test/mitmproxy/contentviews/test_api.py
test/mitmproxy/contentviews/test_multipart.py

On get_message_content_view, the content type wasn't including the boundary, and was only setting the MIME type. This made the multipart content view unusable, as the boundary was required on parsing. To fix the issue, we assign the full content type instead.
This wasn't triggered by any previous tests because they would test against the multipart parser directly, and not the generic parser.

Fix Multipart content view parsing

---

CHANGELOG.md
pyproject.toml

This fixes some specification compliance issues as well as a potential DoS vulnerability.
Start with version 1.0.0, aioquic follows semantic versioning, so no breaking changes will occur before version 2.0.0.

Update aioquic dependency to >= 1.0.0, < 2.0.0 (fixes: #6746)

---

CHANGELOG.md
mitmproxy/proxy/server.py

Fix async `client_connected` handlers crashing mitmproxy

---

CHANGELOG.md
mitmproxy/addons/intercept.py
mitmproxy/tools/console/consoleaddons.py
mitmproxy/tools/console/flowview.py
test/mitmproxy/addons/test_intercept.py

This PR adds a feature(MVP) to allow for websocket interception and modification one at a time per flow. On the mitmweb side of things, the UI shows that websocket messages are being intercepted but there's no option to edit (yet?).
Websockets are intercepted by default if interception is on, to prevent websocket interception use `!~websocket`

Add primitive websocket interception and modification

---

CHANGELOG.md
mitmproxy/tools/main.py

The issue was reported in https://github.com/mitmproxy/mitmproxy/issues/6744
Problem description:
When there is a sudden surge of requests, mitmproxy will hit SIGPIPE (broken pipe) errors because it was trying to write to a closed socket. The stacktrace is:
File "asyncio/runners.py", line 44, in run
File "asyncio/base_events.py", line 636, in run_until_complete
File "asyncio/base_events.py", line 603, in run_forever
File "asyncio/base_events.py", line 1909, in _run_once
File "asyncio/events.py", line 80, in _run
File "mitmproxy/proxy/server.py", line 294, in handle_connection
File "mitmproxy/proxy/server.py", line 407, in server_event
File "asyncio/streams.py", line 325, in write
File "asyncio/selector_events.py", line 924, in write
When this happens, the process terminates unless handled …

Setting SIG_IGN for SIGPIPE errors

---

.github/workflows/main.yml
CHANGELOG.md
release/build-and-deploy-docker.py
release/build.py
release/deploy.py
release/release.py

This got lost with mitmproxy 9 somehow. the plan is to recreate those tags with 'v', and then keep using 'v' going forward.

Prefix version tags with 'v'

---

pyproject.toml

See https://github.com/pytest-dev/pytest/issues/12263

Temporarily prohibit pytest 8.2.0 in order to fix CI

---

CHANGELOG.md
mitmproxy/proxy/layers/http/_http_h2.py

Do not mutate data when splitting it into outbound_frame_size-sized chunks, as discussed in #6873.

Fix slowdown when sending large data over HTTP/2 (#6873)

---

mitmproxy/net/local_ip.py

When ipv6 is disabled completed (e.g, in grub), _socket.socket_ throws OSError exception.
The _get_local_ipv6_ function should return None in this case

fix: OSError raised when ipv6 is disabled

---

CHANGELOG.md
mitmproxy/proxy/layers/http/__init__.py
mitmproxy/proxy/utils.py
test/mitmproxy/proxy/test_utils.py

Fix issue #6944: Optimize response/request_body_buf by using a list of byte chunks to avoid concatenation overhead.

Fix issue #6944: Optimize response/request_body_buf by using list of byte chunks to avoid concatenation overhead

---

mitmproxy/net/dns/domain_names.py
mitmproxy/net/dns/https_records.py
test/mitmproxy/net/dns/test_domain_names.py
test/mitmproxy/net/dns/test_https_records.py

Use existing API from `mitmproxy/net/dns/domain_names` to unpack/pack domain names found in HTTPS records

Use existing API to unpack/pack domain names in HTTPS records

---

test/mitmproxy/proxy/layers/test_quic.py

To exercise incompatible version negotiation, we must not use version 0, as this would cause the client's INITIAL packet to be erroneously interpreted as a VERSION_NEGOTIATION packet - but with a corrupt format.
So far this has not caused any errors, because aioquic's `pull_quic_header` did not fully parse VERSION_NEGOTIATION packets, but this will change with the next aioquic version.
Use one of the reserved version numbers of the form 0x?a?a?a?a, as defined in https://datatracker.ietf.org/doc/html/rfc9000#section-15

Fix QUIC version negotiation test

---

CHANGELOG.md
mitmproxy/addons/next_layer.py
test/helper_tools/loggrep.py
test/mitmproxy/addons/test_next_layer.py

This PR fixes the issue reported by @JarLob in https://github.com/mitmproxy/mitmproxy/issues/5064#issuecomment-2211403259. The problem here was that we did not take an already-parsed SNI into account, but were only looking at TLS handshakes that were happening _just now_.

Incorporate existing SNI into allow/ignore decision, fix #5064

---

CHANGELOG.md
mitmproxy/addons/dns_resolver.py
mitmproxy/dns.py
pyproject.toml
test/mitmproxy/addons/test_dns_resolver.py
test/mitmproxy/addons/test_proxyserver.py
web/src/js/ducks/_options_gen.ts

Uses `mitmproxy_rs.DnsResolver` to resolve domain names that need to be checked in the hosts file first and forwards any other type of query to the server specified in the options
Fixes https://github.com/mitmproxy/mitmproxy/issues/6739
~TODO: check and fix tests after we release latest version of `mitmproxy_rs`~

Support all query types in DNS mode

---

mitmproxy/addons/block.py
test/mitmproxy/addons/test_block.py

We don't want the block addon, which safeguards against public internet access for regular proxies, to interfere with local mode. On macOS, the peername here is our interface's IP address, which may be public.

Do not block local mode connections

---

mitmproxy/addons/next_layer.py
mitmproxy/options.py
mitmproxy/proxy/layers/quic.py
mitmproxy/proxy/layers/tls.py
test/mitmproxy/addons/test_next_layer.py
test/mitmproxy/addons/test_tlsconfig.py
web/src/js/ducks/_options_gen.ts

With these changes I can get (static-curl, macOS, local mode) to work. 🎉 
Does that help with any of the other entries on our matrix?

Add experimental option for HTTP/3 in transparent mode

---

CHANGELOG.md
mitmproxy/addons/dns_resolver.py
test/mitmproxy/addons/test_dns_resolver.py

Fixes #7064 
`mitmproxy_rs.get_system_dns_servers()` might fail with `RuntimeError`s, which would crash mitmproxy while initializing `DnsResolver`'s attributes during startup. We fix this by making `DnsResolver.resolver` and `DnsResolver.name_servers` as cached functions instead of cached properties

Make `DnsResolver.resolver` and `DnsResolver.name_servers` as cached functions instead of cached properties

---

web/src/js/__tests__/ducks/modes/regularSpec.tsx
web/src/js/__tests__/ducks/modes/wireguardSpec.tsx
web/src/js/components/Modes/Regular.tsx
web/src/js/components/Modes/Wireguard.tsx
web/src/js/ducks/modes/regular.ts
web/src/js/ducks/modes/wireguard.ts

In this PR, I've added the logic for setting the `listen_host` and the `listen_port` to the wireguard mode and just the `listen_host` to the regular, since it was missing :)

Add listen_host and listen_port to wireguard and listen_host to regular

---

CHANGELOG.md
mitmproxy/addons/next_layer.py
test/mitmproxy/addons/test_next_layer.py

add a filter to non-tcp connections for full alphabetics tcp connection
this depends of first word in tcp payload
after split by whitespace and checking length of that

support full alpha tcp connection

---

mitmproxy/tools/web/app.py
web/gen/state_js.py
web/src/js/__tests__/ducks/_tbackendstate.ts
web/src/js/components/Modes.tsx
web/src/js/ducks/backendState.ts

In this PR, we hide the local mode when mitmweb is running on Linux. I chose to hide the mode entirely rather than grey it out, as the message "Remaining modes are coming soon" is already present.

hide local mode on linux in mitmweb

---

CHANGELOG.md
mitmproxy/addons/__init__.py
mitmproxy/addons/update_alt_svc.py
test/mitmproxy/addons/test_update_alt_svc.py
web/src/js/ducks/_options_gen.ts

Alt-Svc headers in HTTP responses advertise the host to use while migrating from HTTP1/2 to HTTP3 (amongst other information). This addon modifies the hosts specified in this header to our reverse proxy target.
refs #7025

Addon to update the ports in alt-svc header in reverse mode

---

mitmproxy/proxy/layers/http/_http3.py
mitmproxy/proxy/layers/http/_http_h3.py
mitmproxy/proxy/layers/quic.py
test/mitmproxy/proxy/layers/http/test_http3.py
test/mitmproxy/proxy/layers/test_quic.py
test/mitmproxy/proxy/tutils.py

This PR fixes a bunch of smaller QUIC and HTTP/3 things. Most notably, it removes all support for PUSH_PROMISE frames. mitmproxy will not advertise PUSH_PROMISE support going forward, matching our current HTTP/2 implementation. We haven't received a single complaint or feature request after removing HTTP/2 push promise support, so we shouldn't burden ourselves with a half-completed HTTP/3 variant.
The easiest way to remove this is probably to go commit-by-commit.

Miscellaneous QUIC Improvements

---

CHANGELOG.md
mitmproxy/io/tnetstring.py
test/mitmproxy/io/test_tnetstring.py

Fix #7120
**Note to reviewers:** I had to add commit 5a67118a37e811c3fe8c402f835547aef1a381a3 to accomodate the existing pytest. The reason is that in `test/mitmproxy/io/test_tnetstring.py` the function `tnetstring.pop` is called directly and bytes are passed as `data` argument. However, as far as I can tell, `pop` is never called directly in mitmproxy main code but only indirectly through the `tnetstring.parse` and `tnetstring.loads` functions. I let you decided whether it is better to modify calls to `pop` in `test_tnetstring.py` and discard commit 5a67118a37e811c3fe8c402f835547aef1a381a3 or keep it as it is.

Optimize tnet parsing

---

CHANGELOG.md
mitmproxy/addons/dns_resolver.py
mitmproxy/dns.py
mitmproxy/proxy/layers/dns.py
pyproject.toml
test/mitmproxy/addons/test_dns_resolver.py
test/mitmproxy/proxy/layers/test_dns.py
test/mitmproxy/test_dns.py

Fixes https://github.com/mitmproxy/mitmproxy/issues/7116
Fixes https://github.com/mitmproxy/mitmproxy/issues/7092
Fixes https://github.com/mitmproxy/mitmproxy/issues/7074
Obsoletes https://github.com/mitmproxy/mitmproxy/pull/7115
Depends on https://github.com/mitmproxy/mitmproxy_rs/pull/169 (and a mitmproxy_rs release)

DNS resolver: add getaddrinfo fallback, fix test duration

---

web/src/css/mode.less
web/src/js/components/Modes.tsx

In this PR, I've improve the design of the capture page by highlighting the recommended modes. Ref: #7063

Improve design capture page

---

web/src/css/mode.less
web/src/js/components/Modes/Reverse.tsx

In this PR, I've improved the UX of the dropdown when selecting the protocols for the reverse mode. Ref: #7063

improve UX reverse dropdown

---

mitmproxy/tools/console/grideditor/col_bytes.py

Trying to change string based options such as `mode` or `dns_name_servers` results in a `AttributeError: 'AttrMap' object has no attribute 'get_text'`.
cause: https://github.com/mitmproxy/mitmproxy/pull/7098

Fix error while changing string-based options

---

CHANGELOG.md
mitmproxy/io/har.py
test/mitmproxy/data/har_files/charles.json
test/mitmproxy/data/har_files/chrome.json
test/mitmproxy/data/har_files/firefox.json
test/mitmproxy/data/har_files/head-content-length.json
test/mitmproxy/data/har_files/insomnia.json
test/mitmproxy/data/har_files/postdata.json
test/mitmproxy/data/har_files/safari.json
test/mitmproxy/data/har_files/with-bom.json

Duration in `log.entries[].time` is specified in milliseconds, but was interpreted as seconds in `har.py: request_to_flow`. Which led to scary `123s` instead of real `123ms`.

Fix of duration in import from HAR

---

CHANGELOG.md
docs/src/content/concepts-certificates.md
mitmproxy/addons/tlsconfig.py
web/src/js/ducks/_options_gen.ts

This capability was already built-in but hard-coded to be disabled. Making it configurable as option (defaulting to off) enables mTLS connections between clients and mitmproxy. If true, mitmproxy will send a TLS `CertificateRequest` message to the client during the TLS handshake, upon which a client needs to present a client certificate to mitmproxy to successfully establish an mTLS connection.
This option can be used together with the `client_certs` option to also establish an mTLS connection between mitmproxy and the upstream server. In this case, mitmproxy needs to have a full client cert, including matching private key, that is trusted and accepted by the upstream server. This is a common scenario with MQTT or IoT connections.
Example usage:
$ mitmproxy --set request_client_cert=True …

options: add request_client_cert to enable mutual TLS

---

CHANGELOG.md
mitmproxy/addons/core.py

"Un-set all marks" is implemented as `flow.mark @all false`
`_MarkerType()` coerces `False` into `""`, but this was previously unsupported by `flow.mark`. This previously caused `flow.mark` to error with "invalid marker value".
https://github.com/mitmproxy/mitmproxy/blob/2c1802692ddb99b8d02a353d8382772029168616/mitmproxy/types.py#L457-L464
Add a check for the empty string to `flow.mark` to fix this.
I assume this previously worked, but the error checking got too strict at some point.

Support empty string as marker in flow.mark

---

mitmproxy/contentviews/__init__.py

Many protocols have different encodings between requests and responses, to properly deserialize the message we need to know whether the message is `from_client`. The current implementation of `get_message_content_view` only forwarded the message to `View.__call__` only if the message is HTTP/TCP/UDP, but the parameter is dropped if it is of any other classes. This PR handled the case when the `message` is a `WebSocketMessage`, so a custom View can now inspect the direction through the `websocket_message` kwarg.

allow custom content view to refer to the current websocket message

---

CHANGELOG.md
mitmproxy/proxy/layers/http/__init__.py
test/mitmproxy/proxy/layers/http/test_http2.py
test/mitmproxy/proxy/layers/test_websocket.py

I encountered an issue where mitmdump was failing with a request that was working in the browser. It was a GET request with no body but the server was throwing an error about GET request having a body.
After looking at packet captures the difference between mitmdump and browser was that browser was sending `END STREAM` on the `HEADERS` frame whereas mitmdump was sending an empty `DATA` frame with `END STREAM`.
I patched mitmdump to propogate `END STREAM` if it is present on the downstream `HEADERS` frame.
Tests pass and my test case works, could anyone elaborate if this can cause other issues? If so I can adjust this to get to a state where this can be merged - since this is breaking for me ill roll with a local patch now but it would be great to use an official release.

Propogate end_stream from downstream http/2 requests

---

CHANGELOG.md
mitmproxy/addons/next_layer.py
mitmproxy/options.py
mitmproxy/tools/cmdline.py
test/mitmproxy/addons/test_next_layer.py
web/src/js/ducks/_options_gen.ts

Maybe a bit counterintuitive, but mitmproxy is very nice even without the MITM part.  When doing `--ignore-hosts '.*'` it is not possible to see SNI's, so add new flag to show the raw TCP/UDP streams.
Fixes #6421
Running `mitmproxy --ignore-hosts '.*' --show-ignored-hosts`:

Add `--show-ignored-hosts`

---

CHANGELOG.md
mitmproxy/addons/next_layer.py
test/mitmproxy/addons/test_next_layer.py

Improve the HTTP detection heuristic introduced in this PR: https://github.com/mitmproxy/mitmproxy/pull/7087
In my mitmproxy `transparent` mode setup, [testcontainer's](https://testcontainers.com/getting-started/) ryuk breaks because it sends the string below in raw TCP
```
label=org.testcontainers.version=0.30.0&label=org.testcontainers.sessionId=eb48d24ade2174c56e8951a306241ad68eccdd8fcb7686b62ed03e638ec73870&label=org.testcontainers=true&label=org.testcontainers.lang=go\n
```
Upon checking the proxy log, I found out that mitmproxy thinks that it's an HTTP protocol and try to parse it as such, causing the connection to appear as "stuck"

Improve HTTP detection heuristic

---

docs/src/content/overview-installation.md

mitmproxy now supplies native Apple Silicon binaries, even on honebrew. this shouldn't be needed anymore

Remove Apple Silicon note

---

CHANGELOG.md
mitmproxy/addons/tlsconfig.py
mitmproxy/net/tls.py
mitmproxy/options.py
test/mitmproxy/addons/test_tlsconfig.py

I was looking to make our Docker builds support older TLS versions, only to find out that the OpenSSL version is perfectly fine - we only need to set `@SECLEVEL=0`, see https://github.com/pyca/cryptography/issues/9523.

Set `@SECLEVEL=0` if old TLS versions are requested

---

web/src/css/mode.less
web/src/js/components/Modes.tsx
web/src/js/components/Modes/MissingMode.tsx

In this PR, instead of removing the mode on unsupported platforms, I'm displaying it as grayed-out. This improves the overall user experience.
Ref: #7063

Display Grayed-Out Mode for Unsupported Platforms

---

web/src/js/__tests__/components/Modes/LocalDropdownSpec.tsx
web/src/js/components/Modes/Local.tsx
web/src/js/components/Modes/LocalDropdown.tsx

In this PR, I've added the ability to include executable names that are not part of the current list. The addition occurs when pressing the **Enter** key. This change addresses and closes issue #7063.
https://github.com/user-attachments/assets/1151ab92-f81a-4334-b436-bdd8573377f8

Arbitrary strings in local mode

---

CHANGELOG.md
mitmproxy/addons/browser.py
test/mitmproxy/addons/test_browser.py

`browser.start` command will now allow for a `browser` parameter defaulting to "chrome". (Refer #5247)

Add support for starting a preconfigured Firefox instance via `browser.start` command.

---

.github/workflows/main.yml
CHANGELOG.md
mitmproxy/proxy/mode_servers.py
mitmproxy/proxy/mode_specs.py
pyproject.toml
test/conftest.py
test/mitmproxy/proxy/test_mode_servers.py
test/mitmproxy/proxy/test_mode_specs.py
web/gen/state_js.py
web/src/js/__tests__/ducks/_tbackendstate.ts
web/src/js/ducks/backendState.ts

~Depends on https://github.com/mitmproxy/mitmproxy_rs/pull/187.~
```
mitmdump --mode tun
curl --interface tun0 https://example.com
```

Add `tun` proxy mode on Linux

---

CHANGELOG.md
mitmproxy/addons/modifyheaders.py
test/mitmproxy/addons/test_modifyheaders.py

`modifyheaders` addon uses `request` and `response` hooks which, when `stream_large_bodies` is enabled, are called after headers have already been sent and can no longer be modified.
This commit changes `modifyheaders` addon to use `requestheaders` and `responseheaders` hooks.
This change aims to fix #7030

Fix interaction of modifyheaders addon with stream_large_bodies option

---

CHANGELOG.md
pyproject.toml

Hello, this is my first contribution to mitmproxy.
The `protobuf` dependency seems unused now, I think the need went away in #4349.
All the tests pass on my Mac without protobuf and hopefully CI will find if there is a need I overlooked.
If the dependency can be removed it will simplify my attempt at updating MacPorts which currently installs v7.0.4.
Also it would help some older issues - #5160, #6881
- [n/a] I have updated tests where applicable.

Remove dependency on protobuf library

---

mitmproxy/proxy/layers/http/_http_h2.py

Use `H2Connection.inbound_flow_control_window` instead of hard coding the default value while incrementing the connection flow control window.

Remove hard coded default window size for HTTP/2 connections.

---

CHANGELOG.md
mitmproxy/net/http/http1/__init__.py
mitmproxy/net/http/http1/read.py
mitmproxy/net/http/validate.py
mitmproxy/proxy/layers/http/__init__.py
mitmproxy/proxy/layers/http/_http1.py
test/mitmproxy/net/http/http1/test_read.py
test/mitmproxy/net/http/test_validate.py
test/mitmproxy/proxy/layers/http/test_http.py

This is meant to prevent request smuggling attacks over different HTTP versions.
Tracking Issue: https://github.com/mitmproxy/mitmproxy/issues/7345

Hardening: unify header validation across HTTP versions

---

CHANGELOG.md
mitmproxy/contentviews/json.py

This was discussed in https://github.com/mitmproxy/mitmproxy/discussions/5853.
I tested locally and confirmed that the JSON keys are no longer sorted.

Stop sorting keys in JSON contentview

---

CHANGELOG.md
mitmproxy/certs.py

CertStore was inserting raw x509.Certificate objects into default_chain_certs instead of Cert objects, which caused an error later in tlsconfig.py when the certs were used.
This fixes #7354, and has been tested to work locally.

Fix #7354 "AttributeError" from tlsconfig.py

---

web/src/js/components/Modes.tsx

This should fix #7347.
I'm considering whether to include other platforms (e.g., cygwin, msys, etc.): https://stackoverflow.com/questions/446209/possible-values-from-sys-platform.

Invert check for unsupported platforms in local mode (mitmweb)

---

.github/workflows/main.yml
docs/src/layouts/shortcodes/asciicast.html

I encountered this problem because the version of Hugo installed with Homebrew is much newer than the one in CI. I fixed the error and updated Hugo in CI so the build keeps working.
- Does a documentation build fix like this require a CHANGELOG entry?

Fix Hugo deprecation error

---

CHANGELOG.md
mitmproxy/net/http/http1/read.py
test/mitmproxy/net/http/http1/test_read.py

For requests with `transfer-encoding: identity`, we want to respect content-length headers or otherwise not expect a body.

Refine handling of invalid request transfer-encodings

---

mitmproxy/tools/web/app.py
web/gen/state_js.py
web/src/js/__tests__/ducks/_tbackendstate.ts
web/src/js/components/Modes.tsx
web/src/js/ducks/backendState.ts

In this PR, I'm exposing `localModeUnavailable` to the frontend. This allows us to display a string explaining why local mode is unavailable on unsupported platforms.

Exposing 'localModeUnavailable' to the frontend

---

examples/contrib/upstream_pac.py

I created this script for use at work and thought I'd contribute it to the examples in case anyone else would find it useful. The script uses pypac to evaluate requests to determine if they should go to a configured upstream proxy or not. In the case of a pac evaluation of direct, it also allows you to configure a direct proxy allowing you to use 2 proxies if needed.

Add script to enable use of pac server

---

.github/workflows/main.yml
CHANGELOG.md
docs/src/content/overview-installation.md
examples/addons/websocket-inject-message.py
pyproject.toml
test/individual_coverage.py

All recommended installation methods (https://docs.mitmproxy.org/stable/overview-installation/) ship with Python 3.13 already, we shouldn't drag us down with supporting ancient configurations.

Require Python 3.12+

---

mitmproxy/addons/clientplayback.py
mitmproxy/addons/keepserving.py
mitmproxy/addons/proxyserver.py
mitmproxy/addons/readfile.py
mitmproxy/addons/script.py
mitmproxy/master.py
mitmproxy/proxy/server.py
mitmproxy/tools/web/app.py
mitmproxy/utils/asyncio_utils.py
pyproject.toml
release/selftest.py
test/mitmproxy/utils/test_asyncio_utils.py

The stdlib API has a massive footgun where tasks are garbage-collected mid execution, so we enforce our own wrapper.

Fix use of `asyncio.create_task`

---

CHANGELOG.md
mitmproxy/addons/blocklist.py
test/mitmproxy/addons/test_blocklist.py

`block_list`'s filter expression must not be lowercased and interpreted as-is. Fixes #7450

fix: Remove filter expression lowercasing in block_list addon

---

web/src/js/__tests__/backends/websocketSpec.tsx
web/src/js/backends/websocket.tsx

While implementing the server-side logic to handle the reception of the `updateFilter` message, I quickly realised I was wrong. Unfortunately, during the CONNECTING state, we need to queue messages manually to ensure they're properly sent once the connection is established.
In this PR, I've also added some more tests for the WebSocket component 🙂

Fix bug when sending a message while CONNECTING

---

release/installbuilder/mitmproxy.xml
release/installbuilder/run.ps1

Proposed fix for #7392. Moves `run.ps1` out of `bin` folder to not clutter `%PATH%`.

fix run.ps1 being in %PATH%

---

release/installbuilder/run.ps1

Don't use Windows Terminal if the user explicitly [opted out](https://support.microsoft.com/en-us/windows/command-prompt-and-windows-powershell-for-windows-11-6453ce98-da91-476f-8651-5c14d5777c20).

respect user console preference

---

CHANGELOG.md
mitmproxy/addons/export.py
test/mitmproxy/addons/test_export.py

This fixes a bug where exporting a curl or httpie command with escaped characters would lead to different data being sent. 
Fixes https://github.com/mitmproxy/mitmproxy/issues/7517

Unescape escaped characters in curl and httpie args

---

CHANGELOG.md
docs/src/content/concepts-modes.md

This PR adds documentation for local capture mode to https://docs.mitmproxy.org/stable/concepts-modes/.

docs: add local capture mode

---

mitmproxy/proxy/layers/http/_http2.py

This PR prepares mitmproxy to pass with mypy on the next h2 release.
refs https://github.com/python-hyper/h2/pull/1296

fix type annotations to be compatible with future h2 release

---

CHANGELOG.md
docs/src/content/overview-installation.md

As a Brewfile user, the current installation command in the documentation does not tell me that mitmproxy is a Cask, which is a bit of an inconvenience due to how Brewfile works.
Adding a formulae in a Brewfile is done by adding the line `brew "<formulae>"` while adding a cask in a Brewfile is done by adding the line `cask "<cask>"`
Contrarily to the behavior of the brew install command, adding a formulae line in the Brewfile will not check for a Cask if the formulae does not exist: it will just fail.
The brew install command currently works by first checking if a "mitmproxy" formulae exists in the homebrew repository, then after finding out there is none, it checks for a "mitmproxy" cask in the homebrew repository.
Adding the explicit `--cask` argument allows to skip the unnecessary …

docs: Enhance homebrew installation command for Brewfile users

---

CHANGELOG.md
mitmproxy/contentviews/__init__.py
mitmproxy/contentviews/socketio.py
mitmproxy/tools/console/flowview.py
test/mitmproxy/contentviews/test_socketio.py

This PR implements a socket.io content view and auto-selects it in the "WebSocket Messages" tab if the view mode is set to "Auto" and the request path contains `/socket.io/?`.
This content view hides engine.io ping/pong packets as well as socket.io acknowledgements, so that it's easier to analyze the messages being exchanged. It also prefixes the data with the name of the engine.io/socket.io packet type in a muted color.

Content view for socket.io over websocket transport

---

CHANGELOG.md
mitmproxy/addons/keepserving.py
mitmproxy/addons/proxyserver.py
test/mitmproxy/addons/test_keepserving.py
test/mitmproxy/addons/test_proxyserver.py

This fixes https://github.com/mitmproxy/mitmproxy/issues/7569

keepserving: do not exit before client has disconnected

---

CONTRIBUTING.md

This reverts commit 439e5264eb8aaff74aeb80588b86e13b9f0c320e, which temporarily disabled coverage reporting to work around a PyO3 bug. We should re-add this once the following commands work again:
```
cd test/mitmproxy/addons
pytest --cov mitmproxy.addons.anticache --cov-report term-missing --looponfail test_anticache.py
```
Currently this is at least blocked on the release of cryptography 42.0. :)
refs #6515

Revert "CONTRIBUTING.md: temporarily remove `--cov`"

---

CHANGELOG.md
mitmproxy/proxy/layers/http/_http2.py
test/mitmproxy/proxy/layers/http/test_http2.py

Do not send empty HTTP/2 data frames without EoS bit unless the client sent some

---

CHANGELOG.md
web/src/css/mode.less

Fixes: #7627
Currently this change works on supported browsers only: **Chrome** and **Edge**. Ref: https://developer.chrome.com/docs/css-ui/anchor-positioning-api
https://github.com/user-attachments/assets/a83add47-6282-47db-8c08-6717b1ac9b2e

Adjust popover anchor positioning

---

CHANGELOG.md
web/src/js/flow/utils.ts

Fixes: #7649 
By the way, this temporarily solves the problem, but in the new version (#7617), we won't need it anymore since we're changing the logic for the filters 😄

Fix mitmweb crash when searching/highlighting by ~h/~hq/~hs 

---

release/docker/docker-entrypoint.sh

Ensure mitmproxy uses /home/mitmproxy/.mitmproxy as the config directory even if the mapped volume is owned by host root, preventing fallback to /root/.mitmproxy and CA file regeneration on redeploy. Add `HOME` env confdir in entrypoint to enforce this behavior.
Fixes mitmproxy/mitmproxy#7597

Force confdir to /home/mitmproxy/.mitmproxy when volume is root-owned

---

pyproject.toml
uv.lock

Upgrade tornado to 6.5.0 to fix CVE-2025-47287  
https://github.com/advisories/GHSA-7cx3-6m66-7c5m

Upgrade tornado to 6.5.0 to fix CVE-2025-47287

---

examples/contrib/portfile.py

Convenient when manipulating mitmproxy programmatically, as it's often useful to specify port 0 (for all sorts of servers) but then the user needs a way to retrieve the actual port being used.
mitmproxy logs the bound ports out by default, however because it logs to the fully buffered stdout *and* can generate quite a bit of log, this tends to be inconvenient. Writing out a file at a user-specified location makes it much easier for them to poll, and using json even if there is a minor race the user can just keep reading until they see a valid JSON file.
Closes #7720

Add portfile support

---

web/src/js/__tests__/backends/websocketSpec.tsx
web/src/js/__tests__/components/Header/ConnectionIndicatorSpec.tsx
web/src/js/__tests__/components/Header/__snapshots__/ConnectionIndicatorSpec.tsx.snap
web/src/js/__tests__/ducks/connectionSpec.tsx
web/src/js/backends/websocket.tsx
web/src/js/components/Header/ConnectionIndicator.tsx
web/src/js/ducks/connection.ts

The `connectionEstablished` (now `finishFetching`) should only trigger during startup. This PR fixes that, simplifies the code a bit, and removes the unused offline state.

Web: simplify connection state reducer

---

CHANGELOG.md
mitmproxy/contentviews/_api.py
mitmproxy/contentviews/_view_css.py
mitmproxy/contentviews/_view_javascript.py
pyproject.toml
uv.lock
web/src/js/__tests__/components/contentviews/CodeEditorSpec.tsx
web/src/js/__tests__/components/contentviews/__snapshots__/CodeEditorSpec.tsx.snap
web/src/js/backends/consts.ts
web/src/js/components/contentviews/CodeEditor.tsx

This PR adds syntax highlighting for CSS and JS to mitmproxy/mitmdump and wires up the (still unexposed) mitmweb bits.
Depends on https://github.com/mitmproxy/mitmproxy_rs/pull/266 + release.

add CSS and JS syntax highlighting

---

mitmproxy/master.py

I think the type hint for `Master.opts` is missing a `| None`. There's logic to handle a falsey value, and that's how this test instantiates `Master`:
https://github.com/mitmproxy/mitmproxy/blob/b5ac8e62ea633a7a7211d735fabe6008fb64ece0/test/mitmproxy/test_master.py#L15

Fix type for `Master.opts` to accept `None`

---

.github/workflows/main.yml
CHANGELOG.md

**Update GitHub Actions runner to `windows-2025`**
Some tests have been failing due to the deprecated `windows-2019` runner.
This updates it to `windows-2025`, as suggested in [actions/runner-images#12045](https://github.com/actions/runner-images/issues/12045).

chore: update deprecated windows-2019 github runner image

---

CHANGELOG.md
mitmproxy/tools/web/webaddons.py

https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Authorization
There is no `Authentication` header
No test to update.

fix: update log message with correct header name

---

CHANGELOG.md
mitmproxy/addons/export.py
test/mitmproxy/addons/test_export.py

closes #7664
curl does not generate a content-length header when not given content. This can cause issues with some servers as they require a content-length header for certain http verbs (ex. POST). The changes in this PR adds some logic to add a 0-length content-length when needed.
I changed the signature of `pop_headers` to reflect that it changes the state of the received object in-place.

fix missing content-length header in curl export

---

mitmproxy/addons/core.py
mitmproxy/addons/onboardingapp/__init__.py
mitmproxy/certs.py
mitmproxy/command.py
mitmproxy/dns.py
mitmproxy/http.py
mitmproxy/proxy/commands.py
mitmproxy/proxy/events.py
mitmproxy/proxy/layer.py
mitmproxy/proxy/layers/quic/_stream_layers.py
mitmproxy/tools/console/eventlog.py
mitmproxy/tools/console/flowview.py
mitmproxy/tools/console/master.py
mitmproxy/tools/web/app.py
mitmproxy/utils/human.py
release/release.py
test/conftest.py
test/mitmproxy/net/http/test_multipart.py
test/mitmproxy/proxy/tutils.py
test/mitmproxy/tools/console/test_commander.py

- Run pyupgrade for Python 3.12+
- Use `!r` flag instead of `repr()` in f-strings
- Remove redundant `str()` in f-strings
- Use self-documenting f-strings

Run pyupgrade and improve f-strings

---

CHANGELOG.md
mitmproxy/tools/web/app.py
mitmproxy/tools/web/webaddons.py
test/mitmproxy/tools/web/test_app.py

Fix auth cookie always using the default `web_port` option.

---

.github/dependabot.yml

uv has its own package ecosystem.
After merging this, you can manually trigger dependabot to run by going to the insights tab -> dependency graph -> dependabot (note: this tab is not accessible to the public) -> "Recent update jobs" next to pyproject.toml -> then click on "check for update".
This is also where you can find the logs of dependabot runs and it's where you will be best able to troubleshoot.
Feel free to follow up (with logs) in #7859 if things don't work.

Switch dependabot from pip to uv
